- pkg/controllers/ocp-controllers.go
> wait for ocp apiserver resource

- hack/patches/0006_443635d.patch
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
> handle signal to terminate program

- pkg/assets/crd.go
- pkg/controllers/apiservice.go
- pkg/controllers/ocp-controllers.go
still missing `templateinstances.template.openshift.io` CRD
> applying necessary crds

- install.sh
> Get latest release version to download

- hack/all-in-one/Dockerfile
- hack/all-in-one/README.md
- hack/all-in-one/kubelet-cgroups.conf
- pkg/config/kubelet.go
- pkg/node/kubelet.go
I have built a container `docker.io/rootfs/ushift:macos` for testing
[![asciicast](https://asciinema.org/a/MJZ69vE544HEUi2fpmwtcGpZe.svg)](https://asciinema.org/a/MJZ69vE544HEUi2fpmwtcGpZe)
> enable containerized microshift on MacOS

- cmd/microshift/main.go
- pkg/cmd/controller.go
- pkg/config/config.go
- pkg/controllers/kube-api.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/ocp-controllers.go
- pkg/node/kubelet.go
> Add v-level logging, pass to K8s components

- install.sh
Otherwise it requires interactive input for the user password
> Enabling firewall requires sudo

- install.sh
> Add OR if the system has already been registered

- install.sh
> Check if subscribed and proper repos

- Makefile
- images/build/Dockerfile
- scripts/release.sh
Add generated checksum file to release
> Handle podman divergence in cli commands, add checksum

- install.sh
> Fix retrieval of VERSION

- pkg/servicemanager/manager.go
- pkg/servicemanager/manager_test.go
- pkg/util/sigchannel/sigchannel.go
- pkg/util/sigchannel/sigchannel_test.go
> Improve test coverage

- pkg/util/sigchannel/sigchannel.go
> Fix high CPU load issue

- pkg/util/sigchannel/sigchannel.go
> Simplify CPU load fix

- install.sh
Add hostname check to script
for the issue I created https://github.com/redhat-et/microshift/issues/176
> adding validation check function for hostname

- Makefile
> release tag should not have git-dirty data

- Makefile
- scripts/release.sh
> fix release.sh bug

- assets/apps/000_80_hostpath-provisioner-daemonset.yaml
- pkg/assets/apps/bindata.go
> set hostpath version

- scripts/release.sh
> fixed git org naming

- hack/all-in-one/unit
- install.sh
Add crio service dependency on systemd units.
> Add crio dependency on systemd services

- hack/all-in-one/Dockerfile
**Which issue(s) this PR addresses**: #236 
Closes #236
> use ubi-init base image

- hack/all-in-one/Dockerfile
follow up ubi image refactoring. This PR is to download the right kubectl.
> fix kubectl download path

- CONTRIBUTING.md
- README.md
> Adds minimum requirements

- pkg/node/kubelet.go
Closes #247
also could impact kubelet refactor #217
> fix crio sock deprecation warning

- install.sh
> set selinux always

- Makefile
> only verify project code

- pkg/cmd/version.go
> Print base OKD version

- install.sh
> Remove IPv6 CNI config

- README.md
> Add e2e demo video link to README

- pkg/cmd/run.go
- pkg/config/kubelet.go
- pkg/node/kubelet.go
https://github.com/redhat-et/microshift/issues/201
Closes #201
> Refactor Kubelet to conform to the internal service manager

- pkg/cmd/run.go
- pkg/node/kubelet.go
**Which issue(s) this PR addresses**: https://github.com/redhat-et/microshift/issues/229
Closes #229
> kube-proxy conforms to internal service manager

- install.sh
> Make hostname validation show warning and not stop installation

- install.sh
- selinux/microshift.fc
- selinux/microshift.te
Closes #85 
This should only be a placeholder until we get into https://github.com/containers/container-selinux/blob/main/container.fc
That should be the next goal from there it would be important to see how long it would be until we get into the specific OS channels.
Also, @copejon we may want to ship the microshift.pp file rather than generate one but I wanted to have this up for @sallyom to review
> initial commit of selinux

- install.sh
Completes the integration of Selinux
> build and enable selinux

- scripts/release.sh
> Tag latest

- README.md
> Adds minimum requirements for README.md

- README.md
Adds community information to README
> Community info

- README.md
Finishes up Selinux integration
> removal of selinux warning

- hack/all-in-one/Dockerfile
- hack/all-in-one/crio-bridge.conf
> Remove CNI IPv6 configuration and use right conmon binary for AIO container images

- README.md
- docs/known-issues.md
Signed-off-by: Ian Zhang <izhang@redhat.com>
> add known issue doc for running on EC2 RHEL

- pkg/cmd/init.go
Signed-off-by: Ian Zhang <izhang@redhat.com>
> respect the config.Cluster.ServiceCIDR when signing certs

- hack/all-in-one/README.md
This fixes a typo in aio-readme :)
> typo-aio-readme

- docs/known-issues.md
Signed-off-by: Ian Zhang <izhang@redhat.com>
> update known issue for flannel issue on ec2

- hack/all-in-one/Dockerfile
- hack/all-in-one/nvidia-config.toml
Add nvidia container kit so to enable gpu operator installation
> install nvidia container kit in aio image

- install.sh
also fail fast if running on unsupported arch
```
ubuntu@kitkat:~$ curl -sfL https://raw.githubusercontent.com/jbpratt/microshift/install-support-arm64/install.sh --output arm64-install.sh
ubuntu@kitkat:~$ vim arm64-install.sh
ubuntu@kitkat:~$ chmod +x arm64-install.sh
ubuntu@kitkat:~$ ./arm64-install.sh
======================================================================
!!! WARNING !!!
The hostname kitkat does not follow FQDN, which might cause problems while operating the cluster.
See: https://github.com/redhat-et/microshift/issues/176
If you face a problem or want to avoid them, please update your hostname and try again.
Example: 'sudo hostnamectl set-hostname kitkat.example.com'
======================================================================
Reading package lists... Done …
```
> add arm64 support to the install script

- hack/all-in-one/Dockerfile
- hack/all-in-one/build-images.sh
This is an alternative to #304.
Co-Authored-By: Huamin Chen <hchen@redhat.com>
> Legacy and nft-tables based images matrix

- README.md
> Updates storage requirement to more accurately reflect binary size

- install.sh
Currently cri-o repos are provided only for the following Ubuntu versions:
https://github.com/cri-o/cri-o/blob/v1.20.5/install.md#apt-based-operating-systems
* Ubuntu 20.04
* Ubuntu 19.10
* Ubuntu 19.04
* Ubuntu 18.04
Thus, even though this pull addresses Ubuntu version parameterisation, we really need to wait for cri-o to support Ubuntu versions >20.04 to fully fix #285. See: https://github.com/cri-o/cri-o/issues/4713
Tested with 20.04 and 18.04.
> Enable install.sh to run on multiple Ubuntu versions #285

- Makefile
> drop static-build flags

- Makefile
**Which issue(s) this PR addresses**: 402
Closes #402
> Updating K8s version to show the right one

- Makefile
> typo-make-docs

- pkg/cmd/run.go
- pkg/controllers/infra-services-controller.go
- pkg/controllers/openshift-api-components-controller.go
- pkg/controllers/openshift-apiserver.go
- pkg/controllers/openshift-oauth-server.go
- pkg/controllers/openshift-prepjob-manager.go
Refactor OCPAPIServer to conform to the internal service manager
> Refactor OCPAPIServer to conform to the internal service manager

- install.sh
This PR contains:
- Pre-checks into the install.sh script to verify previously the CPU, Mem and disk
> Pre-checks into install.sh

- README.md
> quick fix of readme

- install.sh
Selinux process should be ran on CONFIG_ONLY runs and run restorecon on the binary only if binary is going to exist
> selinux containerized ordering

- install.sh
Fixes a containerized microshift issue
> issue restorecon

- docs/design/design.md
* Add design documentation
* Address review comments
* Update docs/design/design.md
Co-authored-by: Miguel Angel Ajo Pelayo <miguelangel@ajo.es>
Co-authored-by: Miguel Angel Ajo Pelayo <miguelangel@ajo.es>
> Restore design documentation (#218)

- pkg/config/config.go
> Add log directory to MicroShift config

- README.md
Documentation patch up
Closes #454
> resolves #454

- install.sh
**Which issue(s) this PR addresses**: https://github.com/redhat-et/microshift/issues/466
> fix: set cri-o version to 1.21

- packaging/images/microshift-aio/Dockerfile
The download path for CRI-O repos has changed, need to update the AIO Dockerfile with new path.
> download path for cri-o repos has changed, update Dockerfile

- .github/workflows/ubuntu.yaml
- Makefile
- validate-microshift/.gitignore
- validate-microshift/kuttl-test.sh
Extracts the kuttl operations to a script to make the usable in CI operations.
> move kuttl cmds to script for reuse in CI

- validate-microshift/e2e/microshift/10-assert.yaml
- validate-microshift/e2e/microshift/15-assert.yaml
- validate-microshift/e2e/microshift/20-assert.yaml
- validate-microshift/e2e/microshift/25-assert.yaml
- validate-microshift/e2e/microshift/30-assert.yaml
- validate-microshift/e2e/microshift/35-assert.yaml
- validate-microshift/e2e/microshift/40-assert.yaml
This would allow us to have some simplier testing for readiness
> is up testing

- validate-microshift/e2e/microshift/25-assert.yaml
- validate-microshift/e2e/microshift/35-assert.yaml
@cooktheryan typo in kuttl tests
> update kuttl tests

- .github/workflows/testing.yaml
- pkg/config/config_test.go
- test/config.yaml
Adds unit-testing into GitHub Actions
> adds GH Action +  unit-tests

- .github/workflows/ubuntu.yaml
Now that testing is more mature we can potentially turn down this test. The compiling may be worth keeping
> Disable ubuntu ci job

- pkg/controllers/openshift-controller-manager.go
> Fix ocp cm namespace

- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-oauth-server.go
- pkg/node/kube-proxy.go
- pkg/node/kubelet.go
> Remove stray log messages

- packaging/crio.conf.d/microshift.conf
- packaging/rpm/microshift.spec
- Prevent crio from wiring pods until the CNI is ready
- Require iptables from microshift spec
> spec req iptables

- packaging/rpm/microshift.spec
This will create the directories on the target and ensure proper labeling of /var/hpvolumes
Closes #522
> selinux create directories

- .github/workflows/temp-release.yaml
- Makefile
- hack/temp-release.sh
> hack to temp fix releases

- scripts/release.sh
I think this will fix the image tagging in order to remove the workaround (https://github.com/redhat-et/microshift/pull/536)
> fix release.sh

- .github/workflows/temp-release.yaml
Reverts redhat-et/microshift#537
Remove this first then the other
> Revert "Update temp-release.yaml"

- .github/workflows/release.yaml
Currently builds are broken due to bad mirrors. This fixes the bad mirrors
> Fix of mirrors for release.sh

- README.md
> fix broken OCM link

- pkg/config/config.go
- pkg/util/net.go
> Use 127.0.0.1 as HostIP if no IP is available

- pkg/controllers/openshift-default-scc-manager.go
> Exit MicroShift if scc apply fails

- validate-microshift/e2e/microshift/65-create-argo-resources.sh
- validate-microshift/e2e/microshift/65-create-argo-resources.yaml
- validate-microshift/e2e/microshift/66-assert-deployment.yaml
- validate-microshift/e2e/microshift/67-assert-deployment.yaml
- validate-microshift/e2e/microshift/68-assert-deployment.yaml
- validate-microshift/e2e/microshift/69-assert-deployment.yaml
- validate-microshift/e2e/microshift/70-create-argo-deployment.sh
- validate-microshift/e2e/microshift/70-create-argo-deployment.yaml
- validate-microshift/e2e/microshift/75-assert-deployment.yaml
- validate-microshift/e2e/microshift/80-remove-created-items.sh
- validate-microshift/e2e/microshift/80-remove-created-items.yaml
Signed-off-by: Ryan Cook <rcook@redhat.com>
Test suite to ensure that external resources can be accessed such as a git repo or in the future a RHACM deployment. This helps to verify correct DNS functionality
> DNS testing: complex application deployment with url request

- .github/workflows/release_to_copr.yaml
> Add after-release step triggering srpm/rpm build

- pkg/controllers/kube-controller-manager.go
> Make kube-controller-manager service return errors

- scripts/release.sh
> fix typo in reference

- pkg/cmd/run.go
> Format value of error for stopped services

- assets/components/hostpath-provisioner/storageclass.yaml
- pkg/assets/bindata.go
> add default annotation to kubevirt-hostprovisioner storageclass

- packaging/rpm/paack.py
> Fix typo in paack.py

- .github/ISSUE_TEMPLATE/enhancement-tracking.md
- .github/PULL_REQUEST_TEMPLATE.md
- docs/README.md
- hack/all-in-one/Dockerfile
- hack/install.sh
- packaging/images/microshift-aio/Dockerfile
- packaging/images/microshift/Dockerfile
- packaging/images/openshift-ci/Dockerfile
- packaging/rpm/example-user-containers.yaml
- packaging/rpm/make-microshift-images-rpm.sh
- packaging/rpm/microshift.spec
- pkg/cmd/run.go
This PR updates links in the project to reflect the new home of MicroShift.
> Update links post org transfer

- pkg/cmd/run.go
- pkg/controllers/openshift-apiserver.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-crd-manager.go
> Add openshift-apiserver as dependency for OCM

- pkg/controllers/openshift-apiserver.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-crd-manager.go
- pkg/controllers/openshift-oauth-server.go
> Replacing ocp by openshift for naming consistency

- scripts/image-builder/configure.sh
yum-utils is needed for reposync
selinux-policy-devel is needed for the RPM build
> image-builder: add missing dependencies

- README.md
- docs/README.md
Update top-level README.md file with the proper text and links to the remaining docs.
[USHIFT-73](https://issues.redhat.com//browse/USHIFT-73)
> Update top-level README and remove docs/README file

- README.md
Added system and edge deployment requirements to top-level README file 
[USHIFT-31](https://issues.redhat.com//browse/USHIFT-31)
> Added system and edge deployment requirements to top-level README file 

- pkg/node/kubelet.go
Cobra cli parsing code is no longer needed,
since options can be used in structs.
[USHIFT-101](https://issues.redhat.com/browse/USHIFT-101)
> USHIFT-101: Remove dead configuration code for Kubelet

- assets/crd/0000_03_security-openshift_01_scc.crd.yaml
- pkg/assets/bindata.go
- pkg/controllers/apiservice.go
- pkg/controllers/openshift-apiserver.go
Closes [USHIFT-98
](https://issues.redhat.com/browse/USHIFT-98)
> Remove Security API service and use local server for SCC objects

- docs/rebase.md
This is the documentation of the rebase process at the state after #737 merges.
Closes [USHIFT-65](https://issues.redhat.com//browse/USHIFT-65)
> Document rebase script

- docs/design.md
- docs/enable_apis.md
[USHIFT-47](https://issues.redhat.com//browse/USHIFT-47)
> Document supported OpenShift APIs

- scripts/rebase.sh
Uses a combination of `go mod edit` and `go mod tidy` to generate pseudo versions instead of "manually" constructing them. This handles all format types correctly according to spec and is more robust, but unfortunately also quite a bit slower.
> More accurate pseudoversions

- docs/devenv_rhel8.md
Update redhat-et reference to openshift
> Update devenv redhat-et to openshift repo

- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-apiserver.go
- pkg/controllers/openshift-controller-manager.go
- pkg/node/kube-proxy.go
- pkg/node/kubelet.go
- pkg/util/kubeconfig.go
also, small fix to the apiserver-audit-log path
Closes [USHIFT-84](https://issues.redhat.com/browse/USHIFT-84)
> tighten permissions on configuration data files

- pkg/controllers/openshift-apiserver.go
Closes [USHIFT-132](https://issues.redhat.com/browse/USHIFT-132)
> USHIFT-132: Disable Admission Plugins for non-used APIs

- packaging/crio.conf.d/microshift-ovn.conf
- packaging/rpm/microshift.spec
Closes [USHIFT-143](https://issues.redhat.com/browse/USHIFT-143) and [USHIFT-144](https://issues.redhat.com/browse/USHIFT-144)
> CRIO config for OVN-K CNI plugin

- packaging/systemd/configure-ovs.sh
otherwise it breaks on reboot.
> Trigger br-ex configuration only once in MicroShift

- assets/components/ovn/clusterrole.yaml
- assets/components/ovn/clusterrolebinding.yaml
- assets/components/ovn/configmap.yaml
- assets/components/ovn/master/daemonset.yaml
- assets/components/ovn/master/serviceaccount.yaml
- assets/components/ovn/namespace.yaml
- assets/components/ovn/node/daemonset.yaml
- assets/components/ovn/node/serviceaccount.yaml
- assets/components/ovn/role.yaml
- assets/components/ovn/rolebinding.yaml
- hack/cleanup.sh
- packaging/crio.conf.d/microshift-ovn.conf
- packaging/rpm/microshift.spec
- pkg/assets/bindata.go
- pkg/assets/core.go
- pkg/components/components.go
- pkg/components/controllers.go
- pkg/components/networking.go
- pkg/components/render.go
- pkg/release/release.go
- pkg/release/release_amd64.go
- pkg/release/release_arm64.go
Closes [USHIFT-149](https://issues.redhat.com/browse/USHIFT-149)
> ovn-kubernetes as default CNI plugin

- packaging/rpm/microshift.spec
Just a nit for consistency.
Related to https://issues.redhat.com/browse/USHIFT-144
> Move crio.conf.d/microshift-ovn.conf to microshift-networking

- packaging/network-manager-conf/microshift-nm.conf
- packaging/rpm/microshift.spec
This PR allows OVS initialization with IP static addressing
Closes #[USHIFT-222](https://issues.redhat.com/browse/USHIFT-222)
> USHIFT-222: Add NetworkManager configuration file

- docs/rebase.md
Update the documentation of the rebase process following the recent improvements in #771, #802, and #805. Also, minor formatting changes to keep linter happy.
> Update rebase doc to reflect recent improvements

- scripts/bindata.sh
> Skip non-yaml files when generating bindata

- hack/cleanup.sh
- packaging/rpm/microshift.spec
- packaging/systemd/configure-ovs.sh
Closes [USHIFT-236](https://issues.redhat.com//browse/USHIFT-236)
> Fix openvswitch issues when MicroShift service is disabled

- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
- pkg/components/networking.go
- pkg/components/render.go
> ovnk: get kubeconfig dir from microshift config

- pkg/assets/bindata.go
- scripts/bindata.sh
Address the permission issue noticed in #818
> USHIFT-241: Asset permissions

- OWNERS
Based on his excellent work with the OVN component and
his good understanding of MicroShift and the project
goals.
Suggested by @dhellmann, ack by @fzdarsky @oglok @mangelajo
> Proposing Zenghui Shi as reviewer/approver

- README.md
- docs/default_csi_plugin.md
This PR adds some minimal documentation describing the default storage plugin, prerequisites, and provides an example workload.
Closes [USHIFT-126](https://issues.redhat.com//browse/USHIFT-126)
> USHIFT-126: Minimal CSI Plugin documentation

- docs/devenv_rhel8.md
- docs/howto_firewall.md
- scripts/image-builder/config/kickstart.ks.template
Closes [USHIFT-244](https://issues.redhat.com//browse/USHIFT-244) & [USHIFT-245](https://issues.redhat.com//browse/USHIFT-245)
> Update firewall settings to reflect the requirements imposed by OVN-k

- pkg/release/release_arm64.go
> Use the arm64 image for OVNk in release_arm64.go

- scripts/image-builder/config/kickstart.ks.template
Closes [USHIFT-253](https://issues.redhat.com//browse/USHIFT-253)
> Remove firewall rules reload command from kickstart

- scripts/rebase.sh
Extension of the rebase script to add the "staging" directive used by PR #804.
Signed-off-by: Frank A. Zdarsky [fzdarsky@redhat.com](mailto:fzdarsky@redhat.com)
[USHIFT-224](https://issues.redhat.com//browse/USHIFT-224)
> Add staging directive to rebase script

- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
Closes: https://issues.redhat.com/browse/USHIFT-237
This is a rebased version of Pablo's work here: https://github.com/openshift/microshift/pull/818
> Tolerate any taints in ovnkube-master daemonset

- docs/rebase.md
[USHIFT-224](https://issues.redhat.com//browse/USHIFT-224)
> docs: fix command name in rebase instructions

- docs/design.md
> update storage notes in design docs

- docs/design.md
/assign @zshi-redhat @mangelajo
> update networking notes in design docs

- docs/config/amq-broker.yaml
- docs/howto_amq_broker.md
Enhance AMQ Broker example with persistent storage
Closes: [USHIFT-220](https://issues.redhat.com//browse/USHIFT-220)
> Implement AMQ Broker message persistency

- assets/components/service-ca/clusterrolebinding.yaml
- assets/components/service-ca/deployment.yaml
- pkg/assets/bindata.go
Closes [USHIFT-286](https://issues.redhat.com/browse/USHIFT-286)
> USHIFT-286: Run Service CA component as non root

- docs/devenv_rhel8.md
- docs/devenv_rhel8_auto.md
- docs/howto_firewall.md
- scripts/devenv-builder/config/kickstart.ks.template
- scripts/devenv-builder/configure-vm.sh
- scripts/devenv-builder/create-vm.sh
Automate RHEL8 devenv creation and configuration
> USHIFT-315: Automate RHEL8 devenv creation and configuration

- assets/components/odf-lvm/topolvm-openshift-storage_namespace.yaml
- assets/components/openshift-dns/dns/namespace.yaml
- assets/components/openshift-router/namespace.yaml
- assets/components/service-ca/ns.yaml
- assets/core/0000_50_cluster-openshift-controller-manager_00_namespace.yaml
- assets/core/namespace-openshift-infra.yaml
- pkg/assets/bindata.go
Closes #[USHIFT-332](https://issues.redhat.com/browse/USHIFT-332)
> USHIFT-332: Cleanup TopoLVM webhook labels

- hack/cleanup.sh
Closes #[USHIFT-324](https://issues.redhat.com//browse/USHIFT-324)
> Always do force cleanup

- scripts/devenv-builder/create-vm.sh
> remove os-type argument to eliminate warning message when creating VM

- .github/ISSUE_TEMPLATE/bug-report.md
- docs/howto_sysconf_watch.md
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/config/config_test.go
- pkg/controllers/cluster-policy-controller.go
- pkg/controllers/etcd.go
- pkg/controllers/infra-services-controller.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-crd-manager.go
- pkg/controllers/openshift-default-scc-manager.go
- pkg/mdns/server/resolver.go
- pkg/mdns/server/server.go
- pkg/node/kubelet.go
- pkg/release/release.go
- pkg/release/release_amd64.go
- pkg/release/release_arm64.go
- pkg/sysconfwatch/sysconfwatch_linux.go
- pkg/util/cert.go
- pkg/util/kubeconfig.go
- pkg/util/net.go
- scripts/release.sh
Replace Microshift by MicroShift in two commits:
- With "Match Whole Word"
- ~~Without "Match Whole Word"~~
> USHIFT-136: Replace Microshift by MicroShift 

- docs/devenv_rhel8_auto.md
- scripts/devenv-builder/config/kickstart.ks.template
- scripts/devenv-builder/create-vm.sh
Add swap space to the development environment setup
Closes: [USHIFT-315](https://issues.redhat.com//browse/USHIFT-315)
> USHIFT-315: Add swap space to the development environment setup

- OWNERS
Update approvers and reviewers.
> add new member to owners list

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-tracking.md
> Update issue templates for bugs and ERs

- docs/devenv_rhel8.md
- scripts/devenv-builder/configure-vm.sh
Fix devenv configuration procedure: missing sudo and rephrasing of documentation text
> Fix devenv configuration procedure

- docs/howto_load_balancer.md
Closes [USHIFT-325](https://issues.redhat.com//browse/USHIFT-325)
> USHIFT-325: Update MetalLB howto with the instructions on how to work with the latest software

- hack/tests-static-analysis/README
- hack/tests-static-analysis/go.mod
- hack/tests-static-analysis/go.sum
- hack/tests-static-analysis/main.go
Closes [USHIFT-256](https://issues.redhat.com/browse/USHIFT-256)
> USHIFT-256 OpenShift tests static analysis

- scripts/image-builder/build.sh
- scripts/image-builder/configure.sh
This saves a couple of minutes of building in my environment since lorax
is installed just once on the system the first time.
> Use lorax outside of container during iso creation

- assets/components/ovn/master/daemonset.yaml
- assets/components/ovn/node/daemonset.yaml
- pkg/assets/bindata.go
Closes #[NP-538](https://issues.redhat.com//browse/NP-538)
> Reconcile ovnk in case node IP changes

- assets/components/ovn/configmap.yaml
- pkg/assets/bindata.go
- pkg/components/render.go
- pkg/config/config.go
- pkg/config/config_test.go
Closes #[USHIFT-369](https://issues.redhat.com//browse/USHIFT-369)
> add mtu config option

- scripts/image-builder/build.sh
- scripts/image-builder/config/custom-rpms.toml.template
- scripts/image-builder/config/microshift-local.toml.template
- scripts/image-builder/config/openshift-local.toml.template
https://issues.redhat.com/browse/USHIFT-382
> USHIFT-362: toml.template url updates.

- packaging/microshift/config.yaml
- pkg/config/config.go
> USHIFT-375: fix capitalization in show-config output

- docs/devenv_rhel8.md
- packaging/rpm/make-rpm.sh
Follow-up on #931 
Closes [USHIFT-362](https://issues.redhat.com//browse/USHIFT-362)
> USHIFT-362: Fix microshift executable location in the devenv docs

- pkg/util/kubeconfig.go
This uses the upstream code for writing kubeconfigs and removes the unused "Kubeconfig()" function.
> USHIFT-278: util: write kubeconfigs using the upstream code

- pkg/servicemanager/manager.go
- scripts/rebase_patches/0020-klog-component-names.patch
- vendor/k8s.io/klog/v2/goroutine_labels.go
Fixes spelling of MicroShift in klog.WithMicroshiftLoggerComponent.
> Fix spelling

- scripts/rebase.sh
> Update OCM and CPC requirements

- pkg/cmd/init.go
Closes #[416](https://issues.redhat.com/browse/USHIFT-416)
> USHIFT-416: Clean up unused cert management code

- scripts/create_pr.py
- scripts/rebase.sh
Closes  [USHIFT-179](https://issues.redhat.com/browse/USHIFT-179)
Adds python script for PR creation using `pygithub` library to interact with GitHub API (more info in script's docstring)
Needs to be merged before https://github.com/openshift/microshift/pull/974
> USHIFT-179: PR creator

- docs/openshift_ci.md
- scripts/create_pr.py
> USHIFT-179 Create PR script improvements & doc

- scripts/rebase.sh
Run "go fmt" after modifying the image pull specs to make CI happy.
> Run go fmt after updating release images

- docs/howto_config.md
- pkg/config/config.go
- pkg/kustomize/apply.go
Closes [USHIFT-328](https://issues.redhat.com//browse/USHIFT-328)
> USHIFT-328: Fix and document automatic manifest apply on startup

- scripts/image-builder/build.sh
This PR adds a `-prometheus` flag to the image-builder build script. At the moment that is specifically the process-exporter which provides pidstat like data for all host processes. 
Small bugfixes for `build.sh` also included as well as firewall customization to allow inbound connections to the exporter.
> USHIFT-445: Add prometheus exporter for RHEL4EDGE

- ansible/README.md
- ansible/inventory/inventory
- ansible/roles/common/tasks/readinesscheck.yml
- ansible/roles/install-logging-exporters/defaults/main.yml
- ansible/roles/install-logging-exporters/tasks/main.yml
- ansible/roles/install-logging-exporters/templates/cadvisor.service.j2
- ansible/roles/install-microshift/tasks/main.yml
- ansible/roles/manage-repos/tasks/main.yml
- ansible/roles/microshift-start/tasks/main.yml
- ansible/roles/setup-microshift-host/defaults/main.yml
- ansible/roles/setup-microshift-host/tasks/main.yml
- ansible/run-perf.yml
- ansible/setup-node.yml
- ansible/vars/all.yml
Closes [USHIFT-442](https://issues.redhat.com//browse/USHIFT-442)
> USHIFT-442: Refactor logging exporters installation and update docs

- assets/crd/authorizationv1-local-apiservice.yaml
- pkg/assets/bindata.go
- pkg/assets/crd.go
Closes [USHIFT-450](https://issues.redhat.com//browse/USHIFT-450)
> USHIFT-450: Fix namespace deletion

- docs/howto_config.md
- pkg/config/config_test.go
Closes [USHIFT-327](https://issues.redhat.com//browse/USHIFT-327)
> USHIFT-327: Update documentation with the supported configuration options

- assets/core/podsecurity-admission-label-syncer-controller-clusterrole.yaml
- assets/core/podsecurity-admission-label-syncer-controller-clusterrolebinding.yaml
- pkg/assets/bindata.go
- pkg/controllers/infra-services-controller.go
- scripts/auto-rebase/rebase.sh
Closes [USHIFT-461](https://issues.redhat.com//browse/USHIFT-461)
> USHIFT-461: Add PSA clusterrole and clusterrolebinding

- scripts/auto-rebase/create_pr.py
Because nightlies can be not accepted for several days, job that runs each day would push-force the same changes.
This change forcefully pushes new rebase branch only if it starts on newer main commit and won't update remote branch if there's no difference.
> Improve create_pr.py with branch-off commit logic

- docs/devenv_rhel8.md
- docs/rhel4edge_iso.md
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
Closes [USHIFT-452](https://issues.redhat.com//browse/USHIFT-452)
> USHIFT-452: Update docs to 4.12 pre

- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
This reverts commit a81d1d39b4093cbd142db166c7f5949ff71afd00.
Closes-Issue: https://issues.redhat.com/browse/USHIFT-451
> Revert "microshift: compact ovn databases periodically"

- assets/components/openshift-router/deployment.yaml
- assets/core/0000_50_cluster-openshift-controller-manager_00_namespace.yaml
- pkg/assets/bindata.go
- scripts/auto-rebase/rebase.sh
Closes [USHIFT-459](https://issues.redhat.com//browse/USHIFT-459)
> USHIFT-459: Add hostport to ingress

- assets/components/odf-lvm/topolvm-node_daemonset.yaml
- pkg/assets/bindata.go
- pkg/components/render.go
- pkg/components/render_test.go
Fixes [USHIFT-484](https://issues.redhat.com//browse/USHIFT-484)
> USHIFT-484: Fix template data ref

- README.md
- docs/config/microshift-starter.ks
- docs/getting_started.md
Closes [USHIFT-492](https://issues.redhat.com//browse/USHIFT-492)
> USHIFT-492: Document getting-started procedure from microshift-testing copr repo

- docs/rhel4edge_iso.md
- hack/osbuild2copr.sh
- scripts/image-builder/build.sh
- scripts/image-builder/config/ostree-copr.toml
- scripts/image-builder/configure.sh
Closes [USHIFT-205](https://issues.redhat.com//browse/USHIFT-205)
> USHIFT-205: Add an option for embedding containers using Image Builder

- packaging/crio.conf.d/microshift_amd64.conf
- packaging/crio.conf.d/microshift_arm64.conf
- packaging/rpm/microshift.spec
- pkg/release/release.go
- pkg/release/release_amd64.go
- pkg/release/release_arm64.go
- scripts/auto-rebase/rebase.sh
Related to [USHIFT-499](https://issues.redhat.com//browse/USHIFT-499)
> USHIFT-499: Replace k8s pause image with openshift pod image

- scripts/auto-rebase/create_pr.py
It appears that repository cloned during job [does not have any remotes](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/33585/rehearse-33585-periodic-ci-openshift-microshift-main-periodics-rebase-on-nightlies/1586622210892632064/artifacts/rebase-on-nightlies/openshift-microshift-rebase/build-log.txt):
```
+ git remote -v
+ exit 1
```
so trying to fetch origin branches [fails](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-microshift-main-periodics-rebase-on-nightlies/1586583793873981440/artifacts/rebase-on-nightlies/openshift-microshift-rebase/build-log.txt):
```
+ ./scripts/auto-rebase/create_pr.py
Traceback (most recent call last):
File "./scripts/auto-rebase/create_pr.py", line 68, …
```
> Fix missing remote in rebase script

- Makefile
- pkg/release/get.sh
- scripts/verify_images.sh
Related to [USHIFT-499](https://issues.redhat.com//browse/USHIFT-499)
> add verify job step for image locations

- Makefile
- packaging/rpm/microshift.spec
- Set a format for changelog history messages as a comment in the microshift.spec file
```
```
- Review and update spec file change log 
- Fix notorious error message from Makefile
```
fatal: No names found, cannot describe anything.
```
Closes [USHIFT-428](https://issues.redhat.com//browse/USHIFT-428)
> USHIFT-428: Update change history in microshift.spec file

- scripts/auto-rebase/rebase.sh
Do not remove assets introduced in https://github.com/openshift/microshift/pull/1031
> rebase.sh: openshift-router's serving cert

- docs/getting_started.md
This is a minor PR to update the wording of the getting_started doc. It does not introduce changes to MicroShift function. 
/cc @ggiguash
> USHIFT-492: Update, clarify getting_started doc

- ansible/roles/setup-microshift-host/defaults/main.yml
- ansible/roles/setup-microshift-host/tasks/main.yml
Missed some changes to the Ansible scripts as part of https://github.com/openshift/microshift/pull/1059
> Add golang package back to setup-microshift-host

- docs/openshift_ci.md
Closes [#243](https://issues.redhat.com/browse/USHIFT-243)
> USHIFT-243: Update openshift CI instructions to run local tests

- validate-microshift/kuttl-test.sh
> USHIFT-210: Add debug info in case of kuttl failure

- images/build/Dockerfile
Closes [USHIFT-603](https://issues.redhat.com//browse/USHIFT-603)
> Remove orphaned files

- assets/components/odf-lvm/csi-driver.yaml
- assets/components/odf-lvm/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/components/odf-lvm/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- assets/components/odf-lvm/topolvm-controller_v1_serviceaccount.yaml
- assets/components/odf-lvm/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/components/odf-lvm/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- assets/components/odf-lvm/topolvm-csi-provisioner_rbac.authorization.k8s.io_v1_rolebinding.yaml
- assets/components/odf-lvm/topolvm-csi-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- assets/components/odf-lvm/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/components/odf-lvm/topolvm-csi-snapshotter_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- assets/components/odf-lvm/topolvm-leader-election_rbac.authorization.k8s.io_v1_role.yaml
- assets/components/odf-lvm/topolvm-leader-election_rbac.authorization.k8s.io_v1_rolebinding.yaml
- assets/components/odf-lvm/topolvm-metrics_rbac.authorization.k8s.io_v1_role.yaml
- assets/components/odf-lvm/topolvm-metrics_rbac.authorization.k8s.io_v1_rolebinding.yaml
- assets/components/odf-lvm/topolvm-node-metrics_v1_service.yaml
- assets/components/odf-lvm/topolvm-node_daemonset.yaml
- assets/components/odf-lvm/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/components/odf-lvm/topolvm-node_v1_serviceaccount.yaml
- assets/components/odf-lvm/topolvm.io_logicalvolumes.yaml
- assets/components/odf-lvm/topolvm_default-storage-class.yaml
- pkg/assets/crd.go
- pkg/release/release_amd64.go
- pkg/release/release_arm64.go
Closes [USHIFT-434](https://issues.redhat.com//browse/USHIFT-434)
> USHIFT-434: Update TopoLVM to 4.12 version and pull images from quay.io/rh-storage-partners/microshift-topolvm repo

- docs/config/microshift-starter.ks
- docs/getting_started.md
Closes [USHIFT-610](https://issues.redhat.com//browse/USHIFT-610)
> Fix the getting started procedure to work with RHEL 8.7 and OCP public mirror repo

- assets/components/kube-controller-manager/defaultconfig.yaml
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-controller-manager_test.go
- scripts/auto-rebase/rebase.sh
- scripts/auto-rebase/rebase_patches/0030-kube-controller-manager-command-context.patch
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
> WRKLDS-604: Enable the Openshift flavor of the kube-controller-manager

- assets/components/openshift-router/deployment.yaml
- scripts/auto-rebase/rebase.sh
Co-authored-by: Miguel Angel Ajo Pelayo <majopela@redhat.com>
> USHIFT-625 Fix router graceful shutdown time unit

- assets/components/odf-lvm/topolvm-controller_deployment.yaml
- assets/components/odf-lvm/topolvm-node_daemonset.yaml
https://docs.google.com/spreadsheets/d/1eLBkG4HhlKlxRlB9H8kjuXs5F3zzVOPfkOOhFIOrfzU/edit#gid=0
> USHIFT-463: Update requests for topolvm to reflect measured usage

- docs/rebase.md
- scripts/devenv-builder/configure-vm.sh
> USHIFT-622: Update rebase doc to reflect latest changes

- docs/default_cni_plugin.md
- packaging/systemd/configure-ovs.sh
- pkg/components/networking.go
- pkg/config/ovn/ovn.go
- pkg/config/ovn/test/ovn.yaml
https://issues.redhat.com/browse/NP-633
> NP-633: Add gateway interface options in ovn cni config

- docs/howto_config.md
Close-Issue: https://issues.redhat.com/browse/USHIFT-618
> USHIFT-618 Document NodePort port range extension limits

- docs/howto_firewall.md
> USHIFT-441: Add service network to firewall docs

- scripts/devenv-builder/create-vm.sh
- scripts/image-builder/create-vm.sh
> Add wait option to virt-install to make sure VMs are restarted

- pkg/config/config.go
- pkg/config/config_test.go
NodeName changes are dangerous to running systems (attached storage, running pods, etc., need to be relocated).
This change persists the NodeName in /var/lib/microshift/nodename and makes sure it's not modified across runs.
If the NodeName was auto-generated from the hostname it will write a Warning and continue with the old NodeName.
If the NodeName is explicitly configured, it will fail with an error.
[Closes [USHIFT-573](https://issues.redhat.com//browse/USHIFT-573)
> USHIFT-573 avoid NodeName changes in running systems

- pkg/node/kubelet.go
Closes https://issues.redhat.com/browse/USHIFT-447
> USHIFT-447: Add os_id label to kubelet node registration

- packaging/rpm/make-rpm.sh
- packaging/rpm/microshift.spec
ART's build system will substitute commit value with actual commit from o/microshift repo, so `microshift version -o yaml` will report it instead of printing empty string.
Also removed no longer used support for building RPM based on `github_tag `.
> USHIFT-666: Add %{commit} and embed it into binary

- README.md
- docs/known_limitations.md
Closes [USHIFT-503](https://issues.redhat.com/browse/USHIFT-503)
> USHIFT-503: Document unidle service known limitation

- pkg/cmd/showConfig.go
Fixes show-config to show user configuration again, instead of internal representation.
Closes [USHIFT-674](https://issues.redhat.com//browse/USHIFT-674)
> USHIFT-674: Fix show-config command

- scripts/auto-rebase/create_pr.py
Add the label to squash rebase pull requests automatically.
/assign @pmtk
> NOISSUE: squash rebase pull requests

- pkg/util/cryptomaterial/certchains/chainsbuilder.go
> USHIFT-606: Remove cert validity time warnings

- README.md
- docs/network/host_networking.md
Related-Issue: https://issues.redhat.com/browse/USHIFT-640
Related-Issue: https://issues.redhat.com/browse/USHIFT-663
> Add host networking doc

- README.md
- docs/howto_offline_containers.md
- docs/rhel4edge_iso.md
Closes [USHIFT-673](https://issues.redhat.com//browse/USHIFT-673)
> USHIFT-673: Minor fixes in offline container docs

- pkg/config/config.go
- pkg/config/config_test.go
Closes [USHIFT-732](https://issues.redhat.com/browse/USHIFT-732)
> USHIFT-732: forbid IP addresses as hostname

- docs/config/microshift-starter.ks
- docs/devenv_rhel8.md
- scripts/devenv-builder/configure-vm.sh
Closes [USHIFT-740](https://issues.redhat.com//browse/USHIFT-740)
> USHIFT-740: Enable gpgcheck when installing RPMs

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Anil Kumar Vishnoi <avishnoi@redhat.com>
> Remove stale URL and fix typo

- scripts/auto-rebase/rebase.sh
Currently only an amd64 release tag is used for branch name. This means that if new amd64 nightly is not produced, but there's a new ARM64 nightly we won't update images for arm until next amd64 nightly.
> USHIFT-758: Include arm release in rebase branch name

- docs/devenv_rhel8.md
*.* update instruction to install go-toolset
*.* remove make clean in RPM Packages section, because it will delete Microshift executable.
*.* Added troubleshooting section
Signed-off-by: Anil Kumar Vishnoi <avishnoi@redhat.com>
> Updated devevn_rhel8 doc with

- scripts/auto-rebase/rebase.sh
Backport of https://github.com/openshift/microshift/pull/1256
> OCPBUGS-5859: Include arm release in rebase branch name

- docs/devenv_rhel8.md
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
Cherry-pick #1285 
Closes OCPBUGS-6081
> OCPBUGS-6081: Use rhocp-4.12 release channel for OCP dependencies

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-node-metrics_v1_service.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- docs/rebase.md
- scripts/auto-rebase/rebase.py
- scripts/auto-rebase/rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
[USHIFT-432](https://issues.redhat.com//browse/USHIFT-432)
> USHIFT-432: CSI image / manifest rebase script

- pkg/components/render_test.go
- pkg/config/lvmd/types.go
Closes #[USHIFT-854](https://issues.redhat.com//browse/USHIFT-854)
> USHIFT-854: Set spareGB LVMD default to zero

- README.md
- ansible/README.md
- docs/default_csi_plugin.md
- docs/devenv_cloud.md
- docs/devenv_setup.md
- docs/devenv_setup_auto.md
- docs/network/default_cni_plugin.md
- docs/rebase.md
- docs/rhel4edge_iso.md
- scripts/devenv-builder/configure-vm.sh
- scripts/devenv-builder/create-vm.sh
The procedure was tested on RHEL 9.1 and CentOS 9 Stream
Closes [USHIFT-819](https://issues.redhat.com//browse/USHIFT-819)
> USHIFT-819: MicroShift devenv to support RHEL 9 and CentOS 9

- README.md
- docs/devenv_setup.md
- docs/greenboot.md
- docs/greenboot_dev.md
- packaging/greenboot/microshift-running-check.sh
- packaging/rpm/microshift.spec
- scripts/image-builder/config/blueprint_v0.0.1.toml
Closes:
* [USHIFT-696](https://issues.redhat.com//browse/USHIFT-696): Greenboot script implementation
* [USHIFT-697](https://issues.redhat.com//browse/USHIFT-697): Include Greenboot script in RPM
* [USHIFT-698](https://issues.redhat.com//browse/USHIFT-698): Document MicroShift Greenboot specifics
> Initial implementation of MicroShift integration with greenboot

- docs/network/default_cni_plugin.md
Related-Issue: https://issues.redhat.com/browse/OCPBUGS-7056
> Add note for mtu change

- scripts/auto-rebase/rebase.sh
Fixes builds in ART environment
> NO-ISSUE: Optional pull-secret for extracting lvms bundle

- packaging/rpm/microshift.spec
> USHIFT-130: Add openshift-clients to rpm for sos use

- etcd/cmd/microshift-etcd/run.go
- pkg/cmd/init.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/etcd.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-route-controller-manager.go
- pkg/node/kubelet.go
> USHIFT-717: Remove IPs from certificates

- docs/devenv_rhel8.md
- docs/devenv_rhel8_auto.md
- scripts/devenv-builder/configure-vm.sh
Closes [USHIFT-912](https://issues.redhat.com//browse/USHIFT-912)
> USHIFT-912: Update 4.12 devenv configuration instructions to use the right branch

- scripts/devenv-builder/configure-vm.sh
> NO-ISSUE: Add routes and kubectl firewall rules to configure-vm.sh

- scripts/review-dashboard/README.md
- scripts/review-dashboard/dinghy.yaml
- scripts/review-dashboard/setup.sh
Add script and docs with demo installation of dinghy for building a
review dashboard based on PRs related to MicroShift across different
repositories.
> NO-ISSUE: add developer review dashboard tools

- packaging/microshift/lvmd.yaml
- packaging/microshift/ovn.yaml
- packaging/rpm/microshift.spec
Added lvmd.yaml.default and ovn.yaml.default configuration files following the format in the existing config.yaml.default file
Closes:
- [USHIFT-822](https://issues.redhat.com//browse/USHIFT-822)
- [USHIFT-923](https://issues.redhat.com//browse/USHIFT-923)
> Add lvmd.yaml and ovn.yaml default configuration files

- docs/devenv_setup.md
- docs/rhel4edge_iso.md
Closes [USHIFT-915](https://issues.redhat.com//browse/USHIFT-915)
> USHIFT-915: Add wait flag when creating VMs to make sure they are restarted

- scripts/auto-rebase/changelog.txt
- scripts/auto-rebase/rebase.py
- scripts/auto-rebase/rebase.sh
- Reformat the changelog as nested lists so it looks a bit nicer in the PR
descriptions for rebases.
- Add full changelog to rebase PR descriptions
> NO-ISSUE: add more changelog details to PR descriptions

- docs/config/nginx-IP-header.yaml
- docs/howto_load_balancer.md
Update the document as we have a built-in loadbalancer controller in Microshift.
> NP-604: Loadbalancer Service document update

- ansible/roles/create-vm/defaults/main.yml
- ansible/roles/create-vm/handlers/main.yml
- ansible/roles/create-vm/tasks/main.yml
- ansible/roles/setup-localhost/defaults/main.yml
- ansible/roles/setup-localhost/tasks/main.yml
- ansible/run-perf.yml
- ansible/setup-node.yml
- ansible/vars/all.yml
- Rework local SSH tasks
- Copy ssh key to microshift remote
- Update playbooks
- Add new var to all, slight reorder
Full create -> execution flow is now contained within one playbook
> USHIFT-940: New ansible role to streamline devenv vm creation

- docs/config/microshift-starter.ks
- docs/greenboot.md
- scripts/image-builder/config/kickstart.ks.template
Closes [USHIFT-976](https://issues.redhat.com//browse/USHIFT-976)
> USHIFT-976: Override journald configuration rather than editing the system files

- docs/devenv_setup.md
- scripts/devenv-builder/create-vm.sh
- scripts/image-builder/create-vm.sh
Some hosts lack `sshpass`, this adds `sshpass` to the dnf install line.
> NO-ISSUE: add sshpass to dnf install on hypervisor

- scripts/jira/cloner.py
- Split between queries and commands.
- Prompts confirmation for actions.
- Informs about manual/automatic actions.
- Automatic fill of target versions in parent issues.
- Detects unassigned issues.
- Skips CVE issues.
> NOISSUE: Improve JIRA cloner

- scripts/jira/cloner.py
> NOISSUE: Add user filtering and sprint handling to jira script

- README.md
- docs/howto_kubeconfig.md
> NOISSUE: Add kubeconfig management docs

- scripts/release-notes/gen-ec-release-notes.py
RC builds are published to a different path on the mirror, so we need
to check 2 RPM list files and handle the differences in the filenames
of the RPMs themselves. This change extracts the "candidate type" from
the filename instead of assuming an engineering candidate.
> NO-ISSUE: update release notes script to handle RC builds

- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-scheduler.go
- pkg/node/kubelet.go
- pkg/util/cert.go
- pkg/util/cryptomaterial/certchains/signers.go
> USHIFT-1010: Restrict created files permissions

- docs/howto_config.md
- docs/storage/configuration.md
- docs/storage/default_csi_plugin.md
Add storage configuration, including how to configure multiple device classes, to the config doc.
> add storage config documentation

- docs/config/nginx-IP-header.yaml
- docs/howto_load_balancer.md
> : NOISSUE: Update the LB service document by using a free host port

- docs/getting_started.md
Change "optionated" to "opinionated" in `getting_started.md`.
> NO-ISSUE: Fix spelling error in getting started docs

- docs/howto_offline_containers.md
/assign @ggiguash @schmaustech
> USHIFT-1079: link to container registry credentials docs

- e2e/Dockerfile.hello-microshift
- packaging/images/openshift-ci/Dockerfile.microshift-test
Closes [USHIFT-1064](https://issues.redhat.com/browse/USHIFT-1064)
> USHIFT-1064: lightweight, unprivileged container image "MicroShift Test"

- Makefile
Some of the verification checks take longer than others, so separate
them to provide a target developers can use locally without waiting
many minutes for tests to run.
/assign @copejon
> USHIFT-1106: separate slow and fast verify checks

- packaging/rpm/microshift.spec
[USHIFT-1122](https://issues.redhat.com//browse/USHIFT-1122)
> Unblocking CI selinux dependencies

- e2e/tests/0030-router-smoke-test.sh
- e2e/tests/0031-loadbalancer-smoke-test.sh
- e2e/tests/assets/hello-microshift.yaml
- e2e/tests/assets/microshift-test.yaml
- packaging/images/openshift-ci/Dockerfile.microshift-test
Closes  [USHIFT-1064](https://issues.redhat.com/browse/USHIFT-1064)
> USHIFT-1064: use microshift-test image for e2e test

- Makefile
- docs/devenv_cloud.md
- docs/devenv_setup.md
- docs/devenv_setup_auto.md
- docs/howto_offline_containers.md
- docs/rhel4edge_iso.md
- hack/osbuild2copr.sh
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
- scripts/image-builder/create-vm.sh
Closes #[USHIFT-1121](https://issues.redhat.com/browse/USHIFT-1121)
> USHIFT-1121: switch uname -i to uname -m

- OWNERS
> NO-ISSUE: Add pliurh to reviewers

- packaging/images/openshift-ci/Dockerfile.test-runtime
> USHIFT-1119: Use ubi9 base image for test-runtime in CI

- docs/rhel4edge_iso.md
- scripts/image-builder/build.sh
> Increase disk size validation

- docs/devenv_cloud.md
- docs/devenv_setup.md
- docs/devenv_setup_auto.md
> USHIFT-1235: Fix docs for RHEL DVD file names to be of the 9.2 version

- packaging/crio.conf.d/microshift-ovn.conf
Revert dc16ad144e9a5d1c5cf040cbc4c474b6ecd66029
> revert: add cpu pinning back

- packaging/images/openshift-ci/Dockerfile.test-runtime
> USHIFT-1082: Update test-runtime image dependencies

- pkg/controllers/kube-apiserver.go
> USHIFT-1202: Use hostnames over IPs in apiserver when connecting to kubelet

- test/run.sh
Addresses https://issues.redhat.com/browse/USHIFT-1282
> Ensure pip is up to date within the Robot Framework venv.

- assets/components/lvms/topolvm-controller-resizer_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/components/lvms/topolvm-controller-resizer_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- docs/storage/default_csi_plugin.md
- e2e/tests/0050-pvc-resize.sh
- pkg/components/storage.go
- scripts/auto-rebase/assets.yaml
Closes [USHIFT-1049](https://issues.redhat.com//browse/USHIFT-1049)
> USHIFT-1049 QE: regression case failure [sig-storage] STORAGE MicroShiftOnly-Author:rdeore-Critical-59660-[MicroShift] Volumes resize on-line

- scripts/image-builder/build.sh
> USHIFT-1296: Fix privileges to download caddy in iso builds

- docs/storage/default_csi_plugin.md
[USHIFT-1316](https://issues.redhat.com//browse/USHIFT-1316)
> [USHIFT-1316] add lvms volume cloning documentation

- test/README.md
> USHIFT-1327: correct instructions for using ssh-agent with RF tests

- packaging/rpm/microshift.spec
Shift Week Project:
Created spec folder to hold our spec files for validating configs.
Installed our openapi spec file to spec folder.
> SHIFTWEEK: feat: add spec dir and move cp openapi spec file

- scripts/auto-rebase/rebase_job_entrypoint.sh
> USHIFT-1359 Change source from where release image tag is obtained from for rebase

- e2e/tests/0031-loadbalancer-smoke-test.sh
- test/suites/load-balancer.robot
> Increase retries and backoff of loadbalancer service smoke test

- pkg/assets/crd.go
> chore: pkg imported more than once

- scripts/auto-rebase/assets.yaml
Closes #[USHIFT-704](https://issues.redhat.com//browse/USHIFT-704)
/assign @pmtk
> USHIFT-704: fix rebase asset.yaml for aggregate-route

- test/README.md
- test/bin/scenario.sh
> USHIFT-1409: extend scenario.sh to make it easy to login to test vms

- test/bin/ci_phase_iso_boot.sh
/hold until https://github.com/openshift/release/pull/40720 merges
/assign @pacevedom @pmtk
> USHIFT-1385: boot CI VMs in parallel

- docs/contributor/storage/configuration.md
- docs/contributor/storage/default_csi_plugin.md
[USHIFT-1398](https://issues.redhat.com//browse/USHIFT-1398)
> [USHIFT-1398] Snapshotting config and usage documentation

- test/bin/ci_phase_test.sh
- test/bin/scenario.sh
> USHIFT-1387: Add scenario test run script

- test/bin/scenario.sh
also make "boot" an alias for "create" in scenario script
> USHIFT-1428: add "rerun" command to scenario script

- test/bin/ci_phase_test.sh
- test/bin/scenario.sh
> USHIFT-1387: Re-enable ssh agent in scenario testing

- packaging/greenboot/microshift-running-check.sh
Closes [USHIFT-1434](https://issues.redhat.com//browse/USHIFT-1434)
> USHIFT-1434: Add csi-snapshot pods to greenboot

- packaging/greenboot/microshift-running-check.sh
I simulated the pod "restart" by deleting pods in the `openshift-storage` namespace and the error reason was correctly p
printed.
```
Running Required Health Check Scripts...
STARTED
GRUB boot variables:
boot_success=0
boot_indeterminate=0
Greenboot variables:
...
...
Checking pod restart count in the 'openshift-ovn-kubernetes' namespace
Checking pod restart count in the 'openshift-service-ca' namespace
Checking pod restart count in the 'openshift-ingress' namespace
Checking pod restart count in the 'openshift-dns' namespace
Checking pod restart count in the 'openshift-storage' namespace
Pod restart count check failed for the 'openshift-storage' namespace
FAILURE
```
Closes: [USHIFT-1319](https://issues.redhat.com//browse/USHIFT-1319)
> USHIFT-1319: Add a message to the greenboot pod count check when it fails

- test/README.md
- test/bin/ci_phase_iso_boot.sh
- test/bin/common.sh
- test/bin/manage_vm_storage_pool.sh
- test/bin/scenario.sh
> USHIFT-1387: Use storage pool for scenario VM creation

- test/bin/scenario.sh
> USHIFT-1396: Add sos reports to scenario testing

- scripts/devenv-builder/configure-vm.sh
A workaround for the recurring dnf cache problem seen in AWS. Retries on dnf commands with cleaning the cache.
P.S. Also fix grep error message when `/etc/crio/crio.conf` does not exist.
See this log for a typical dnf cache error we're trying to solve.
```bash
+ sudo dnf install -y gcc git golang cockpit make jq selinux-policy-devel rpm-build jq bash-completion
Updating Subscription Management repositories.
Last metadata expiration check: 0:01:31 ago on Thu 13 Jul 2023 10:15:42 PM UTC.
Dependencies resolved.
===============================================================================================
Package                        Arch    Version               Repository                   Size
=============================================================================================== …
```
> NO-ISSUE: Add retries for dnf commands in configure-vm.sh script

- test/assets/storage-version-migration/cr.yaml
- test/assets/storage-version-migration/crd.beta.yaml
- test/assets/storage-version-migration/crd.stable.yaml
- test/suites/storage-version-migration.robot
Add e2e synthetic test for Storage Migration validation.
/assign @pmtk
> USHIFT-1382: feat: add e2e test for storage migration

- docs/config/microshift-starter.ks
- scripts/image-builder/config/kickstart.ks.template
- test/kickstart-templates/kickstart.ks.template
Closes [USHIFT-1425](https://issues.redhat.com//browse/USHIFT-1425)
> USHIFT-1425: Fix ostree url update and user configuration in kickstart files

- scripts/jira/manage_ticket.sh
> USHIFT-1451: install all dependencies for jira tools

- test/README.md
- test/image-blueprints/group1/rhel92.toml
- test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
- test/image-blueprints/group2/rhel92-source-fake-next-minor.toml
- test/image-blueprints/group2/rhel92-source.toml
Add the blueprint file to the image list table.
Add missing entries to the image list table.
Add descriptions to the blueprint files.
/assign @copejon
> USHIFT-1490: update test image reference table

- test/resources/libostree.py
- test/scenarios/rhel-9.2-microshift-source-backup-prune.sh
- test/suites-ostree/backup-prune.robot
Add e2e test for backup pruning
> USHIFT-1445: feat: add e2e test for backup pruning and unknown directories

- docs/user/debugging_tips.md
- docs/user/howto_config.md
- docs/user/howto_pod_security.md
Add a simple example of defining a custom SCC that allows more
privileges and configuring a namespace and pod to use it.
> USHIFT-1511: add scc example

- packaging/rpm/microshift.spec
- scripts/image-builder/build.sh
https://issues.redhat.com/browse/OCPBUGS-15948
Manual cherry-pick of #2035
> USHIFT-1426: unpin openvswitch 4.13

- test/suites/storage-version-migration.robot
There may be a delay between pushing the CRD to the API server and having
it available for use to create a CR. Retry creating the CR a few times.
> USHIFT-1518: deal with potential race condition in storage migration test

- docs/contributor/rebase.md
- scripts/auto-rebase/assets.yaml
- scripts/auto-rebase/handle_assets.py
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/lvms_assets.yaml
- scripts/auto-rebase/presubmit.py
- scripts/auto-rebase/rebase.py
- scripts/auto-rebase/rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
- scripts/fetch_tools.sh
Remove the LVMS rebase steps for the overall OCP rebase process and
provide separate, parallel, commands for updating LVMS.
/assign @copejon @pmtk @ggiguash
> USHIFT-1521: separate rebase of OCP and LVMS

- test/agent/microshift-test-agent.sh
- test/resources/ostree-data.resource
- test/resources/ostree.resource
- test/scenarios/rhel-9.2-microshift-source-failed-staged.sh
- test/suites-ostree/backup-restore.robot
- test/suites-ostree/staged-failed-upgrade.robot
add test that validates when an unhealthy first boot happens during upgrade, a restore is performed.
> USHIFT-1392: feat: add e2e test for staged failed update scenario

- test/bin/scenario.sh
> USHIFT-1531: Loop and timeout for getting VM IP in scenarios

- scripts/auto-rebase/rebase.py
> USHIFT-1552: update the valid-bug label used in rebase PRs

- scripts/auto-rebase/rebase.py
Backport of #2183
/assign @ggiguash @pmtk
> USHIFT-1566: fix valid-bug label in rebase.py on 4.13

- scripts/image-builder/configure.sh
- test/README.md
- test/bin/cleanup.sh
- test/bin/start_webserver.sh
Closes [USHIFT-1577](https://issues.redhat.com//browse/USHIFT-1577)
> USHIFT-1577: Replace caddy by nginx web server

- test/bin/common.sh
- test/bin/scenario.sh
A follow-up for [the comment](https://github.com/openshift/microshift/pull/2219#discussion_r1296375999) in #2219
Closes [USHIFT-1591](https://issues.redhat.com//browse/USHIFT-1591)
> USHIFT-1591: Delete the VM-specific storage pool in scenario cleanup

- docs/contributor/design.md
As the implementation has evolved over the last year, we have made
some adjustments to allow for new and evolving product
requirements. This change updates the design principles to match our
current plans and implementation.
/assign @pacevedom @jerpeter1
> USHIFT-1610: design principle updates

- test/scenarios-periodics/el92-src@cncf-conformance.sh
> USHIFT-1607: Fix bug when checking for cncf tar file

- test/scenario_settings.sh.example
> USHIFT-1623: add VNC_CONSOLE to example scenario settings file

- scripts/auto-rebase/rebase_history.sh
This script is useful for building the technical enablement summary
and release notes.
/assign @pmtk @pacevedom
> USHIFT-1620: add a script to produce the full rebase history

- docs/contributor/updateability.md
> NO-ISSUE: Correct test file references in the docs

- docs/user/howto_pod_security.md
> USHIFT-1649: add more references about pod security admission enforcement

- test/scenarios-periodics/el92-src@cncf-conformance.sh
> USHIFT-1655: Increase cncf conformance timeout

- OWNERS
> NO-ISSUE: Update owners

- pkg/cmd/admin.go
Before:
```
$ microshift backup
Error: accepts 1 arg(s), received 0
$ microshift backup ""
Error: command requires root privileges
$ microshift backup 1 2
Error: accepts 1 arg(s), received 2
```
After:
```
$ microshift backup
Error: command requires an argument
Usage:
microshift backup PATH [flags]
Flags:
-h, --help   help for backup
$ microshift backup ""
Error: argument cannot be empty
Usage:
microshift backup PATH [flags]
Flags:
-h, --help   help for backup
$ microshift backup 1 2
Error: command accepts only 1 argument
Usage:
microshift backup PATH [flags]
Flags:
-h, --help   help for backup
```
> USHIFT-1658: `microshift {backup,restore}`: print usage if given invalid arg

- packaging/rpm/microshift.spec
- scripts/microshift-sos-report.sh
- test/bin/scenario.sh
> USHIFT-1664: Introduce microshift-sos-report helper

- scripts/image-builder/cleanup.sh
Closes [USHIFT-1688](https://issues.redhat.com//browse/USHIFT-1688)
> USHIFT-1688: Fix image-builder/cleanup.sh to restart osbuilder service on exit

- test/bin/build_images.sh
Add -t argument to test/bin/build_images.sh so the caller can rebuild
a single image by passing the template file as input.
> USHIFT-1695: support building a single image in test harness

- test/assets/hello-microshift-ingress.yaml
- test/resources/microshift-network.resource
- test/suites/standard/networking-smoke.robot
> OCPBUGS-19433: Add ingress smoke test

- scripts/microshift-sos-report.sh
> OCPBUGS-19567: Add logs plugin to sos helper

- scripts/microshift-cleanup-data.sh
- test/resources/microshift-process.resource
- test/resources/ostree-health.resource
- test/suites/greenboot/greenboot.robot
- test/suites/standard/cleanup-data.robot
> [release-4.14] OCPBUGS-19525: Fix microshift-cleanup-data script and test its functionality

- docs/user/debugging_tips.md
See https://github.com/sosreport/sos/pull/3357 for sos code changes.
> USHIFT-1631: do not recommend sos obfuscation by default

- packaging/rpm/microshift.spec
- scripts/microshift-sos-report.sh
- test/bin/scenario.sh
Manual cherry-pick of https://github.com/openshift/microshift/pull/2311
> OCPBUGS-19772: Add microshift-sos-report wrapper

- test/README.md
- test/bin/build_images.sh
- test/bin/common.sh
- test/bin/get_crel_version_repo.sh
- test/bin/scenario.sh
- test/image-blueprints/group2/rhel92-crel.toml
- test/package-sources/microshift-crel.toml
- test/scenarios-periodics/el92-crel@upgrade-fails.sh
- test/scenarios/el92-crel@upgrade-ok.sh
Closes: [USHIFT-1097](https://issues.redhat.com//browse/USHIFT-1097) [USHIFT-1107](https://issues.redhat.com//browse/USHIFT-1107) OCPBUGS-19457
> OCPBUGS-19457: Test update from current release

- ansible/roles/add-kubelet-logging/defaults/main.yml
- ansible/roles/add-kubelet-logging/tasks/main.yml
- ansible/roles/common/tasks/boot.yml
- ansible/roles/create-service-account/tasks/main.yml
- ansible/roles/create-vm/defaults/main.yml
- ansible/roles/install-logging/defaults/main.yml
- ansible/roles/install-logging/tasks/main.yml
- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/install-microshift/tasks/main.yml
- ansible/roles/manage-repos/defaults/main.yml
- ansible/roles/manage-repos/tasks/main.yml
- ansible/roles/microshift-start/files/ready.sh
- ansible/roles/microshift-start/tasks/main.yml
- ansible/setup-node.yml
- ansible/vars/all.yml
This PR has a number of fixes/changes that were a product of the version to version comparison.
- Changes to Service Account for logging
- Modify Grafana installation/configuration for logging
- Add beta repo support to repo management tasks (should be generic for future betas)
- Add improved boot time measurement via shell script in common role
- Update create-vm vars
- Updated build/vs install MicroShift & etcd conditions
> USHIFT-1685: Ansible Improvements Catch-up

- test/bin/build_images.sh
> NO-ISSUE: Retrieve osbuild worker logs from iso build

- test/assets/hello-microshift.yaml
[USHIFT-1726](https://issues.redhat.com//browse/USHIFT-1726):
Needed because we are limited on the number of pulls
> USHIFT-1726: Pull busybox from quay.io to avoid rate limit

- test/resources/microshift-network.resource
- test/resources/oc.resource
- test/suites/standard/hostname.robot
- test/suites/storage/pvc-resize.robot
- test/suites/storage/reboot.robot
- test/suites/storage/snapshot.robot
[USHIFT-1690](https://issues.redhat.com//browse/USHIFT-1690)
> USHIFT-1690: multi-nic keyword bug fix

- packaging/greenboot/functions.sh
- packaging/greenboot/microshift-running-check.sh
> OCPBUGS-20037: Fix journal entries to belong to greenboot unit

- test/assets/hello-microshift.yaml
This is a back port of [USHIFT-1726](https://issues.redhat.com//browse/USHIFT-1726)
OCPBUGS-19939
> [release-4.14] OCPBUGS-19939: Commit busybox fix for pulling from Quay.io

- docs/user/howto_test_offline.md
> NO-ISSUE: Correct minor issues found while reviewing howto_test_offline

- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/manage-repos/defaults/main.yml
- ansible/roles/manage-repos/tasks/main.yml
- ansible/roles/manage-repos/templates/ocpbeta.repo.j2
- ansible/roles/microshift-start/tasks/main.yml
- ansible/vars/all.yml
Closes #[USHIFT-1746](https://issues.redhat.com//browse/USHIFT-1746)
> USHIFT-1746: Ansible support prerelease repos

- scripts/devenv-builder/configure-vm.sh
Tested in AWS Cloud using RHEL-9.3.0_HVM_BETA-20230912-x86_64-0-Hourly2-GP2 AMI.
> USHIFT-1771: RHEL 9.3 Beta Development environment setup

- packaging/rpm/microshift.spec
- scripts/devenv-builder/configure-vm.sh
* update golang check in rpm spec file to look at each part of the
version string separately
* update rpm spec file to require go 1.20.10
* update golang in dev tool setup to 1.20.10
> USHIFT-1778: update golang to 1.20.10

- ansible/roles/fetch-kubeconfig/defaults/main.yml
- ansible/roles/fetch-kubeconfig/tasks/main.yml
- ansible/roles/run-workloads/defaults/main.yml
- ansible/roles/run-workloads/tasks/kube-burner.yml
- ansible/roles/run-workloads/tasks/main.yml
- ansible/roles/setup-localhost/defaults/main.yml
- ansible/roles/setup-localhost/tasks/main.yml
- ansible/setup-node.yml
Closes #[USHIFT-1751](https://issues.redhat.com//browse/USHIFT-1751)
> USHIFT-1751: Add role to run kube-burner workloads

- origin/suite.txt
> USHIFT-1774: Add router stress tests

- origin/README.md
> USHIFT-1759: Edit origin readme

- origin/pkg/defaultmonitortests/types.go
This commit must NOT be ported to openshift/origin!
> USHIFT-1760: Skip invariants with an env var

- scripts/microshift-sos-report.sh
> [release-4.14] OCPBUGS-20498: Add logs plugin to sos helper

- packaging/rpm/make-rpm.sh
> USHIFT-1777: Add rpm checks after building

- test/bin/scenario.sh
> USHIFT-1804: Report OK status for IP and SSH in offline scenarios

- test/bin/scenario.sh
Create some functions to hide the implementation of vm settings so
scenario scripts can use them.
> USHIFT-1823: add VM property abstraction to scenario.sh

- test/bin/scenario.sh
> USHIFT-1821: allow scenario steps to report being skipped

- scripts/microshift-sos-report.sh
- test/bin/scenario.sh
> USHIFT-1820: Skip sos microshift profile if its disabled

- test/bin/scenario.sh
This allows scenario setup steps to do more with the VM before starting the
test.
> USHIFT-1824: add ssh wrapper functions to scenario.sh

- packaging/network-manager-conf/microshift-nm.conf
- packaging/rpm/microshift.spec
> OCPBUGS-23220: Remove keyfile nm plugin force when installing

- test/bin/manage_build_cache.sh
See the [USHIFT-1887](https://issues.redhat.com//browse/USHIFT-1887) JIRA issue description for time comparison with and without archiving the repo contents.
The expected speed up is by 2-2.5m vs 3-3.5m before
> USHIFT-1887: Archive ostree commit repo contents before uploading to S3

- docs/user/debugging_tips.md
> NP-849: Add instruction for configuring OVN-K log level

- Makefile
- packaging/images/Containerfile.rpm-builder
this is the registry with ocp builder  multiplatform support
> USHIFT-1940: update to multiplatform builder image

- packaging/rpm/microshift.spec
Depends on https://github.com/openshift/microshift/pull/2608
> OPRUN-3064: RPM package for Openshift-lifecycle-manager microshfit manifests 

- test/bin/build_images.sh
- test/bin/wait_images.py
Adds a retry when a build job fails. It can be tested with `composer-cli compose cancel` is it marks the job as FAILED.
> USHIFT-1901: Retry once failed composer build

- docs/contributor/design.md
> NO-ISSUE: Update design.md

- scripts/release-notes/gen_ec_release_notes.py
> USHIFT-1963: ignore 4.14 for candidate release notes

- test/bin/scenario.sh
The deletion of pods using `kubectl` command gets stuck and returns with timeout.
Trying a stronger technique by using `crictl` commands.
> USHIFT-1952: Retry after microshift-cleanup-data when greenboot reports a failure in scenario.sh

- test/suites/fips/validate-fips.robot
due to a race condition  Microshift service  must be stopped before running the test.
> USHIFT-1961: make sure FIPS compliance test runs on a stopped system

- test/resources/common.resource
- test/resources/microshift-network.resource
- test/suites/standard/networking-smoke.robot
> remove quotes from argument passed to keyword

- assets/components/openshift-router/deployment.yaml
- scripts/auto-rebase/rebase.sh
- test/suites/standard/networking-smoke.robot
> USHIFT-1861: Fix network smoke tests flakes

- test/suites/fips/validate-fips.robot
> USHIFT-1961: FIPS test log information about microshift RPM

- test/bin/scenario.sh
> USHIFT-1956: Reinstate greenboot fail fast checks

- scripts/devenv-builder/configure-vm.sh
Goal is to speed up provisioning of MicroShift using cluster-bot
> USHIFT-2080: configure-vm.sh: skip dnf update on demand

- scripts/image-builder/configure.sh
The version on RHEL 9.2 works OK for building only 9.2 images, so
allow it to be used.
/assign @ggiguash @pmtk
> USHIFT-2053: only install osbuild from COPR on RHEL 9.3

- test/kickstart-templates/kickstart.ks.template
> USHIFT-2067: Enable insecure in kickstart template

- test/README.md
- test/bin/ci_phase_iso_boot.sh
- test/bin/mirror_registry.sh
- test/bin/scenario.sh
- test/kickstart-templates/kickstart.ks.template
Manual cherry pick of PRs:
- https://github.com/openshift/microshift/pull/2777
- https://github.com/openshift/microshift/pull/2766
- https://github.com/openshift/microshift/pull/2757
- https://github.com/openshift/microshift/pull/2683
> [release-4.15]  USHIFT-2103: Add registry mirror to metal jobs

- test/bin/build_images.sh
- test/bin/ci_phase_iso_build.sh
Also adds a -f flag to force rebuilding locally, and introduces force
logic for source image rebuilds and when building a specific image from
its template.
/assign @ggiguash @pmtk
> USHIFT-2051: always build images not available in the cache

- scripts/dnf_retry.sh
> USHIFT-2123: Make sure rc is zero when exiting dnf_retry.sh loop

- scripts/dnf_retry.sh
Cherrypick of https://github.com/openshift/microshift/pull/2820
> [release-4.15] USHIFT-2127: Add tracing to dnf_retry.sh and fix rc logic

- scripts/get-latest-rhocp-repo.sh
Update get-latest-rhocp-repo.sh to try to get information about one of
our dependencies from a repository before selecting that repository
for use. This ensures that not only does the repo exist, but it
includes at least one of the packages we need.
/assign @ggiguash @jogeo
/cc @pmtk
> USHIFT-2145: look for dependency in rpm repo before trying to use it

- scripts/image-builder/configure.sh
> [release-4.14] USHIFT-2159: Upgrade osbuild copr package versions after copr cleanup

- test/bin/mirror_registry.sh
> USHIFT-2160: Retry logic for registry image pull

- test/scenarios-periodics/el92-src@cncf-conformance.sh
> USHIFT-2139: bump sonobuoy version to 0.57.1

- test/suites/standard1/log-scan.robot
- test/suites/standard1/networking-smoke.robot
> USHIFT-2105: Temporarily disable flaky tests

- .snyk
Based on https://github.com/openshift/oc/blob/master/.snyk
> USHIFT-2167: Ignore origin/ dir for security scans

- test/bin/build_images.sh
- test/bin/common.sh
- test/bin/mirror_registry.sh
- test/kickstart-templates/kickstart-liveimg.ks.template
> USHIFT-2131: Add registry mirror configuration to kickstart-liveimg

- pkg/config/config.go
- pkg/config/config_test.go
> OCPBUGS-23336: Check AdvertiseAddress configured in NICs

- test/bin/build_images.sh
> USHIFT-2131: Fix dnf download for rhocp repos

- test/bin/build_images.sh
- test/bin/common.sh
- test/bin/mirror_registry.sh
- test/kickstart-templates/kickstart-liveimg.ks.template
Cherry picked from https://github.com/openshift/microshift/pull/2897 and https://github.com/openshift/microshift/pull/2859
> [release-4.15] USHIFT-2187: Fix image mirroring for previous version

- test/resources/selinux.py
- test/resources/selinux.resource
- test/scenarios-periodics/el92-src@rpm-standard1.sh
- test/scenarios-periodics/el92-src@rpm-standard2.sh
> USHIFT-1848: add periodic test scenario for the standard tests on rpm-based system

- test/bin/build_images.sh
Clean up help text and add new option to skip logs.
> USHIFT-2242: add option to build_images.sh to skip log collection step

- origin/run.sh
> USHIFT-2263: Add env var driven origin test list

- pkg/controllers/kube-apiserver.go
- pkg/util/net.go
Reverts openshift/microshift#2966
> Revert "USHIFT-2253: Improve microshift start time by reducing readiness checks intervals"

- scripts/release-notes/gen_ec_release_notes.py
The earlier version of the release note script let the user run the
commands to create the tag. This update applies the tags automatically
to make the script easier to use.
> USHIFT-2266: have the release note script handle the tag commands

- scripts/docs-preview/Containerfile
- scripts/docs-preview/README.md
- scripts/docs-preview/build-in-container.sh
- scripts/docs-preview/build.sh
- scripts/docs-preview/common.sh
- scripts/docs-preview/serve.sh
- scripts/fetch_tools.sh
> USHIFT-2367: documentation preview build scripts

- test/bin/stress_testing.sh
- test/suites/osconfig/clusterid.robot
Revert commits added by error on this PR: https://github.com/openshift/microshift/pull/2999
> NO-ISSUE: Revert commits

- docs/user/getting_started.md
> USHIFT-2377: update getting started docs to point to 4.14

- scripts/image-builder/configure.sh
This reverts commit 47fba3b496d2546a5102f668206575ddf5bc46f3.
> USHIFT-2345: Revert "Work around broken osbuild dependency on RHEL 9.3"

- scripts/image-builder/configure.sh
Reverts openshift/microshift#2990
> USHIFT-2346: Revert "[release-4.15] USHIFT-2346: Work around broken osbuild dependency on RHEL 9.3"

- scripts/devenv-builder/configure-vm.sh
- scripts/pull_retry.sh
> USHIFT-2374: Add option to pull images on configure-vm

- scripts/devenv-builder/configure-vm.sh
> USHIFT-2374: Move pull images after starting crio

- scripts/devenv-builder/configure-vm.sh
- scripts/pull_retry.sh
> USHIFT-2386: Add option to pull images in configure-vm.sh

- test/bin/stress_testing.sh
- test/run.sh
Closes Jira: https://issues.redhat.com/browse/USHIFT-2260
> USHIFT-2260: Add support to run Stress Testing conditions from Jenkins

- test/image-blueprints/layer4-ext/group1/rhel93_microshift-ext.toml
> USHIFT-2473: add missing quote to microshift-ext template

- test/bin/scenario.sh
> [release-4.15] USHIFT-2389: Use timeout command for interrupting failed VM installations

- test/bin/stress_testing.sh
> USHIFT-2460: Fix Stress Testing script

- etcd/go.mod
- scripts/auto-rebase/rebase.sh
> USHIFT-2546: Remove go mod toolchain on rebase

- .gitignore
- test/README.md
- test/bin/common.sh
- test/dev_overrides.sh.example
Add the ability to override settings used by the CI scripts for local
developer workflows.
/assign @jogeo
> USHIFT-2543: add overrides for CI scripts

- test/bin/ci_phase_iso_boot.sh
- test/bin/ci_phase_test.sh
- test/bin/common.sh
> USHIFT-2542: Skip cncf conformance in presubmits

- test/bin/scenario.sh
> [release-4.15] USHIFT-2559: Fix exit sequence error code in action_create and action_run of scenario.sh

- scripts/devenv-builder/configure-vm.sh
Adds a --optional-rpms flag to install all RPMs.
> USHIFT-2550: Change configure-vm.sh to not install optional RPMs by default

- test/bin/ci_phase_iso_boot.sh
> USHIFT-2542: Fix scenario removal

- test/scenarios-periodics/el92-src@cncf-conformance.sh
> USHIFT-2506: CNCF remove parallel execution

- test/bin/ci_phase_iso_boot.sh
- test/bin/ci_phase_test.sh
- test/bin/common.sh
Manual cherry-pick of #3115 and #3144
> [release-4.15] USHIFT-2610: Skip cncf conformance in presubmits

- test/scenarios-periodics/el92-src@cncf-conformance.sh
> [release-4.14] USHIFT-2609: CNCF-4.14 remove parallel execution

- docs/contributor/rebase.md
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
> [release-4.15] USHIFT-2617: Use registry.redhat.io for lvms in rebase

- docs/contributor/rebase.md
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
> [release-4.14] USHIFT-2791: Use registry.redhat.io for lvms in rebase

- assets/components/openshift-router/service-cloud.yaml
- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/ingress.go
- scripts/auto-rebase/rebase.sh
- test/resources/microshift-network.resource
- test/suites/standard1/router.robot
> USHIFT-2087: Add configurable router ports

- scripts/release-notes/gen_ec_release_notes.py
> USHIFT-2917: do not sign tags used for release notes

- scripts/release-notes/gen_ec_release_notes.py
> USHIFT-2966: ensure the output of git push is in the traceback if there is an error

- test/resources/microshift-process.resource
- test/suites/standard2/validate-custom-certificates.robot
> USHIFT-2967: use oc command with custom-ca

- test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
- test/scenarios-bootc/cos9-src@backup-and-restore-on-reboot.sh
- test/scenarios-bootc/cos9-src@backups.sh
- test/scenarios-bootc/cos9-src@greenboot.sh
- test/scenarios-bootc/cos9-src@log-scan.sh
- test/scenarios-bootc/cos9-src@multi-nic.sh
- test/scenarios-bootc/cos9-src@optional.sh
- test/scenarios-bootc/cos9-src@osconfig.sh
- test/scenarios-bootc/cos9-src@standard-suite2.sh
- test/scenarios-bootc/cos9-src@storage.sh
- test/scenarios-bootc/el94-src@backup-and-restore-on-reboot.sh
- test/scenarios-bootc/el94-src@backups.sh
- test/scenarios-bootc/el94-src@greenboot.sh
- test/scenarios-bootc/el94-src@log-scan.sh
- test/scenarios-bootc/el94-src@multi-nic.sh
- test/scenarios-bootc/el94-src@optional.sh
- test/scenarios-bootc/el94-src@osconfig.sh
- test/scenarios-bootc/el94-src@standard-suite2.sh
- test/scenarios-bootc/el94-src@storage.sh
> USHIFT-2910: Move firewall configuration to container files for bootc images

- test/bin/ci_phase_iso_build.sh
Verified that the cache job runs and uploads `centos9-bootc.iso` and `rhel94-bootc.iso` files to the S3 bucket.
> USHIFT-2984: Add bootc image caching to ISO build process

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
> USHIFT-3154: Add terminationMessagePolicy to topolvm pods

- assets/optional/multus/06-daemonset.yaml
- assets/optional/multus/07-daemonset-dhcp.yaml
- assets/optional/multus/kustomization.aarch64.yaml
- assets/optional/multus/kustomization.x86_64.yaml
- scripts/auto-rebase/rebase.sh
> USHIFT-2912: Use MicroShift-specific Multus images

- test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
- test/scenarios/el94-src@standard-suite2.sh
Includes optional RPMs for smoke, sanity check if they run successfully.
> USHIFT-3241: Run standard-suite-2 with optional RPMs

- test/scenarios-periodics/el92-src@cncf-conformance.sh
> [release-4.15] USHIFT-3267: Increase cncf result collection timeout to 10m

- pkg/loadbalancerservice/controller.go
Updates to the network in the host trigger a possible update. This also triggers a log about an update that may be unnecessary (both the log and the update).
By comparing the current status and the new one we can avoid an API call and also log properly.
> USHIFT-3177: Avoid updating default router ips if status is the same

- test/resources/SkipTests.py
- test/run.sh
Manual cherry-pick from https://github.com/openshift/microshift/pull/3343
> [release-4.14] USHIFT-2463: Add PreRunModifier flag to skip RF

- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- pkg/config/config.go
- pkg/loadbalancerservice/router.go
> USHIFT-3002: Add router listenAddress ipv6 handling

- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- pkg/config/config.go
> OCPBUGS-35468: Filter out empty entries in router listenAddress

- etcd/vendor/github.com/openshift/microshift/pkg/config/multinode.go
- etcd/vendor/github.com/openshift/microshift/pkg/util/cert.go
- etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
- pkg/config/multinode.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-controller-manager_test.go
- pkg/controllers/openshift-route-controller-manager.go
- pkg/util/cert.go
- pkg/util/net.go
> USHIFT-3482: IPv6 handling adjustments in configuration

- assets/components/openshift-router/deployment.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- scripts/auto-rebase/rebase.sh
> USHIFT-3000: Configure router to support ipv6 single/dual stack

- packaging/NetworkManager.conf.d/10-microshift-ignore-devices.conf
- packaging/rpm/microshift.spec
> USHIFT-3736: Force NM configuration to allow ipv6

- origin/skip.txt
> USHIFT-3752: Skip node reboot test in conformance

- pkg/config/config.go
> USHIFT-3761: Default to ipv6 config values when node ip is ipv6

- scripts/devenv-builder/manage-vm.sh
- test/assets/ipv6-network.xml
- test/bin/common.sh
- test/bin/manage_hypervisor_config.sh
- test/bin/scenario.sh
- test/bin/start_webserver.sh
- test/kickstart-templates/includes/post-network.cfg
- test/suites/greenboot/greenboot.robot
> USHIFT-3476: Test harness ipv6 adaptations

- test/resources/libipv6.py
- test/resources/microshift-network.resource
> USHIFT-3483: Add ipv6 helpers to test framework

- origin/skip.txt
> USHIFT-3773: Skip 2 node sig-architecture conformance test

- docs/contributor/rebase.md
Corrects and adds onto the rebase guide for Microshift to include more details on LVMS rebases, which are custom and not run in the same way as a normal rebase
> USHIFT-2193: docs: corrects and adjusts rebase docs for LVMS

- origin/skip.txt
> USHIFT-3773: Skip untainted nodes conformance test

- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/node.go
- etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
- packaging/microshift/config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/node.go
- pkg/node/kubelet.go
- pkg/sysconfwatch/sysconfwatch_linux.go
- pkg/util/net.go
- test/suites/ipv6/dualstack.robot
> USHIFT-3783: Additional parameter for node ipv6 address in dual stack

- scripts/auto-rebase/rebase-lvms.sh
> NO-JIRA: fix: update script to git add rebase entrypoint script

- test/bin/scenario.sh
Manual backport of https://github.com/openshift/microshift/pull/3743
> [release-4.16] USHIFT-3896: Add explicit command line mode to virtual machine creation

- test/run.sh
> USHIFT-2987: Add support for low-latency feature

- test/run.sh
> USHIFT-4070: Add to support to target multiple RF test suites

- assets/optional/multus/07-daemonset-dhcp.yaml
> USHIFT-4061: change imagePullPolicy from Always to IfNotPresent

- origin/skip.txt
> USHIFT-4081: Skip new sig-network-edge idling tests

- assets/release/release-x86_64.json
- origin/skip.txt
> USHIFT-4121 USHIFT-4123: Skip sig-ci tests, revert ovnk image

- pkg/mdns/controller.go
> OCPBUGS-41510: Avoid link local ipv6 addresses in mdns

- test/scenarios-bootc/presubmits/el94-src@dual-stack.sh
> USHIFT-4128: Add ipv6 dual stack scenario to bootc iso tests

- assets/components/lvms/lvm.topolvm.io_lvmclusters.yaml
- assets/components/lvms/lvm.topolvm.io_lvmvolumegroups.yaml
- assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
- assets/components/lvms/topolvm-configmap_lvms-version.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
Rebase to latest 4.17 build of LVMS
> Rebase lvms quay.io lvms dev lvms4 lvms operator bundle v4.17.0 41

- test/kickstart-templates/includes/onerror-logs.cfg
> USHIFT-4520: Exit with non-zero status from onerror kickstart handler

- test/bin/mirror_registry.sh
Convenience option in the development environment to speed up the flow.
> NO-ISSUE: Add an option to reuse mirror registry

- test/README.md
During testing, found out that if `USHIFT_USER` have sudo access with password then test failure happen with following error
```
$ ../test/run.sh suites/standard1/networking-smoke.robot
[...]
+ /work/microshift/test/../_output/robotenv/bin/robot --randomize all --prerunmodifier /work/microshift/test/resources/SkipTests.py: --loglevel TRACE -V /work/microshift/test/variables.yaml -x junit.xml --outputdir /work/microshift/test/../_output/e2e-20240930-151647 suites/standard1/networking-smoke.robot
No tests to be skipped
==============================================================================
Networking-Smoke :: Networking smoke tests
==============================================================================
Router Smoke Test :: Run a router smoke test                          | …
```
> NO-ISSUE: USHIFT_USER should have sudo access without password

- assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
- assets/components/lvms/topolvm-configmap_lvms-version.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
> Rebase lvms registry.redhat.io lvms4 lvms operator bundle v4.17.0 43

- origin/skip.txt
> NO-ISSUE: Skip HAProxy multinode schedule conformance test

- assets/components/lvms/lvm.topolvm.io_lvmclusters.yaml
- assets/components/lvms/lvm.topolvm.io_lvmvolumegroups.yaml
- assets/components/lvms/lvms-operator_apps_v1_deployment.yaml
- assets/components/lvms/topolvm-configmap_lvms-version.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
> NO-ISSUE: Rebase lvms registry.redhat.io lvms4 lvms operator bundle v4.17.0 43

- pkg/config/config.go
> USHIFT-4541: improve slave NIC detection for router exposed IPs

- test/bin/manage_build_cache.sh
Since we're using `--quiet` is almost all AWS CLI commands, exit with errors was not obvious when running the script in interactive mode.
> NO-ISSUE: Add error message for AWS CLI commands instead of silent exit

- test/bin/common_versions.sh
- test/package-sources/rhocp-y.toml
- test/package-sources/rhocp-y1.toml
> [release-4.17] USHIFT-4694: update common_versions.sh

- assets/optional/multus/06-daemonset.yaml
- assets/optional/multus/07-daemonset-dhcp.yaml
> USHIFT-4702: Add terminationMessagePolicy to multus containers

- scripts/multinode/configure-pri.sh
- scripts/multinode/configure-sec.sh
- test/scenarios/periodics/el94-src@cncf-conformance.sh
> USHIFT-4712: Fix tests and node configuration for CNCF conformance

- test/bin/common_versions.sh
- test/package-sources/rhocp-y.toml
- test/package-sources/rhocp-y1.toml
- test/scenarios/presubmits/el94-src@rpm-install.sh
> USHIFT-4129: Update common_versions.sh with 4.17 repos

- test/scenarios/periodics/el94-src@cncf-conformance.sh
> USHIFT-4712: CNCF scenario: check failed tests

- scripts/multinode/configure-pri.sh
- scripts/multinode/configure-sec.sh
- test/scenarios/periodics/el94-src@cncf-conformance.sh
Manual cherry-picking from main branches PRs:
- https://github.com/openshift/microshift/pull/4102
- https://github.com/openshift/microshift/pull/4092
> [release-4.17] USHIFT-4714: Fix CNCF conformance periodics issues

- assets/optional/gateway-api/release-gateway-api-aarch64.json
- assets/optional/gateway-api/release-gateway-api-x86_64.json
- packaging/rpm/microshift.spec
- scripts/auto-rebase/ossm_assets.yaml
- scripts/auto-rebase/rebase_gateway_api.sh
> USHIFT-4715: Add gateway-api-release-info RPM

- test/suites/standard2/validate-custom-certificates.robot
> [release-4.17] USHIFT-4563: Save and restore default config in custom certs e2e tests

- assets/optional/gateway-api/03-servicemesh-operator3_apps_v1_deployment.yaml
- scripts/auto-rebase/rebase_gateway_api.sh
> USHIFT-4744: Remove limits from servicemesh operator deployment

- test/bin/scenario.sh
- test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
- test/scenarios-bootc/periodics/el94-src@isolated-net.sh
- test/scenarios-bootc/presubmits/cos9-src@multi-nic.sh
- test/scenarios-bootc/presubmits/cos9-src@optional.sh
- test/scenarios-bootc/presubmits/el94-src@dual-stack.sh
- test/scenarios-bootc/presubmits/el94-src@multi-nic.sh
- test/scenarios-bootc/presubmits/el94-src@optional.sh
- test/scenarios/periodics/el94-src@isolated-net.sh
- test/scenarios/periodics/el94-src@offline.sh
- test/scenarios/periodics/el94-src@optional.sh
- test/scenarios/presubmits/el94-src@dual-stack.sh
- test/scenarios/presubmits/el94-src@ipv6.sh
- test/scenarios/presubmits/el94-src@multi-nic.sh
> USHIFT-4572: Rework network handing in launch_vm

- docs/user/howto_gateway_api.md
> USHIFT-4743: Add user docs for gateway api

- scripts/jira/requirements.txt
- scripts/jira/sprint_metrics.py
- scripts/jira/sprint_metrics_config.json
> NO-ISSUE: Sprint metrics charting capabilities and date adjustment

- scripts/aws/cf-gen.yaml
> USHIFT-4893: Add ipv6 back to aws cloudformation stack template

- test/bin/mirror_registry.sh
> NO-ISSUE: Fix selinux volume permissions when mirroring containers

- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/kube-storage-version-migrator.go
- pkg/controllers/openshift-route-controller-manager.go
- pkg/node/kubelet.go
Go's recover() only works within a go routine.
If the service spawns a Go routine to run the component, the recover() in service manager won't catch potential panics.
> USHIFT-4519: Recover and re-panic certain subcomponents

- test/bin/build_images.sh
- test/bin/pyutils/build_bootc_images.py
The problem was introduced by [this commit](https://github.com/openshift/microshift/pull/4225/commits/22f398702aa4c60c30f2533116d921260442ea0e).
> USHIFT-5086: Fix local package downloads after removing sudo

- scripts/mirror-images.sh
> [release-4.18] USHIFT-4737: Revert skopeo retry

- test/scenarios-bootc/periodics/el94-src@cncf-conformance.sh
- test/scenarios/periodics/el94-src@cncf-conformance.sh
> USHIFT-4912: Update sonobuoy to 0.57.2

- docs/config/Containerfile.bootc-rhel9
- docs/contributor/network/host_networking.md
- docs/user/howto_firewall.md
- scripts/devenv-builder/configure-vm.sh
- test/bin/scenario.sh
- test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel-optionals.containerfile
- test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-crel.containerfile
- test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-prel.containerfile
- test/image-blueprints-bootc/layer1-base/group2/rhel94-bootc-yminus2.containerfile
- test/image-blueprints-bootc/layer2-source/group1/cos9-bootc-source.containerfile
- test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source-base.containerfile
- test/image-blueprints-bootc/layer2-source/group1/rhel94-bootc-source.containerfile
- test/image-blueprints/layer1-base/group2/rhel94-microshift-yminus2.toml
- test/image-blueprints/layer1-base/group3/rhel94-microshift-previous-minor.toml
- test/image-blueprints/layer1-base/group4/rhel94-crel-with-optionals.toml
- test/image-blueprints/layer1-base/group4/rhel94-crel.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
- test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
> OCPBUGS-45192: Add ipv6 to trusted firewall zone

- test/suites/standard2/etcd.robot
See https://github.com/openshift/microshift/pull/4204 PR
> NO-ISSUE: fix doc message

- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- etcd/cmd/microshift-etcd/run.go
- etcd/go.mod
- etcd/vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
- etcd/vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
- etcd/vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/apiserver.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
- etcd/vendor/k8s.io/apiserver/pkg/authentication/user/user.go
- etcd/vendor/modules.txt
- packaging/microshift/config.yaml
- pkg/config/apiserver.go
- pkg/config/config.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-route-controller-manager.go
- pkg/node/kubelet.go
- test/suites/standard1/configuration.robot
> USHIFT-4932: TLS config options for api server

- docs/contributor/network/host_networking.md
- docs/user/howto_firewall.md
- scripts/devenv-builder/configure-vm.sh
- test/bin/scenario.sh
- test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
- test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-tuned.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
- test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
- test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
- test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
> [release-4.17] OCPBUGS-46040: Add ipv6 cluster network to firewall

- pkg/servicemanager/manager.go
> USHIFT-5295: Add trace log when service terminated abruptly

- etcd/vendor/github.com/openshift/microshift/pkg/config/apiserver.go
- pkg/config/apiserver.go
> OCPBUGS-48735: Fix default cipher suites when using TLS 1.2

- test/suites/standard2/configuration.robot
> NO-ISSUE: skip tls 1.2 cipher configuration tests

- scripts/devenv-builder/manage-vm.sh
- test/bin/scenario.sh
- test/scenarios-bootc/presubmits/el95-src@dual-stack.sh
> USHIFT-5402: Test harness VM IP address robustness

- test/run.sh
This is a manual cherry-pick from: https://github.com/openshift/microshift/pull/3769
> [release-4.15] USHIFT-4867: error in microshift RF tests randomize parameter

- test/suites/standard2/configuration.robot
> USHIFT-5378: Reenable TLS 1.2 tests

- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/config/config.go
- pkg/config/telemetry.go
- test/kickstart-templates/includes/post-microshift.cfg
> USHIFT-5401: Add telemetry configuration parameters

- pkg/util/net.go
> OCPBUGS-51366: Sort interfaces by index

- scripts/devenv-builder/configure-vm.sh
we have several CI jobs which usage optional RPMs with different RPM requirements.
such:
- footprint-and-performance-nightly  (we must have low-latency)
- ocp-conformance-optional-components (requires a lot of resources so we want to skip model-ai amd low-latency)
in any case  we  want to skip gateway-api
> USHIFT-5456: add optional-skipped-rpms option to configure-vm

- pkg/util/net.go
> [release-4.18] OCPBUGS-52206: Sort interfaces by index

- scripts/multinode/configure-sec.sh
> USHIFT-5457: Bump multinode test kubelet to 1.32.2

- assets/components/openshift-router/deployment.yaml
- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/config/ingress.go
- scripts/auto-rebase/manifests_patches/010-ingress-deployment-clientCA.patch
- scripts/auto-rebase/rebase.sh
- test/suites/standard1/router.robot
> USHIFT-5344: introduce ingress security customizations

- scripts/multinode/configure-sec.sh
> USHIFT-5459: Ensure same kubelet version across nodes in cncf tests

- scripts/multinode/configure-sec.sh
> [release-4.18] USHIFT-5458: Sync kubelet version with apiserver for cncf conformance

- test/suites/standard1/router.robot
> USHIFT-5491: Temporarily disable router security options tests

- pkg/controllers/telemetry.go
- pkg/node/kubelet.go
- pkg/telemetry/gather.go
- pkg/telemetry/telemetry.go
- test/kickstart-templates/includes/post-containers.cfg
> USHIFT-5298: Metrics collection

- pkg/controllers/telemetry.go
- pkg/util/net.go
> USHIFT-5492: Auto-detect disconnected env to disable telemetry

- packaging/rpm/microshift.spec
> USHIFT-5108: Update cri-o to 1.32 in rpm spec

- packaging/images/Makefile
- packaging/images/README.md
Depends on successful merge of https://github.com/openshift/release/pull/63022
> USHIFT-5475: Add multi-arch build functionality to CI brew image

- pkg/controllers/telemetry.go
- test/suites/standard2/telemetry.robot
> USHIFT-5399: Add RF tests for telemetry

- test/suites/standard2/telemetry.robot
> NO-ISSUE: Temporary skip for telemetry tests

- test/resources/microshift-rpm.resource
[USHIFT-3270](https://issues.redhat.com//browse/USHIFT-3270): Increase dnf low-bitrate timeout
> [release-4.15] USHIFT-3270: Increase dnf low-bitrate timeout

- packaging/rpm/microshift.spec
Manual cherry-pick of https://github.com/openshift/microshift/pull/4751
> [release-4.18] OCPBUGS-54448: Add hostname package dependency to microshift RPM

- pkg/admin/autorecovery/backup.go
- pkg/admin/prerun/version.go
- pkg/controllers/telemetry.go
- pkg/telemetry/gather.go
- pkg/telemetry/telemetry.go
- pkg/util/util.go
> USHIFT-5519: Add microshift_version to telemetry

- packaging/observability/opentelemetry-collector-large.yaml
- packaging/observability/opentelemetry-collector-medium.yaml
- packaging/observability/opentelemetry-collector-small.yaml
> USHIFT-5400 add observability profiles

- test/suites/optional/observability.robot
> NO-ISSUE: Relax requirements for observability line count tests

- docs/user/ai_model_serving.md
- packaging/observability/opentelemetry-collector-large.yaml
> USHIFT-5544: OTEL/observability: scrape Pods' metrics

- test/README.md
This PR addresses adding documentation about how to target any given vm using scenario.sh
Closes https://issues.redhat.com/browse/USHIFT-5528`.
> USHIFT-5528: Add documentation on how to target any given VM

- test/bin/ci_phase_boot_and_test.sh
- test/resources/observability.resource
- test/resources/prometheus.py
- test/suites/optional/observability.robot
- test/suites/telemetry/telemetry.robot
Manual back port from https://github.com/openshift/microshift/pull/4769 PR
> [release-4.19] USHIFT-2575: add 2 telemetry test cases

- assets/components/openshift-router/configmap-accesslog.yaml
- assets/components/openshift-router/deployment.yaml
- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/config/ingress.go
- scripts/auto-rebase/assets.yaml
- scripts/auto-rebase/manifests_patches/010-ingress-deployment-clientCA.patch
- scripts/auto-rebase/manifests_patches/011-ingress-deployment-access-logging.patch
- scripts/verify/verify-rf.sh
- test/assets/network/router-error-configmap.yaml
- test/suites/standard1/router.robot
> USHIFT-5660: Ingress access logging implementation and tests

- assets/components/openshift-router/deployment.yaml
- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/ingress.go
- etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
- packaging/microshift/config.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/config/ingress.go
- scripts/auto-rebase/manifests_patches/011-ingress-deployment-access-logging.patch
- test/scenarios-bootc/presubmits/el96-src@router.sh
- test/scenarios/presubmits/el94-src@router.sh
- test/suites/router/router.robot
- test/suites/standard1/router.robot
> USHIFT-5741: Add syslog configuration to ingress access logging

- test/bin/manage_loki.sh
- test/bin/manage_prometheus.sh
- test/resources/observability.resource
- test/scenarios-bootc/periodics/cos9-src@optional.sh
- test/scenarios-bootc/presubmits/el96-src@optional.sh
- test/scenarios/periodics/el94-src@optional.sh
- test/suites/optional/observability.robot
- test/suites/telemetry/telemetry.robot
> OCPBUGS-56497: Avoid port collisions in prometheus/loki RF

- test/resources/microshift-network.resource
- test/suites/network/multi-nic.robot
> NO-ISSUE: Remove fixed node port from hello-microshift service in RF

- test/suites/router/router.robot
> USHIFT-5778: Fix ordering in router security RF tests

- packaging/rpm/microshift.spec
> USHIFT-5820: Bump cri-o version to 1.33.0

- test/bin/mirror_registry.sh
> [release-4.19] OCPBUGS-57789: Fix signature checking in CI hypervisor

- scripts/verify/verify-py.sh
- scripts/zstd/images.py
- scripts/zstd/summary.sh
Example execution, simulating an upgrade from 4.19 to current 4.20:
```bash
$ ./summary.sh https://raw.githubusercontent.com/openshift/microshift/refs/heads/release-4.19/assets/release/release-x86_64.json https://raw.githubusercontent.com/openshift/microshift/refs/heads/main/assets/release/release-x86_64.json quay.io/pacevedo -o /tmp/output.txt
========================================
zstd:chunked Compression Simulation
========================================
[INFO] Checking requirements...
[SUCCESS] All requirements satisfied
[INFO] Checking Podman storage configuration...
[WARN] Podman storage configuration issues detected:
[WARN]   - Local storage configuration file not found, using default
[WARN] For optimal zstd:chunked …
```
> USHIFT-5805: Add zstd:chunked demonstrator script

- test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
- test/suites/standard2/configuration.robot
Manual cherry-pick of 0422b27b9211702bbd002f90e3fd4023c982054f
> [release-4.19] USHIFT-5879: Renable default config test on for the current release

- test/bin/subscription_manager_register.sh
Manual cherry-pick of a3083f7294559b5fc1b468b2ad5ecb16ee143280
> [release-4.18] OCPBUGS-58442: Fix subscription-manager registration command not to use sudo directly

- test/bin/subscription_manager_register.sh
Manual cherry-pick of a3083f7294559b5fc1b468b2ad5ecb16ee143280
> [release-4.14] OCPBUGS-58447: Fix subscription-manager registration command not to use sudo directly

- packaging/greenboot/microshift-running-check-cert-manager.sh
- packaging/rpm/microshift.spec
> USHIFT-5921: cert-manager greenboot deployment healthcheck

- pkg/sysconfwatch/sysconfwatch_linux.go
> USHIFT-5088: Send sigterm to self on sysconfwatch events

- assets/optional/cert-manager/manager/kustomization.yaml
- assets/optional/cert-manager/manager/manager.yaml
- assets/optional/cert-manager/release-cert-manager-aarch64.json
- assets/optional/cert-manager/release-cert-manager-x86_64.json
> USHIFT-5924: bump cert-manager manifests to 1.17 release

- test/suites/optional/generic-device-plugin.robot
- test/suites/optional/strings.py
**Which issue(s) this PR addresses**: This PR adds a new test case that helps to verify mountPath correctly renames the device within the container. Also modifies existing functions/code to make it reusable across tests.
> USHIFT-5723: Adding new test case for GenericDevicePlugin

- scripts/ci-ai-model-serving/tests/08-test-caikit-tgis.sh
- scripts/ci-ai-model-serving/tests/caikit-tgis/010-minio.yaml
- scripts/ci-ai-model-serving/tests/caikit-tgis/011-minio-connection-secret.yaml
- scripts/ci-ai-model-serving/tests/caikit-tgis/012-minio-sa.yaml
- scripts/ci-ai-model-serving/tests/caikit-tgis/020-inference-svc.yaml
- scripts/ci-ai-model-serving/tests/caikit-tgis/021-route.yaml
Includes usage of minio (S3 compatible storage) to verify other than OCI method of model delivery.
> USHIFT-5486 USHIFT-5905: AI Model Serving on AWS + NVIDIA: CAIKIT TGIS

- dashboards/grafana-dashboard-microshift-telemetry.configmap.yaml
> USHIFT-5960: Add grafana telemetry dashboard definition

- scripts/auto-rebase/rebase.py
> USHIFT-6088: Add verified label to rebase

- .gitignore
- ansible/README.md
- ansible/roles/nvidia-gpu-setup/README.md
- ansible/roles/nvidia-gpu-setup/defaults/main.yml
- ansible/roles/nvidia-gpu-setup/tasks/main.yml
- ansible/roles/nvidia-gpu-test/defaults/main.yml
- ansible/roles/nvidia-gpu-test/tasks/main.yml
- ansible/roles/nvidia-gpu-test/templates/gpu-test-workload.yaml.j2
- ansible/setup-node.yml
- ansible/vars/all.yml
- Add `nvidia-gpu-setup` role to do all the setup necessary on the node
- Add `nvidia-gpu-test` role to validate functionality of NVIDIA GPUs
- Modify `setup-node.yml` and `README.md` to reflect GPU changes
- Add new `vars/all.yml` as necessary
- Update `.gitignore` to add result & gpu-test-logs directories
> USHIFT-6094: Ansible Add NVIDIA GPU support

- test/scenarios-bootc/releases/el96-lrel@ginkgo-tests.sh
- test/scenarios/releases/el96-lrel@ginkgo-tests.sh
**Which issue(s) this PR addresses**: Currently storage gingko cases are failing due to disk size issue and fixing the same in this PR.
Closes #[USHIFT-6107](https://issues.redhat.com//browse/USHIFT-6107)
> USHIFT-6107: Increase the vm size for the storage cases to pass

- scripts/advisory_publication/README.md
**Which issue(s) this PR addresses**: advisory_publication_report.sh has been adjusted to get ocp release information from konflux advsiories so updating the readme as well to reflect the same.
> USHIFT-5992: Update README.md to have the latest information

- scripts/devenv-builder/configure-vm.sh
The script became hardly maintainable. 
If we make changes and backport them in the scope of [USHIFT-5911](https://issues.redhat.com//browse/USHIFT-5911), let's try to do it in a more digestable form.
> USHIFT-5911: Refactor configure-vm.sh script

- scripts/fetch_tools.sh
- test/bin/ci_phase_boot_and_test.sh
- test/bin/common.sh
- test/bin/scenario.sh
- test/scenarios-bootc/releases/el96-lrel@ginkgo-tests.sh
- test/scenarios/releases/el96-lrel@ginkgo-tests.sh
**Which issue(s) this PR addresses**: Manually rebasing the PR https://github.com/openshift/microshift/pull/5365 and https://github.com/openshift/microshift/pull/5423 and https://github.com/openshift/microshift/pull/5459
> [release-4.20] USHIFT-5983: Update scenario.sh script to run gingko tests

- test/bin/common_versions.sh
> [release-4.20] USHIFT-6035: Update rc as latest release type in common_versions

- test/image-blueprints/layer2-presubmit/group1/rhel96-lrel-optionals-tuned.toml
> NO-ISSUE: Fix brew dependency in image blueprints

- assets/optional/cert-manager/manager/images.yaml
- assets/optional/cert-manager/manager/kustomization.yaml
- scripts/auto-rebase/assets_cert_manager.yaml
- scripts/auto-rebase/rebase.py
- scripts/auto-rebase/rebase_cert_manager.sh
- scripts/auto-rebase/rebase_job_entrypoint.sh
- scripts/fetch_tools.sh
> USHIFT-5925: Cert manager auto rebase

- Makefile
- packaging/rpm/make-rpm.sh
- packaging/rpm/microshift.spec
- pkg/config/config.go
- pkg/config/telemetry.go
- pkg/controllers/telemetry.go
- pkg/version/version.go
> USHIFT-5548 Disable telemetry for community builds

- scripts/multinode/configure-pri.sh
- test/bin/common_versions.sh
- test/scenarios-bootc/periodics/el96-src@cncf-conformance.sh
- test/scenarios/periodics/el96-src@cncf-conformance.sh
> USHIFT-6191: Fix CNCF conformance tests

- scripts/multinode/configure-pri.sh
- test/scenarios-bootc/periodics/el96-src@cncf-conformance.sh
- test/scenarios/periodics/el96-src@cncf-conformance.sh
> [release-4.20] USHIFT-6191: Disable telemetry for cncf conformance

- scripts/ci-nvidia-device-plugin/setup/03-nvidia-container-toolkit.sh
Related to changes in v1.18 of nvidia-container-toolkit
> USHIFT-6207: Update nvidia-ctk invocation
