- install.sh
when running install.sh more than once to get a dev environment going, I encountered the following error causing the script to abort.
Error:
```sh
mkdir: cannot create directory ‘/var/lib/kubelet/’: File exists
```
> BUG: resolve directory already exists failure

- install.sh
running install.sh more than once results in the service file being appended rather than replaced causing the failure:
```sh
Failed to start microshift.service: Unit microshift.service has a bad unit file setting.
See system logs and 'systemctl status microshift.service' for details.
[root@rhel-n01 microshift]# systemctl status microshift.service
● microshift.service - Microshift
Loaded: bad-setting (Reason: Unit microshift.service has a bad unit file setting.)
Active: failed (Result: exit-code) since Tue 2021-06-15 19:07:35 EDT; 12min ago
Main PID: 873 (code=exited, status=203/EXEC)
Jun 15 19:07:35 rhel-n01.fly.lab systemd[1]: microshift.service: Main process exited, code=exited, status=203/EXEC
Jun 15 19:07:35 rhel-n01.fly.lab systemd[1]: microshift.service: Failed with result …
```
> BUG: remove append flag from systemd microshift.service file

- OWNERS
OWNERS is supposed to be YAML of a certain format, invalid OWNERS causes noise in Prow logs. The `verify-owners` [plugin](https://github.com/openshift/release/blob/master/core-services/prow/02_config/redhat-et/microshift/_pluginconfig.yaml#L6) would protect you if you added the file in a PR, but not when it was directly committed and pushed.
> Update OWNERS to be valid YAML

- Makefile
- images/build/Dockerfile
This PR standarizes the build flow for `make microshift` target so that the containerized microshift binary and the binary produced by the containerized build are known to be identical.  This is accomplished by first building the binary in the build container, copying it to the runnable image, and then copying it to the host.
Contingent on #115, as that defines a stable container runtime env.
> refactor containerized microshift build

- install.sh
This PR fixes issue #117 and makes sure kubectl binary is found when merging configs.
> Fix issue #117

- install.sh
Right now if the server is rebooted the *setenforce 0* value no longer exists. Adding this change will allow for us to be able to reboot until proper selinux support is added
> this will allow for microshift to be rebooted

- install.sh
This was an initial take at ports to allow. Once we get to the point of adding worker nodes it may need to massaged especially to allow the flannel coms. The testing I did on my side was to access the cluster from another instance within the same CIDR using the kubeconfig and then create an application using nodeport and verify I can access.
> initial entries

- Dockerfile
- hack/all-in-one/Dockerfile
- images/build/Dockerfile
It saves ~60 MB:
```
$ podman images | grep localhost
localhost/micro                              latest  548daf096454  35 seconds ago      335 MB
localhost/regular                            latest  c1d913e921fa  13 minutes ago      396 MB
```
Closes #141
> Use ubi8-minimal instead of regular ubi8

- Makefile
- images/build/Dockerfile
Fixes #170 
The binary build datetime data must conform to k8s formating `%Y-%m-%dT%H:%M:%SZ`.  However, the image artifacts tags must not have ':'s, so we replace them with '-'.  The image tags will change slightly to e.g. `quay.io/microshift/microshift:0.4.7-0.microshift-2021-07-22T19-13-14Z-linux-amd64`.
`kubectl version -o yaml`:
```
[root@fedora microshift]# oc version -o yaml
clientVersion:
buildDate: "2021-06-25T21:59:29Z"
compiler: gc
gitCommit: 8b4b09487463415374368af3bbc4ff2e6366477b
gitTreeState: clean
gitVersion: 4.7.0-202106252127.p0.git.8b4b094-8b4b094
goVersion: go1.15.7
major: ""
minor: ""
platform: linux/amd64
releaseClientVersion: 4.7.19
serverVersion:
buildDate: "2021-07-22T23:55:38Z" <---- this is the value affected by the change described above
compiler: gc
gitCommit: …
```
> Use k8s compliant build date

- pkg/cmd/init.go
- pkg/controllers/kube-api.go
fix #https://github.com/redhat-et/microshift/issues/175#issuecomment-884987918 
the root cause is that the kube-apiserver and kube-controller-mananger use different private keys for service account and service account tokens.
cc @tosin2013
> unify service account key and signing keys

- pkg/controllers/apiservice.go
- pkg/controllers/ocp-controllers.go
probing OCP APIs without registering them first will fail. This is found in the log the line produced [here](https://github.com/redhat-et/microshift/blob/main/pkg/controllers/ocp-controllers.go#L95)
```go
if err != nil {
logrus.Warningf("Failed to wait for ocp apiserver: %v", err)
return nil
}
```
> create api registration for ocp first before probing them

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement-tracking.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds PR and Issue templates in the hopes of standardizing user and contributor submissions.  See https://github.com/openshift/okd/issues/new/choose as an example.
Submitters may still open an blank git issue, but this can be toggled off if we choose.
Fixes #166
> add PR and issue templates

- pkg/cmd/run.go
Currently, Microshift checks for the non-existence of the data dir (/var/lib/microshift) to infer that
it runs for the first time and thus should initialize certs, kubeconfigs, etc. This creates a problem
on systems where /var/lib/microshift already exists (e.g. for pre-loading of images or manifests).
Until we have cleaned-up initialization as part of the multi-node work, this patch introduces a work-
around that makes initialization conditional on the cert dir being present instead, which is more
specific.
Closes #189
> Initialize also with pre-existing data dir

- install.sh
- scripts/release.sh
The install.sh should not change the name of the binary before calculating its checksum.
Closes #203
> fixes binary checksum validation and binary naming in releases

- Makefile
Scope container client search to _build_containerized target and check that one is found before running.  Report binary not in $PATH otherwise.
Closes #213
> check CTR_CMD in containerized build

- pkg/cmd/init.go
- pkg/config/config.go
- pkg/config/kubelet.go
- pkg/controllers/etcd.go
- pkg/controllers/kube-controller-manager.go
- pkg/node/kubelet.go
Rename Host.* variables to Node.* to be more aligned to the k8s perspective of nodes.
Signed-off-by: Carlos de Paula <me@carlosedp.com>
> Rename Host.* variables to Node.*

- pkg/config/kubelet.go
In hosts where resolv.conf is controlled by systemd-resolved, the file
/etc/resolv.conf contains only the localhost IP "127.0.0.53" that is
managed by systemd-resolved. The correct file with upstream servers
in this case is /run/systemd/resolve/resolv.conf that if exists
is appended to Kubelet config to be used on containers that use
"dnsPolicy: Default".
Signed-off-by: Carlos de Paula <me@carlosedp.com>
> Use systemd resolv.conf in case it exists

- images/build/Dockerfile
Patches out build image packages that are unavailable for redhat UBI images.
> patch build dockerfile

- hack/all-in-one/Dockerfile
Currently the AIO Dockerfile expects the microshift binary in current directory. This is no longer needed since recent release has both amd64 and arm64 support. This fix is to get platform specific binary in the Dockerfile, so we can use this to build a multi-arch image.
> retrieve platform specific microshift binary from release repo

- scripts/rebase.sh
This patch adds a scripts/rebase.sh script that takes as parameter the OKD release version string to rebase to and then updates
* vendored packages to the ones used by that OKD release,
* image digests in pkg/release/release_*.go for architectures supported by OKD,
* manifests in the assets directory
based on the release image metadata.
Closes #232
> Add script for rebasing onto later OKD version

- pkg/kustomize/apply.go
> Fix panic on buggy kustomization, add retries

- install.sh
I tested this with Vagrant `ubuntu/focal64` box and it works. Note due to #263, however, at this moment you can only do this:
```
CONFIG_ENV_ONLY=true ./install.sh
```
and you need to install `microshift` yourself with a [local build for Ubuntu](https://github.com/tadayosi/microshift/releases/download/test-ubuntu/microshift-ubuntu.tar.xz).
Other notes on the fix:
- `set -e -o pipefail` is bash specific so it doesn't make sense to use `/bin/sh`. Also `/bin/sh` resolves to `dash` on Ubuntu by default
- SELinux is already disabled by default for Ubuntu
No issues related to the pull req.
> Support Ubuntu for install.sh

- hack/all-in-one/Dockerfile
- hack/all-in-one/build-images.sh
kubelet vendors cadvisor, which vendors go-nvml. To make nvml run, we need to have libnvidia-ml.so on the node.
per cuda image, we need to have cuda-nvml-devel rpm.
```console
cuda-nvml-devel-11-4-11.4.43-1.x86_64
```
> build both cuda and ubi aio images

- README.md
Since the install script was updated to use bash options, sh fails to understand the script.
Closes #283
> update install command to use bash

- Makefile
- microshift.spec
- systemd/microshift.service
This can be built with the following commands for a release (download the source from github)
```
$ spectool -g -R microshift.spec
$ rpmbuild -ba microshift.spec
```
And with the following commands for local development and changes:
```
$ make devel-rpm
$ make devel-srpm
```
Related-Issue: #278
> Create initial spec for RPM packaging

- microshift.spec
- selinux/Makefile
- selinux/microshift.fc
Adds a Makefile for the selinux directory to help with local development
and adds an selinux microshift sub-package which contains the selinux
policies.
Related-Issue: #277
> Create RPM SELinux sub-module

- hack/all-in-one/README.md
- hack/all-in-one/microshift-aio-run
- hack/all-in-one/microshift-aio.service
Signed-off-by: Parul Singh <parsingh@redhat.com> 
This PR partially resolves https://github.com/redhat-et/microshift/issues/276
This PR:
Adds a systemd unit file to run microshift all-in-one with podman
The service:
-  creates `microshift-vol` podman volume if it does not exist
-  starts microshift via podman run command
-  writes location of KUBECONFIG to /etc/microshift-aio/microshift-aio.conf for easy `source /etc/microshift-aio/microshift-aio.conf` upon service startup
-  included the auto-update podman annotation, but this needs testing to be sure it works correctly (ie, not sure which tags, if it changes the tags)
* With `systemctl stop microshift-aoi`
* microshift pod is stopped/deleted
* …
> add fully aio systemd unit file and script

- hack/all-in-one/README.md
- hack/all-in-one/microshift-aio-run
To be able to run microshift via podman we need to run podman as sudo otherwise the cluster never gets up and running as nodes are stuck in NotReady state.
> add sudo to podman to avoid rootless

- hack/all-in-one/README.md
- hack/all-in-one/microshift-aio
- hack/all-in-one/microshift-aio.service
* typo in container name for microshift-aio.service ExecStop
* create "start" "stop" args in the microshift-aio-run script, rename script to microshift-aio
* typo in kubeconfig path record, updated vol to microshift-data there
> typo in microshift-aio container name on ExecStop

- Makefile
It's incompatible with the git version installed in the openshift
release CI [1]. And it's only meant to detect broken git repositories
instead of failing the git command. But we handle that already with the
`|| echo '4.7.0-0.microshift-unknown` part.
[1] https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22178/rehearse-22178-pull-ci-redhat-et-microshift-main-test-rpm/1441081828843720704
> Remove the --broke(n) git describe flag

- hack/all-in-one/Dockerfile
- hack/all-in-one/build-images.sh
Fix the build-images and some issues with the fc28 iptables
rpm installation.
My version of the #304 in #309 was missing the containers storage.conf
fix for rhel7.
Co-Authored-By: Huamin Chen <hchen@redhat.com>
> Continue support for RHEL7

- hack/all-in-one/README.md
- pkg/cmd/run.go
- pkg/controllers/ocp-controllers.go
- pkg/util/net.go
Refactor OCPControllerManager to conform to the internal service manager #239
Closes#239
> Refactor OCPControllerManager to conform to the internal service manager

- .github/workflows/release.yaml
- Makefile
- scripts/release.sh
Closes #313 
Adds a github action to execute microshift releases.  Removes the `target` parameter from release.sh as the action will always execute against `main:HEAD`.
> Add github action: "release

- install.sh
Applied best practice from Debian wiki:
https://wiki.debian.org/DebianRepository/UseThirdParty
Closes #286
> Remove usage of deprecated apt-key in install.sh #286

- Makefile
@iranzo @cooktheryan this can be merged separately or commit added to https://github.com/redhat-et/microshift/pull/411
> docs moved to `microshift-documentation`, remove `make docs-build,serve` target

- hack/cleanup.sh
- packaging/rpm/microshift.spec
This will allow running `cleanup-all-microshift-data` which will
ask for confirmation. This is something which should be useful
during development phase and which could potentially be removed
for a final product.
> Improve and pack the cleanup script in the rpms

- packaging/rpm/microshift.spec
- packaging/systemd/microshift-aio.service
- packaging/systemd/microshift-containerized.service
- packaging/systemd/microshift.service
> Cleanup and add containerized systemd services as part of the rpm

- .gitignore
rpm artifacts do not belong in git history
> git ignore rpm artifacts

- hack/cleanup.sh
Any of the other actions could stop the script (pkill not finding
the processes already gone, etc...).
This fixes it by continuing through until deletion of the microshift
data.
> Sometimes the cleanup script won't clean /var/lib/microshift

- go.mod
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/mdns/controller.go
- pkg/mdns/routes.go
- pkg/mdns/routes_test.go
- pkg/mdns/server/resolver.go
- pkg/mdns/server/resolver_test.go
- pkg/mdns/server/server.go
- pkg/mdns/server/server_test.go
- vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
- vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
- vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
- vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
- vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
- vendor/modules.txt
This commit adds support in microshift do do mDNS announcement on the LAN.
1) For the host name
For example if your hostname is `microshift.locaL`, other hosts will be able to
resolve microshift.local, because microshift will respond to the name with the IPv4 and IPv6 addresses.
2) For the hosts in the routes
for example, if you have a route with the host: `nginx.cluster.local`, and another `mqtt.cluster.local` ,
microshift would respond for both with the openshift-router IP addresses, so
other services in the lan can find those services.
This is a proposal of functionality which can be tested at this point, if we believe this is useful to the project 
I can start writing tests and documenting.
> mDNS responder for microshift

- packaging/images/microshift-aio/Dockerfile
Closes #474 #477
This `oc 4.8.9` to the microshift-aio image from [here](https://mirror2.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.8.9/openshift-client-linux-4.8.9.tar.gz)
Also, sets KUBECONFIG within the microshift-aio image
> Add oc client binary to microshift-aio, set KUBECONFIG

- pkg/node/kubelet.go
Closes #475
This PR adds ` "/system.slice/crio.service"` to kubelet flags to suppress error message regarding 
```
"Failed to get system container stats" err="failed to get cgroup stats for \"/system.slice/crio.service\": failed to get container info for \"/system.slice/crio.service\": unknown container \"/system.slice/crio.service\"" containerName="/system.slice/crio.service"
```
> fix for failed to get system container stats errors

- Makefile
- packaging/rpm/make-rpm.sh
- packaging/rpm/microshift.spec
Embedding those details, and then injecting then back during
srpm building (instead of looking for the git details which
doesn't exist anymore for an srpm build -it's a tarball-)
allows for microshift being properly compiled with those
details in the binary.
Closes-Issue: #476
> Embed git tags, commit ID and tree status in srpm

- Makefile
Full blown debug binaries can now be built with
`make DEBUG=true`
This is helpful for step-by-step debugging of MicroShift.
Remote debugging is then possible by running dlv with the following
parameters, and then connecting from your favorite IDE:
```
sudo dlv --listen=:2345 --headless --api-version=2 --accept-multiclient exec ./microshift -- run
```
> Add debug flags when building MicroShift

- assets/apps/0000_60_service-ca_05_deploy.yaml
- assets/core/0000_60_service-ca_04_configmap.yaml
- assets/core/0000_60_service-ca_04_secret.yaml
- pkg/assets/apps/bindata.go
- pkg/assets/core.go
- pkg/assets/core/bindata.go
- pkg/components/controllers.go
- pkg/components/render.go
Instead of hostPath volumes, create the configmap and secret to use configmap,secret volume type in service-ca deployment. This will allow service-ca pod to run as non-root, once the cluster-policy-controller is running in MicroShift.
> move service-ca volumes to cm,secret

- assets/crd/0000_03_quota-openshift_01_clusterresourcequota.crd.yaml
- assets/crd/0000_03_security-openshift_01_scc.crd.yaml
- pkg/assets/crd/bindata.go
SCC and ClusterResourceQuota validation behavior in OpenShift doesn't match MicroShift - ie, MicroShift validation is more strict, because it is kube-openapi validation while OpenShift uses custom validation. This PR remedies, so any SCC that can be created in OCP can be created in MicroShift. Also, SecurityContextConstraints shortNames `scc`  and ClusterResourceQuotas `clusterquota` rely on a hack in OpenShift, where these CRs  are _registered_ with openshift-apiserver, but _served_ with kube-apiserver. MicroShift doesn't require this, so instead, add the shortNames field to the CRD yaml. 
(same applies to ClusterResourceQuotas) 
Closes #480
> scc,clusterquota CRD remove 'nullable: true' fields from required and add shortNames

- pkg/cmd/run.go
- pkg/components/controllers.go
- pkg/components/render.go
- pkg/controllers/apiservice.go
- pkg/controllers/infra-services-controller.go
- pkg/controllers/openshift-apiserver.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-crd-manager.go
- pkg/controllers/openshift-default-scc-manager.go
- pkg/mdns/controller.go
- pkg/mdns/routes.go
PR to update names of PrepJob, APIComponents service managers, files, and functions to describe what they do:
```
NewOpenShiftPrepJob  ->  NewOpenShiftCRDManager
NewOpenShiftAPIComponents  ->  NewOpenShiftDefaultSCCManager
move openshift-controller-manager namespace creation to the StartOCM configure function
```
> ocp components simplify,clarify names

- packaging/rpm/microshift.spec
glibc-static is no longer required for building the microshift RPM
> no longer require glibc-static

- packaging/images/microshift-aio/Dockerfile
For microshift-aio image builds, the aarch64 oc binary is available as of 4.9.11 - rather than hardcoding the version to 4.8, and for amd64, bump the version and add $ARCH instead
Note: oc version will temporarily be ahead of component versions atm (4.8), but it is backwards compatible.
/cc @thinkahead
> microshift-aio image builds: bump oc download in aio image for aarch64 binary

- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/util/cert.go
Without reloading any later operation will result in a panic
trying to access nil rootCA or nil rootKey.
> Reload existing CA from disk on restart

- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/util/cert.go
Reverts redhat-et/microshift#499
> Revert "Reload existing CA from disk on restart"

- packaging/crio.conf.d/microshift.conf
- packaging/rpm/microshift.spec
cbr0 is the network name configured by flannel, the kubelet
will not schedule pods, and won't be ready until the CNI
configures properly the host.
This avoids host provisioner or service-ca from failing
on first start sometimes.
Fixes-Issue: #356
> Prevent crio from wiring pods until the CNI is ready

- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/util/cert.go
We need this back in, it was unrelated to those failures, this is only for re-loading the microshift CA from disk to memory on
microshift service reboot, so the bootstrap for multinode would work on later patches.
Reverts redhat-et/microshift#521
> Revert "Revert "Reload existing CA from disk on restart""

- packaging/systemd/microshift-containerized.service
We are not mounting the location of persistent volume mounts in the containerized version of microshift. If that container is replaced all persistent data will be lost
> missing persistent volume mount

- packaging/crio.conf.d/microshift.conf
Add the /opt/cni/bin directory to the search path
> Support crio.networks in rhel8 properly

- packaging/systemd/microshift-containerized.service
If the /var/hpvolumes does not exist MicroShift cannot start
> directory is required to exist

- validate-microshift/e2e/microshift/45-create-resources.sh
- validate-microshift/e2e/microshift/45-create-resources.yaml
- validate-microshift/e2e/microshift/50-assert-deployment.yaml
- validate-microshift/e2e/microshift/55-assert-svc.yaml
- validate-microshift/e2e/microshift/60-assert-pvc.yaml
We need to validate pvcs as well to ensure that they create based on our SELINUX rules
> more testing

- packaging/rpm/microshift.spec
In the docs we use microshift as the service name for containerized but when installed via RPM this is different its names microshift-containerized
> matching service name with docs

- packaging/rpm/microshift.spec
Fixing how the systemd file lands. The way install was managing it was causing containerized to takeover
> fixes the systemd files

- assets/apps/0000_70_dns_01-dns-daemonset.yaml
- pkg/assets/apps/bindata.go
- pkg/cmd/run.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-apiserver.go
- pkg/node/kube-proxy.go
- pkg/node/kubelet.go
- test/config.yaml
klog is a singleton library, and since we use that library from all
our services in a single process setting different log files won't
work, and will syphon all logs into the last log file we add.
Keep the simple strategy of letting all output to stderr for now.
Related-Issue: #493
> Do not modify default logging parameters

- packaging/systemd/microshift-containerized.service
Signed-off-by: Parul Singh <parsingh@redhat.com>
For podman deployment:
- systemd unit file for starting and managing microshift-containerized.
Closes #434, #433, #432
> selinux configs and  volume for microshift-containerized

- pkg/cmd/run.go
- pkg/util/net.go
- pkg/util/net_test.go
> Populate the the NO_PROXY environment

- hack/runDlv.sh
This is helpful to run the delve debugger in a remote host (or locally)
and then connect from your favorite IDE or delve instance for
remote debugging.
> add script to run dlv with the microshift binary

- packaging/systemd/microshift-containerized.service
Hpvolumes must be created and labeled on the host system. The hostpath provisioner container technically runs on the host rather than in microshift container so presenting a podman volume to the microshift container doesn't actually work.
> allow hpvolumes to be created at runtime and tagged accordingly

- pkg/servicemanager/manager.go
- pkg/servicemanager/manager_test.go
> If a service stops with error request all the other services to stop

- packaging/rpm/microshift.spec
Our docs explain how to download the .service file [1] instead,
and it has proven problematic to package this.
Fix the microshift.service being overwritten by microshift-containerized,
even when the non-containerized package only is installed.
Resolves-Issue: #591
> Remove the microshift-containerized subpackage

- packaging/rpm/microshift.spec
Signed-off-by: Ryan Cook <rcook@redhat.com>
Force set versions.
Output RHEL 8 
```
Total                                                          79 MB/s |  36 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
Preparing        :                                                                      1/1 
Installing       : microshift-selinux-4.8.0-2022_01_04_175420_24_g8a3819ee.el8.noarch   1/2 
Running scriptlet: microshift-selinux-4.8.0-2022_01_04_175420_24_g8a3819ee.el8.noarch   1/2 
Installing       : microshift-4.8.0-2022_01_04_175420_24_g8a3819ee.el8.x86_64           2/2 
Running scriptlet: microshift-4.8.0-2022_01_04_175420_24_g8a3819ee.el8.x86_64           2/2 
Running scriptlet: …
```
> force packaging versions

- pkg/controllers/openshift-crd-manager.go
Otherwise the service manager can't track completion of the service
when a stop is requested.
> OpenShift CRD Manager service must signal stop when completed

- pkg/controllers/kube-scheduler.go
> Make kube-scheduler Service return errors for healthcheck

- pkg/controllers/kube-apiserver.go
> Make kube-api-server to return errors from healthcheck

- packaging/rpm/microshift.spec
Modify the way we are creating and labeling directories
Closes #598
> Fix of selinux directories

- packaging/images/microshift/Dockerfile
- packaging/images/microshift/entrypoint.sh
- packaging/systemd/microshift-containerized.service
Otherwise some containers start before the flannel setup is
ready. This configuration guarantees that MicroShift.
Fixes-Issue: #605
Signed-off-by: Miguel Angel Ajo Pelayo <miguelangel@ajo.es>
Closes #605
> Install /etc/crio/crio.conf.d for containerized MicroShift

- packaging/rpm/make-microshift-app-images-rpm.sh
- packaging/rpm/make-microshift-images-rpm.sh
- packaging/rpm/microshift-images.spec
- pkg/release/get.sh
Pre-loading container images into CRI-O 
#162
Should be merged after #593
> Pre-loading container images into CRI-O

- pkg/release/release_amd64.go
Otherwise the later container rpm-packaging patches
will grab the wrong image, and the pause image is missing
for offline systems.
> Specify the right pause image used by cri-o

- pkg/controllers/kube-apiserver.go
If an audit log directory is provided, set the default audit log
retention age to 7 days. When `--audit-log-maxage` is not specified,
kube-apiserver audit logs are retained indefinitely, taking up
signficant space on the host node.
Closes #613
> Set Default Audit Log Retention

- .github/workflows/release.yaml
- Makefile
- packaging/images/components/archive.sh
- scripts/release.sh
These .tar.gzs later will be used by common non-podman capable builders
(copr) to create rpms with the container images.
> Pack containers into GitHub CI

- cmd/microshift/main.go
Stop setting GOMAXPROCS as more recent versions of Golang already defaults to NumCPU.
Aligns with OpenShift Standalone.
see: https://pkg.go.dev/runtime#GOMAXPROCS
> Use default GOMAXPROCS behavior

- pkg/controllers/openshift-apiserver.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-oauth-server.go
- pkg/kustomize/apply.go
- pkg/node/kube-proxy.go
This PR handles service stop/failure to make them all behave equally, and also to be able
to be stopped on request, please see individual commits.
- Make kube-proxy Service stoppable
- Exit on kustomization failure
- Make oauth-api-server stoppable and return errors
- Make ocp-api-server stoppable by manager
- Let the OpenshiftControllerManager service to be stopped
> Equalise service stop or failures

- packaging/rpm/microshift.spec
We need to check EL8/9 targets for such package being fully available
once built in copr nightly.
Signed-off-by: Miguel Angel Ajo Pelayo <miguelangel@ajo.es>
> Add conntrack-tools dependency to rpms

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/kube-apiserver.go
With this new parameter, service node port range can be successfully customized as a MicroShift config para:
config.yaml
```
cluster: 
url:                  "https://127.0.0.1:6443"
clusterCIDR:          "10.42.0.0/16"
serviceCIDR:          "10.44.0.0/16"
serviceNodePortRange: "1050-33000"
dns:                  "10.44.0.10"
domain:               "cluster.local"
```
We edit the router nodePort from 30001 to 2001:
```
[root@fedora ~] # oc get svc -A 
NAMESPACE           NAME                        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default             kubernetes                  ClusterIP   10.44.0.1       <none>        443/TCP                      109s
default             openshift-apiserver …
```
> Expose service node port range as MicroShift config

- pkg/cmd/run.go
- pkg/controllers/apiservice.go
- pkg/ipwatch/ipwatch.go
MicroShift endpoints rely on the host IP address. If that IP changes for whatever reason, APIs will be completely unavailable and MicroShift will stop working. This PR will detect IP host changes, and shutdown MicroShift. Since the production deployment model is based on systemd service, MicroShift service will be automatically restarted and endpoints will be recreated to be back in a functional state. 
Closes #556
> Restart MicroShift when IP address changes

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/kustomize/apply.go
- test/config.yaml
This extends the single path /var/lib/microshift/manifests
default into:
- /usr/lib/microshift/manifests
- /etc/microshift/manifests
- /var/lib/microshift/manifests
which will be evaluated in order. While the first one could be fully
managed in ostree (core components), the second one could be managed
by configuration management, the third one is maintained for backwards
compatibility purposes.
In addition the MicroShift configuration file supports customization
of this via the manifestsDir entry.
> Allow multiple kustomization paths

- packaging/rpm/paack.py
rpmbuild macros otherwise create a /usr/lib/.build-id reference
to every elf file inside the containers, and those clash with
other system rpms.
> Do not create .build-ids in rpms for containers (paack)

- assets/components/flannel/daemonset.yaml
- assets/components/hostpath-provisioner/daemonset.yaml
- assets/components/openshift-dns/dns/daemonset.yaml
- pkg/assets/bindata.go
- pkg/release/release_amd64.go
Ensures all deployments and daemonsets use `imagePullPolicy: IfNotPresent`, such that pre-loading container images works again.
Updates the pause image version to 3.6 (the one used by OCP/OKD 4.10).
> Fix ushift-52

- pkg/node/kubelet.go
Closes #617
Properly configure kubelet cgroup management.
All end-user workloads are partitioned under /kubepods.slice.
Global cpu/memory accounting should be enabled via systemd host configuration as part of host setup.
Maybe we can ensure this is done in the RPM as a follow-up?
> Enable kubelet cgroup management

- hack/all-in-one/Dockerfile
- hack/install.sh
- packaging/images/microshift-aio/Dockerfile
Get the following response when curling release version:
$ curl -s https://api.github.com/repos/redhat-et/microshift/releases
{
"message": "Moved Permanently",
"url": "https://api.github.com/repositories/361784175/releases",
"documentation_url": "https://docs.github.com/v3/#http-redirects"
}
> Update microshift release url

- packaging/rpm/microshift.spec
- packaging/systemd/hostpath-provisioner.service
> Package HPP systemd service in Microshift RPM for SELinux policies

- packaging/crio.conf.d/microshift.conf
Moves conmon to the pod cgroup slice.
Combined with #620 addresses [USHIFT-25](https://issues.redhat.com/browse/USHIFT-25).
> Move conmon to pod slice

- .gitignore
- packaging/rpm/make-rpm.sh
- scripts/image-builder/blueprint_v0.0.1.toml
- scripts/image-builder/build.sh
- scripts/image-builder/cleanup.sh
- scripts/image-builder/configure.sh
- scripts/image-builder/installer.toml
- scripts/image-builder/kickstart.ks
- scripts/image-builder/microshift-local.toml
- scripts/image-builder/openshift-local.toml
Implement a procedure for building microshift installer ISO using the locally built (for microshift) & downloaded (for OCP) RPM packages.
The build procedure amounts to running the following scripts from scripts/image-builder directory:
- configure.sh - One time build tool installation and system configuration
- cleanup.sh - Delete all the previous artifacts, podman & osbuilder images to conserve disk space
- make rpm - Build MicroShift locally and prepare its RPM packages
- build.sh - Build the _builds/microshift-installer.x86_64.iso
[USHIFT-54](https://issues.redhat.com//browse/USHIFT-54)
> Image builder using local RPM packages

- scripts/rebase.sh
Refactors `scripts/rebase.sh` so that individual steps (download release, updating go.mod, updating images, etc.) can be called individually.
Updates downloading of release to use `oc adm release` tooling. As a consequence, uses as parameter the URI of the release image, no longer the release version (e.g. `scripts/rebase.sh download quay.io/openshift/okd@sha256:6667...`).
Adapts updating of manifests to the reorganised asset directory structure.
> Refactor rebase.sh

- scripts/image-builder/build.sh
- scripts/image-builder/kickstart.ks
Minor enhancement to remove the SSH public key from kickstart and delete intermediate ISO to clean up disk space.
[USHIFT-54](https://issues.redhat.com//browse/USHIFT-54)
> Remove SSH key from kickstart and clean up intermediate ISO image file

- hack/reference-workload/amq-broker.yaml
- hack/reference-workload/app-logic.yaml
- hack/reference-workload/app-web-interface.yaml
- hack/reference-workload/kustomization.yaml
- hack/reference-workload/readme.md
- hack/reference-workload/untrusted-app-plugin.yaml
This adds an example customer workload which includes:
- amq-broker (AMQP + MQTT), volatile, no volumes or storage yet.
- app-api
- app-core
- app-web
- app-plugin1 restristed to talk only to app-api:8080
> Reference customer workload

- pkg/config/config.go
- pkg/controllers/kube-apiserver.go
The mocked command line parsing code is not needed to configure the
kube-apiserver, since we can construct an options struct directly.
> USHIFT-92: kube-apiserver: remove dead configuration code

- pkg/controllers/kube-scheduler.go
The mocked command line parsing code is not needed to configure the
kube-scheduler, since we can construct an options struct directly.
> USHIFT-93: kube-scheduler: remove dead configuration code

- pkg/controllers/openshift-apiserver.go
The mocked command line parsing code is not needed to configure the
openshift-apiserver, since we can construct an options struct
directly.
> USHIFT-94: openshift-apiserver: remove dead configuration code

- pkg/controllers/openshift-controller-manager.go
The mocked command line parsing code is not needed to configure the
openshift-controller-manager, since we can construct an options struct
directly.
> USHIFT-95: openshift-controller-manager: remove dead configuration code

- pkg/controllers/openshift-apiserver.go
- Fix AIO image to properly configure crio for MicroShift networking (#628)
- update LICENSE (#625)
- Reorganize assets (#619)
- build(deps): bump actions/upload-artifact from 2.3.1 to 3 (#612)
- build(deps): bump actions/checkout from 2 to 3 (#609)
- build(deps): bump technote-space/broken-link-checker-action (#572)
- Equalise service stop or failures (#637)
- Format value of error for stopped services (#644)
- Add conntrack-tools dependency to rpms (#624)
- add default annotation to kubevirt-hostprovisioner storageclass (#647)
- Expose service node port range as MicroShift config (#649)
- build(deps): bump actions/setup-go from 2 to 3 (#651)
- Build container rpms from docker repositories (#645)
- Restart MicroShift when IP address changes (#650)
- Allow multiple kustomization paths …
> cleanup extra format

- pkg/node/kube-proxy.go
Cobra CLI config code is no longer needed.
Closes [USHIFT-102](https://issues.redhat.com/browse/USHIFT-102)
> USHIFT-102: Remove dead configuration for Kube Proxy

- packaging/rpm/paack.py
overlay2 format includes a block device inside the overlay directory
but tar can't unpack that during the install phase.
We exclude that file and move it to %post
Closes [USHIFT-122](https://issues.redhat.com/browse/USHIFT-122)
> Fix paack issue with podman4 where overlay2 storage is used

- .lichen.yaml
- Makefile
Some exceptions have been added to .lichen.yaml for dual-licensed
go modules, as well as for some OpenShift components which
didn't specify licenses anywhere in their repositories.
Related-Issue: https://issues.redhat.com/browse/USHIFT-111
Signed-off-by: Miguel Angel Ajo Pelayo <majopela@redhat.com>
> Adds a licensecheck make target that runs lichen

- scripts/rebase.sh
Steps to improving the `rebase.sh` script:
- Change heuristic for rebasing go.mod to be more predictable (make explicit which dep comes from where instead of using "latest wins").
- Improve extracting of assets from release image.
- Copy in more assets.
- Remove unused code.
> Update rebase script

- pkg/controllers/apiservice.go
- pkg/controllers/openshift-apiserver.go
Duplicated authorization API resources cause garbage
collection issues.
Closes [USHIFT-88](https://issues.redhat.com/browse/USHIFT-88)
> USHIFT-88: Removing duplicated authorization API resources

- pkg/release/release_arm64.go
Removes the Flannel images from ARM release.
> Remove Flannel in favor of Bridge CNI plugin

- scripts/image-builder/build.sh
Report an error when the pull secret file specified on the command line does not exist or is empty.
Also adds general error message support to the usage function in the script so that it is clear what problem triggered a failure.
> USHIFT-133: Improve image build script error handling

- Makefile
- docs/rebase.md
- docs/rhel4edge_iso.md
- scripts/rebase.sh
This PR adds make targets, which call the existing image-builder scripts. Adding the 'iso' target provides a convenient single step, for example when building the install ISO for use in a test environment.
> Add an iso target to the Makefile.

- docs/rhel4edge_iso.md
- scripts/image-builder/build.sh
- scripts/image-builder/config/kickstart.ks.template
* Added -lvm_sysroot_size optional command line to scripts/image-builder/build.sh script
* Implemented custom LVM partitioning for sysroot volume, minimal size of 5GB
* The rest of the disk is left unallocated to be used by the CSI driver
* Documentation updated to describe the new functionality
[USHIFT-134](https://issues.redhat.com//browse/USHIFT-134)
> Enable LVM partitioning with custom sysroom volume size and separate data volume

- Makefile
- docs/rhel4edge_iso.md
- scripts/image-builder/build.sh
- scripts/image-builder/config/kickstart.ks.template
This PR adds support for inserting authorized keys into the kickstart file used to deploy Microshift.
It supports test automation under https://issues.redhat.com/browse/USHIFT-104
> Add support for authorized_keys to the kickstart file.

- Makefile
- pkg/assets/crd.go
- pkg/cmd/init.go
- pkg/components/components.go
- pkg/controllers/apiservice.go
- pkg/controllers/openshift-apiserver.go
- pkg/mdns/server/server_test.go
Use filepath.Join() to combine strings to build filenames instead of relying on string concatenation. This is more reliable if the configured directory name ends in a path separator character.
[USHIFT-180](https://issues.redhat.com//browse/USHIFT-180)
> Use filepath join

- docs/rhel4edge_iso.md
- scripts/image-builder/build.sh
- scripts/image-builder/config/kickstart.ks.template
* The minimal sysroot partition size is now 8GB
* Updated script and kickstart to use the current $(uname -i) arch instead of hard-coded x86_64
* Added version identifier to MicroShift ISO file name, i.e. microshift-installer-4.10.18.x86_64.iso
Closes [USHIFT-157](https://issues.redhat.com//browse/USHIFT-157)
> Change sysroot partition minimum to 8GB and avoid hard-coding arch

- packaging/rpm/microshift.spec
- packaging/systemd/configure-ovs-microshift.sh
- packaging/systemd/configure-ovs.sh
- packaging/systemd/microshift-ovs-init.service
- packaging/systemd/microshift.service
This script comes from the machine config operator [1] and configures
br-ex for use with OVNKubernetes, making sure that the main interface
is connected to br-ex.
[1] https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/configure-ovs-network.yaml
Closes [USHIFT-145](https://issues.redhat.com/browse/USHIFT-145)
> Add microshift-ovs-init script as oneshot during boot

- packaging/rpm/microshift.spec
microshift-ovs-init / configure-ovs.sh uses jq, and fails if it's not
installed. RHEL4Edge comes with jq by default but RHEL8 doesn't,
and we test on GCE with RHEL8.
> Add the jq dependency

- pkg/controllers/version.go
This is a follow-up to #776 
/assign @mangelajo
> USHIFT-180: version controller should only wait for kube-apiserver

- assets/components/openshift-dns/node-resolver/daemonset.yaml.tmpl
- assets/components/openshift-dns/node-resolver/update-node-resolver.sh
- docs/rebase.md
- scripts/rebase.sh
Adds the automation of rebasing assets like the hosted component manifests.
Ensures running `./scriptsrebase.sh manifests` on a staged upstream release always produces the same results.
For each component, the script runs 4 steps:
1. Copying relevant manifests from the release image or the operand manifests from the respective component's Operator.
2. Making the changes that the respective Operator would apply at runtime (e.g. set names, namespaces, etc.).
3. Making MicroShift-specific changes (overrides).
4. Replacing static values with the go template variables which MicroShift fills in.
If you run this script to test changes, not that there may be changes where fields change order in the YAML files. This is due to the YAML editor `yq` adding new files at the end, not in alphabetical …
> automate rebasing of manifests

- pkg/controllers/kube-apiserver.go
Errors returned by BuildConfigFromFlags were sent to the error
channel, but control flow continued despite the nil rest.Config
pointer.
> USHIFT-216: Fix kube-apiserver readiness check panic on kubeconfig error.

- pkg/controllers/kube-apiserver.go
They're nearly equivalent, but there are behaviors that are controlled
by whether or not the apiserver has signaled readiness at least
once (e.g. warnings are logged about receiving requests before ready).
/hold
I'd originally included this in https://github.com/openshift/microshift/pull/794 and later separated it accounting reasons. This patch depends on the other.
> USHIFT-16: Use /readyz for kube-apiserver readiness checks instead of /healthz.

- scripts/rebase.sh
Makes the rebase script accept _two_ pull specs for release images, the first the one for the amd64 architecture (as before), the second the one for the arm64 architecture. Then uses the arm64 release image to update that architecture's container image digests.
[USHIFT-177](https://issues.redhat.com//browse/USHIFT-177)
> Rebase arm64 images too

- packaging/systemd/microshift.service
- pkg/cmd/run.go
With the default type "simple", microshift is considered ready
immediately after its process has forked instead of waiting for an
sd_notify message.
> USHIFT-238: Set type of microshift.service to "notify".

- Makefile
- pkg/assets/bindata.go
- scripts/bindata.sh
- scripts/verify_bindata.sh
Exit from make with an error when there are changes to the assets directory not captured in bindata.go.
> USHIFT-240: fix verify-bindata target

- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
Get rid of cluster operations of ovn database by
switching from cluster to standalone mode.
The transaction processing steps are much simpler
in standalone mode compared with cluster mode.
Following is the sequence of actions for transaction execution in a standalone database: # Receive a transaction request.
Execute the transaction on in-memory data.
Write resulted changes on disk.
Reply to a client.
And the same thing in a single-node cluster: # Receive a transaction request.
Evaluate the transaction (same as execute, but changes are not yet committed).
Propose resulted changes to a raft storage module.
Update raft log with new changes.
Write changes on disk.
Mark proposed changes as applied.
Read last applied change from raft storage.
Re-evaluate changes and commit (basically, execute …
> Switch to ovn standalone mode

- scripts/rebase.sh
Avoid that the rebase script stomps over CRDs that aren't contained (yet) in the output of `oc adm release info --contents`.
> Copy explicit list of CRDs

- pkg/sysconfwatch/sysconfwatch.go
- pkg/sysconfwatch/sysconfwatch_linux.go
The binary itself might not run as expected on Apple or other non-linux
platforms, but we should avoid adding linux specific code without
alternatives for other systems/platforms.
As a bonus, this allows building microshift binary on M1 MacBook, improving development workflow/experience for some contributors without emphasizing that microshift is supported running on non-linux platforms.
> pkg/sysconfwatch: add non-linux variant to allow microshift binary to build

- pkg/mdns/controller.go
Recorded resolver name doesn't match mdns query name.
Assuming local hostname is "localhost.local", resolver
records domain name as "localhost.local", but a mdns
client would send query with name "localhost.local."
which results in no response from mdns server.
> fix mdns unqulified name

- pkg/release/release_amd64.go
This provides security on the image contents not to be modified.
Closes-Issue: https://issues.redhat.com/browse/USHIFT-225
> Pull the ovn-kubernetes image by sha256 hash

- pkg/cmd/run.go
- pkg/config/config.go
pprof is useful tool for profiling and finding hot cpu/mem spots
and should not be enabled in production deployment.
To start microshift with pprof enabled (disabled by default):
$ microshift run --debug.pprof=true
As an example to get golang heap memory snapshot of microshift main
process:
$ go tool pprof http://127.0.0.1:29500/debug/pprof/heap
Fetching profile over HTTP from http://127.0.0.1:29500/debug/pprof/heap
Saved profile in /root/pprof/pprof.microshift.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz
File: microshift
Build ID: 6b04bb6b4868ae9806a35aa9be8cef4fc448c606
Type: inuse_space
Time: Aug 4, 2022 at 10:45pm (EDT)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 75.06MB, 51.65% of 145.31MB total …
> cmd: add debug.pprof option to serve pprof on local port 29500

- hack/nginx-scc-test.yaml
- hack/scc-prep.sh
Creates an scc-test namespace, and a service account with
privileges on such namespace, but no admin privileges.
Then it creates an sa.kubeconfig file which can be used
to install a privileged nginx deployment which should
be forbidden.
> Hack scripts to help us debug scc

- Makefile
Disabling CGO would remove runtime dependency
of glibc and reduce the MicroShift binary size
Co-authored-by: Miguel Angel Ajo Pelayo <majopela@redhat.com>
> Disable CGO when building MicroShift binary

- scripts/image-builder/config/kickstart.ks.template
During the installation, firewall is enabled, but not active - thus "firewall-cmd --reload" is returning an error.
Closes [USHIFT-253](https://issues.redhat.com//browse/USHIFT-253)
> Fix ISO kickstart to check if firewall is active, not enabled

- pkg/controllers/kube-apiserver.go
This seems unused.
----
I'm just getting to know to codebase, this code seemed redundant.
> kube-apiserver: don't setup the oauth endpoint

- pkg/mdns/controller.go
- pkg/mdns/server/server.go
mDNS was listening on internal ovn interfaces (pods) and allocating
way too much memory per server, regular mDNS queries fit on unfragmented
regular 1500 MTU packets.
Closes: https://issues.redhat.com/browse/USHIFT-264
> mDNS: Avoid listening on internal interfaces and reduce footprint

- scripts/rebase.sh
- scripts/rebase_patches/0001-Fix-CSI-initialization-conflict.patch
- vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go
Node information (e.g. node name) is stored in a global variable during initialization of the CSI volume plugin. Both kubelet and kube-controller-manager initialize the CSI volume plugin, so whichever one initializes last "wins" and their state is persisted. The kube-controller-manager initializes the plugin in such a way that it can't be used to register kubelet plugins. This is responsible for the inconsistent failures we were seeing in E2E storage tests.
K3S (which also embeds kubelet and kube-controller-manager) discovered and is affected by the same issue. This PR adds their patch. I'm opening a Microshift issue to attempt an upstream change that will allow both projects to drop this patch.
> USHIFT-269: Carry patch for CSI plugin initialization conflicts between kubelet and kube-controller-manager.

- pkg/mdns/controller.go
A bug prevented route mDNS hosts from being announced when the host
doesn't have an mdns compliant hostname, while that fact should
be independent.
Closes Issue: https://issues.redhat.com/browse/USHIFT-271
> Store host IPs for mDNS routes even if hostname is not .local

- pkg/mdns/controller.go
- pkg/mdns/routes.go
The logging parameters were set for structured logging (InfoS) in
some cases, while Infof is being used (same for Errorf).
Closes: https://issues.redhat.com/browse/USHIFT-263
> Fix mDNS package logging

- README.md
- docs/debugging_tips.md
Start a new section of the user documentation with debugging tips by
including information about how to determine the version of
MicroShift.
Closes: [USHIFT-271](https://issues.redhat.com//browse/USHIFT-271)
> USHIFT-272: start debugging tips doc with version information

- packaging/systemd/microshift.service
Closes #[USHIFT-197
](https://issues.redhat.com/browse/USHIFT-197)
> USHIFT-197: Enable resource accounting in MicroShift systemd service

- assets/components/kube-apiserver/config-overrides.yaml
- assets/components/kube-apiserver/defaultconfig.yaml
- assets/components/odf-lvm/topolvm-node-securitycontextconstraint.yaml
- pkg/assets/bindata.go
- pkg/components/storage.go
- pkg/controllers/kube-apiserver.go
- scripts/rebase_patches/0010-kube-apiserver-command-context.patch
- vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go
Rather than maintain a parallel implementation of the kube-apiserver
cobra command's "Run", construct a KubeAPIServerConfig manifest file
and pass its path as a command argument. This preserves the
OpenShift's patched kube-apiserver behavior, including notable changes
to admission configuration: SecurityContextConstraint enforcement,
timeout, per-namespace runlevels, and custom resource validation and
defaulting for included OpenShift APIs.
> USHIFT-213: Enable OpenShift flavor of kube-apiserver.

- OWNERS
Based on his great understanding of the Kubernetes and OpenShift control plane and his great contributions to MicroShift, I think Ben should be part of the MicroShift's core team.
Thanks @dhellmann for suggesting this.
> Proposing Ben Luddy as reviewer/approver

- hack/cleanup.sh
ovn-kubernetes CNI config file is written by ovnkube-node
process and will be left over if ovnkube-node doesn't
exit gracefully (which is the case when stopping MicroShift
service).
Crio waits for the existence of ovn-kubernetes CNI config
to mark the node as Ready. If ovn-kubernetes CNI config is
not cleaned up, node will become ready immediately on next
boot w/o waiting for ovn network become ready.
> cleanup ovn kubernetes CNI binary and config file

- packaging/systemd/microshift.service
- pkg/cmd/run.go
- pkg/sysconfwatch/sysconfwatch_linux.go
Closes [USHIFT-242](https://issues.redhat.com/browse/USHIFT-242)
**Description**:
- Fixes premature systemd service readiness by clearing `NOTIFY_SOCKET` environment variable so apiserver, kubelet, or openshift-controller-manager won't send `READY=1`. The variable is restored when MicroShift is considered ready.
- Adds closure of `sysconfwatch`'s `ready` channel, so MicroShift's readiness is no longer blocked.
- Adds 2m service start timeout. If service does not start in that time, it'll be terminated and restarted.
- `systemctl start microshift` won't return until MicroShift is ready which now will happen much later (currently ~45s based on several tries).
> Fix early systemd readiness

- pkg/node/kubelet.go
Closes #661  [USHIFT-28](https://issues.redhat.com/browse/USHIFT-28)
**Desc**
Adds node labeling based on MicroShift roles. There's a slight difference between MicroShift's and kubelet's roles: [control-plane vs controlplane, worker vs node](https://github.com/openshift/microshift/blob/79b64b05d843d2a4aa2c7a406276ece69d019f81/vendor/k8s.io/kubelet/pkg/apis/well_known_labels.go#L50)
> Set node-role.kubernetes.io based on MicroShift roles

- pkg/servicemanager/manager.go
If the context is canceled, the first `context.Canceled` error returned from a component results in a second SIGTERM that ends the process without waiting for other components to stop.
> USHIFT-266: Don't send second SIGTERM on context.Canceled.

- ansible/README.md
- ansible/roles/common/tasks/readinesscheck.yml
- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/install-microshift/tasks/main.yml
- ansible/roles/manage-repos/tasks/main.yml
- ansible/roles/microshift-start/tasks/main.yml
- ansible/setup-node.yml
- Check for presence & conditional installation of subscription-manager
and oc/kubectl binary
- Small change to pod readiness count and command
- Small update to README for missing vars
- Formatting fixes
**Which issue(s) this PR addresses**: [USHIFT-293](https://issues.redhat.com/browse/USHIFT-293)
> USHIFT-293: Ansible GCP Compatibility Update

- packaging/systemd/configure-ovs.sh
Configure-ovs.sh gets ovn gateway interface using
default route, which may not exist in no internet
connection environment. This change falls back to
use first available route interface in the case
that no default route is found.
> Use first available route interface

- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
ovn database may grow to several Megabytes, compact
the database in a short cadence (default: 10s) other
than waiting until automatic compact in 24 hours.
> compact ovn databases periodically

- scripts/devenv-builder/configure-vm.sh
Building the rpm runs make to build the binary so there is no need to
run it separately in the dev environment configure script.
/kind cleanup
> skip extra make step in dev environment automation

- docs/devenv_rhel8_auto.md
- scripts/devenv-builder/create-vm.sh
This change makes it possible to create a wrapper script that sets
variables instead of passing arguments on the command line, which
makes it easier to remember what each value means.
/type cleanup
> update create-vm.sh to support taking inputs via environment variables

- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/install-microshift/files/etcd.service
- ansible/roles/install-microshift/tasks/main.yml
- ansible/roles/manage-repos/defaults/main.yml
- ansible/vars/all.yml
- Support topolvm disk, building external etcd, and alternative microshift repos.
- Add pidstat sample interval and additional RHEL repo.
**Which issue(s) this PR addresses**: https://issues.redhat.com/browse/USHIFT-337
> USHIFT-337: Support topolvm disk, building external etcd, etc

- docs/devenv_rhel8.md
- scripts/devenv-builder/configure-vm.sh
Changes the dev env documentation + automation script to align with the way we'd expect users to install MicroShift:
* microshift*.rpms (should) pull in package deps, so don't install them manually.
* MicroShift's service units (should) take care of starting service units they depend on, so do not start them manually.
* Install oc and kubectl clients from the repos rather than side-loading them.
> align dev install with prod and simplify

- assets/components/openshift-router/ingress-to-route-controller-clusterrole.yaml
- assets/components/openshift-router/ingress-to-route-controller-clusterrolebinding.yaml
- pkg/assets/bindata.go
- pkg/components/controllers.go
- scripts/rebase.sh
Add assets for RBAC for ingress-to-route-controller.
Update rebase.sh to pull updates to those assets in the future.
Partial fix for [USHIFT-333](https://issues.redhat.com//browse/USHIFT-333)
Partial fix for #860
> USHIFT-333: add ingress-to-route-controller RBAC

- packaging/rpm/microshift.spec
The problem occurs when crio has just been installed and not enabled yet.
Closes #899
> USHIFT-361: Fix RPM post install script not to return error when crio is not running

- pkg/controllers/openshift-controller-manager.go
Route requests from openshift-controller-manager using protobuf
encoding aren't supported by the CRD-based custom resource handler.
> Set application/json content-type for OCM clients.

- assets/core/namespace-openshift-infra.yaml
- pkg/assets/bindata.go
- scripts/rebase.sh
The openshift-infra namespace is now gathered from the
cluster-kube-controller-manager-operator assets.
This rebases #885.
/cc @oglok
> Use OpenShift Infra NS from KCM operator

- .gitignore
Update the ignore pattern so if _rpmbuild is a symlink it is still
ignored.
/type cleanup
> ignore rpm build location

- packaging/rpm/microshift.spec
Update the spec file to not emphasize MicroShift being an experimental
or research project.
> USHIFT-140: remove experimental comments from RPM description

- pkg/config/config.go
- pkg/controllers/kube-apiserver.go
- pkg/util/net.go
MicroShift and some service components (e.g. kube-apiserver)
get nodeIP through the default route interface. When there is
no internet connection, default route won't exist which results
in failure starting services.
For example,
kubelet expects nodeIP to not be 127.0.0.1:
kubelet_node_status.go:622] "Failed to set some node status fields"
err="failed to validate nodeIP: nodeIP can't be loopback address"
node="localhost.localdomain"
kube-apiserver fails to find suitable network address:
service kube-apiserver exited with error: kube-apiserver configuration
error: Unable to find suitable network address.error='no default routes
found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the
AdvertiseAddress directly or provide a valid BindAddress to fix this.
Closes …
> Get node IP through ovn gateway interface when no default route

- packaging/systemd/configure-ovs.sh
- packaging/systemd/microshift-ovs-init.service
MicroShift service runs right after system boot when
dhcp address may not be available on node interface.
This results in configure-ovs.sh script getting non
default route interface on lo device which cannot be
added to ovn gateway interface br-ex.
Closes #[USHIFT-340](https://issues.redhat.com//browse/USHIFT-340)
> Wait for default route to become available after boot

- Makefile
- pkg/servicemanager/manager.go
- scripts/rebase_patches/0020-klog-component-names.patch
- vendor/k8s.io/klog/v2/goroutine_labels.go
- vendor/k8s.io/klog/v2/klog.go
Adds servicemanager service names as a new field to klog headers, like this:
```
Aug 31 21:43:28 microshift.localdomain microshift[598329]: I0831 21:43:28.008100  598329 kube-apiserver kube-apiserver.go:295] "kube-apiserver" is ready
Aug 31 21:43:28 microshift.localdomain microshift[598329]: I0831 21:43:28.008132  598329 kube-scheduler manager.go:114] Starting kube-scheduler
Aug 31 21:43:28 microshift.localdomain microshift[598329]: I0831 21:43:28.008151  598329 kube-controller-manager manager.go:114] Starting kube-controller-manager
Aug 31 21:43:28 microshift.localdomain microshift[598329]: I0831 21:43:28.008156  598329 openshift-crd-manager manager.go:114] Starting openshift-crd-manager
Aug 31 21:43:28 microshift.localdomain microshift[598329]: I0831 21:43:28.008787  598329 …
```
> USHIFT-336: Inject embedded component names into klog headers.

- assets/components/openshift-router/service-cloud.yaml
- pkg/assets/bindata.go
- pkg/controllers/kube-apiserver.go
- scripts/rebase.sh
Setting service nodeport range to KubeAPIServerConfig.ServicesNodePortRange
doesn't take effect, needs to use service-node-port-range in
KubeAPIServerConfig.APIServerArguments
Closes #[USHIFT-334](https://issues.redhat.com//browse/USHIFT-334)
> Make nodeport range configurable

- go.mod
- go.sum
- scripts/rebase.sh
- vendor/modules.txt
Update go.mod and rebase script so it handles recent addition of OPC.
Partially addresses [USHIFT-367](https://issues.redhat.com//browse/USHIFT-367)
> USHIFT-367: add OPC to rebase script and update go.mod

- assets/crd/0000_01_route.crd.yaml
- pkg/assets/bindata.go
Update to copy of file from
openshift/api@0b39f81154fa42abe26933181141ed4b4e3ad247
Note to reviewers: There were a lot of whitespace changes in the YAML file being updated, so I split this PR into 2 commits. The first updates the "base" by using a recent commit in openshift/api that was older than the validation change we care about. The second includes only that validation update.
> USHIFT-333: update validation for tls in route crd

- cmd/microshift/main.go
- pkg/cmd/run.go
- pkg/cmd/showConfig.go
- pkg/config/config.go
Add a command to show the default configuration, modified to make it
suitable for global use on the host.
Related to [USHIFT-19](https://issues.redhat.com//browse/USHIFT-19)
> USHIFT-364: add command to show default configuration

- pkg/cmd/init.go
- pkg/controllers/kube-apiserver.go
- pkg/node/kubelet.go
- pkg/util/cryptomaterial/certpaths.go
- pkg/util/cryptomaterial/trustupdates.go
This PR separates the CAs that are trusted by the kubelet for client cert authentication.
The `cmd/init.go` is starting to be a little messy, we will probably want to refactor it eventually.
---
This is currenly untested, I would be surprised if everything worked because this finally cuts the trust of a kubelet to the ultimate bundle for client cert authentication, but let's see what happens,
> AUTH-296: Separate kubelet client trust

- docs/design.md
Capture some guidelines that we have been implicitly using in the
discussion of how to expose CSI configuration options.
/assign @copejon @fzdarsky
/type documentation
> expand configuration section of design guidelines

- assets/crd/authorizationv1-local-apiservice.yaml
- assets/crd/securityv1-local-apiservice.yaml
- pkg/assets/bindata.go
- pkg/assets/crd.go
Certain resources (including RoleBindingRestrictions and
SecurityContextConstraints) belong to an API group served on OpenShift
by openshift-apiserver but have been migrated to CRDs. The
kube-apiserver on OpenShift carries a series of patches to ensure that
they coexist politely with openshift-apiserver. On MicroShift, the
group discovery handler for these types is never registered in the
aggregator (expecting openshift-apiserver to do it).
> USHIFT-318: Create local APIServices for formerly-openshift-apiserver CRDs.

- .gitignore
- Makefile
- docs/devenv_rhel8.md
- docs/rhel4edge_iso.md
- packaging/rpm/make-rpm.sh
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
- scripts/image-builder/cleanup.sh
Move all of the build output under an `_output` directory at the root
of the repository to make it easier to clean it all up at one time and
to make the .gitignore file easier to manage.
/assign @fzdarsky
> USHIFT-362: consolidate all build output directories

- scripts/rebase.sh
Do not try to copy OVNk manifests (yet), as we're still rebasing to upstream releases that do not yet contain them.
Also, do not redirect errors to /dev/null to not mask unexpected issues.
> Do not try to rebase OVNk manifests

- assets/core/0000_50_cluster-openshift-controller-manager_00_namespace.yaml
- assets/crd/0000_03_securityinternal-openshift_02_rangeallocation.crd.yaml
- pkg/assets/bindata.go
- scripts/rebase.sh
Updates rebase script to copy in more of the assets/core and assets/crd manifests from the respective OpenShift components.
Signed-off-by: Frank A. Zdarsky [fzdarsky@redhat.com](mailto:fzdarsky@redhat.com)
Closes [USHIFT-251](https://issues.redhat.com//browse/USHIFT-251)
> USHIFT-251: Sync more core and CRD manifests

- assets/components/openshift-router/deployment.yaml
- assets/components/openshift-router/namespace.yaml
- assets/components/openshift-router/service-cloud.yaml
- assets/components/openshift-router/service-internal.yaml
- pkg/assets/bindata.go
- scripts/rebase.sh
Updates the openshift-router manifests using the latest rebase.sh automation.
Some of the changes are completely neutral and result from the adoption of yq, e.g. reordering of fields resulting from yq appending added fields at the end rather than ordering them in alphabetically or different indentation.
More importantly, though, it also aligns manifests more closely with those found on an equivalent running OpenShift cluster. This includes different labels, annotations, and selectors, environment variables.
Signed-off-by: Frank A. Zdarsky [fzdarsky@redhat.com](mailto:fzdarsky@redhat.com)
> USHIFT-367: apply rebase.sh to router manifests and align with OCP 

- pkg/cmd/run.go
- pkg/config/config.go
- pkg/config/config_test.go
- test/config.yaml
This PR fixes tests in pkg/config/config_tests.go that were either flaky in CI or not correctly testing the function under test.
Also, adds command line flags for parameters for which we already support configuration via config.file.
Closes [USHIFT-383](https://issues.redhat.com/browse/USHIFT-383)
> Fix config params and tests

- assets/components/odf-lvm/topolvm-controller_deployment.yaml
- assets/components/odf-lvm/topolvm-node_daemonset.yaml
- pkg/assets/bindata.go
Add priorityClassName to TopoLVM pods for better scheduling/preemption capabilities.
Currently, MicroShift does not have a default priority for pods, which means they resolve to 0. In order to have pods properly scheduled for the cluster to be in healthy status, and also be able to support features like [graceful node shutdown](https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown), we must have all critical pods with the correct priority.
[Pod preemption reference](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/)
> USHIFT-373: add priorityClassName to topoLVM

- scripts/rebase.sh
Drop the "-x86_64" suffix from the rebase branch's name.
Use "make vendor" instead of vendoring and patching manually.
> Some clean-ups for the rebase script

- go.mod
- pkg/cmd/init.go
- pkg/util/cryptomaterial/certpaths.go
- pkg/util/cryptomaterial/signers.go
- pkg/util/cryptomaterial/signers_test.go
This PR adds a refactoring of the current certificate initialization code.
The new code allows describing certificate chains by Go structures, feeding them into a builder object, and then creating them all at once once the developer is happy with what they have.
The new structure currently only allows to retrieve leaf certificate certs/key PEMs in a path-like manner, but might be extensible to perform queries on *x509.Certificate objects in the future, so as to allow for checking expirations and could be thus fed to a controller that is capable of handling rotations over the structure.
/cc @ibihim
> AUTH-296: certificate chains init refactoring

- docs/enable_apis.md
When we removed the openshift-apiserver dependency, most of the APIs
from the authorization.openshift.io group were removed. Update the
documentation to reflect that change.
> USHIFT-399: update list of enabled APIs

- pkg/cmd/init.go
- pkg/components/controllers.go
- pkg/util/cert.go
- pkg/util/cryptomaterial/certpaths.go
This PR splits out service-ca trust chain from the root CA.
/hold
https://github.com/openshift/microshift/pull/939 should be merged first, I'm creating this PR just to see whether splitting out service-ca brings any issues.
> AUTH-296: split out the service-ca trust chain

- pkg/assets/crd.go
- pkg/cmd/init.go
- pkg/components/components.go
- pkg/config/config.go
- pkg/controllers/cluster-policy-controller.go
- pkg/controllers/infra-services-controller.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-controller-manager.go
- pkg/controllers/openshift-default-scc-manager.go
- pkg/controllers/version.go
- pkg/kustomize/apply.go
- pkg/mdns/controller.go
- pkg/node/kubelet.go
Provide a consistent way to calculate the path to a set of managed
kubeconfig files so we can avoid errors with path management
throughout the code.
> USHIFT-261: clean up path handling for kubeconfig files

- packaging/systemd/configure-ovs.sh
Closes #[USHIFT-365](https://issues.redhat.com//browse/USHIFT-365)
> USHIFT-365: support ipv4.ignore-auto-dns on ovs-interface br-ex

- pkg/config/config.go
Remove the empty and unused `Node` and `ControlPlane` fields of the
`MicroshiftConfig` struct to clean up the output of `microshift show-config`.
> USHIFT-400: remove unused fields in configuration data structure

- pkg/cmd/init.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/openshift-controller-manager.go
- pkg/util/cryptomaterial/signers.go
This PR makes the following changes:
- makes the KCM sign CSRs with the actual CSR signer certificate introduced in https://github.com/openshift/microshift/pull/898
- separates the root CA from the client-ca that is distributed by the KAS as the client cert trust
> AUTH-296: Cut off the root CA from the cluster-distributed client CA

- hack/all-in-one/Dockerfile
- hack/all-in-one/build-aio-dev.sh
- hack/all-in-one/build-images.sh
- packaging/images/components/components/base-image/Dockerfile
- packaging/images/microshift-aio/Dockerfile
- packaging/images/microshift/Dockerfile
This will allow to get the latest 8.y.z security fixes, and bring some consistency in our build process.
We should bump 8.6 to 8.7 when 8.7 UBIs are released
The difference between building on top of 8.4 and 8.6 are highlighted on this security scan:
https://quay.io/repository/rhn_support_ekasprzy/microshift-aio?tab=tags
I manually tested the all in on build and things are working as expected (control plane and all infra pods as part of the cluster start and run successfully) Red Hat Enterprise Linux major releases have a stable API for kernel and glibc (https://access.redhat.com/articles/rhel8-abi-compatibility) so we shouldn't expect breakage anyway.
> Set UBI version to latest UBI minor version

- pkg/cmd/init.go
- pkg/controllers/kube-apiserver.go
- pkg/util/cryptomaterial/certpaths.go
This PR narrows the trust for the requestheader-client-ca distributed in the cluster in the `kube-system/extension-apiserver-authentication` CM.
/cc @oglok @ibihim
> AUTH-296: Cut off the root CA from the cluster-distributed requestheader-client-ca

- docs/rhel4edge_iso.md
- packaging/rpm/make-microshift-images-rpm.sh
- packaging/rpm/paack.py
Closes [USHIFT-362](https://issues.redhat.com//browse/USHIFT-362)
> USHIFT-362: Fix output directories for container RPM builds

- scripts/rebase_patches/0002-disable-APIrequestcount-controller.patch
- vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
The APIrequestcount controller cannot be disabled via configuration param in the OpenShift KAS. This carried out patch disables it and avoids recurrent calls to this non-existing API.
> USHIFT-401: Carried out patch to disable APIrequestcount controller

- pkg/cmd/init.go
- pkg/controllers/openshift-controller-manager.go
- pkg/util/cryptomaterial/certpaths.go
- pkg/util/cryptomaterial/signers.go
This PR introduces a couple of smaller fixes to the current code related to certificates.
Namely:
- actually use the serving CA to generate serving cert for the OCM
- don't generate new sub-CA certificates for the CSR signer with every restart
- fix the CA validity days to match OCP
/cc @oglok @ibihim
> AUTH-296: Certificate-related fixes

- scripts/rebase.sh
This will speed up the rebase process and save a lot of bandwidth.
> rebase.sh: Use shallow clone

- ansible/roles/common/tasks/readinesscheck.yml
Fix wait-for-pods command in performance test scripts not to depend on the number of pods
Closes [USHIFT-294](https://issues.redhat.com//browse/USHIFT-294)
> Fix wait-for-pods command in performance test scripts 

- docs/howto_config.md
Closes [USHIFT-449](https://issues.redhat.com//browse/USHIFT-449)
> USHIFT-449: Fix auto-apply for manifests to run in a non-default namespace

- pkg/controllers/kube-apiserver.go
Rebase of https://github.com/openshift/microshift/pull/924.
> API-1437: Enable kube-apiserver option send-retry-after-while-not-ready-once

- go.mod
- vendor/modules.txt
`go-bindata` is no longer used by openshift/kubernetes, it's planned to be changed with `go:embed` in future
> Fix 4.12 nightly rebase

- assets/components/ovn/configmap.yaml
- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
ovnk local gateway mode allows pod egress traffic to use system routes, also NodePorts will work over multiple interfaces.
> Switch to ovnk local gateway mode

- scripts/image-builder/configure.sh
rpm-build package provides the `rpmbuild` command and without it creating the local rpm fails which kind of break the flow for `docs/rhel4edge_iso.md` document.
> scripts/image-builder/configure.sh: Add rpm-build to package list

- cmd/microshift/main.go
- pkg/config/config.go
- pkg/config/config_test.go
- vendor/k8s.io/component-base/cli/OWNERS
- vendor/k8s.io/component-base/cli/run.go
- vendor/modules.txt
- fixes -v flag
- hide unsupported flags in help
this is reaction to https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components. Similar change discussed in https://coreos.slack.com/archives/CB48XQ4KZ/p1662394269749719?thread_ts=1661425151.276079&cid=CB48XQ4KZ
> USHIFT-457: use cli.Run for executing boilerplate and initializing logs

- ansible/roles/setup-microshift-host/defaults/main.yml
- ansible/roles/setup-microshift-host/tasks/main.yml
- docs/devenv_rhel8.md
- go.mod
- packaging/rpm/microshift.spec
- scripts/devenv-builder/configure-vm.sh
- scripts/devenv-builder/create-vm.sh
- updates go version `go.mod`
- makes necessary changes to dev-env doc & scripts and ansible playbook to work around rhel8.6 not having go1.18 in repos - **these should be reverted when we start using RHEL 8.7**
> USHIFT-494: go1.18

- docs/howto_config.md
- pkg/release/release_amd64.go
- pkg/release/release_arm64.go
Kubernetes moved from k8s.gcr.io to registry.k8s.io in 1.15 via: https://github.com/kubernetes/kubernetes/pull/109938
With old k8s.grc.io, pods failed to start in offline mode since it cannot resolve registry.k8s.io or download the new pause image:
Warning  FailedCreatePodSandBox  10s (x7 over 92s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_ovnkube-master-84dtp_openshift-ovn-kubernetes_cb245daf-ef1d-4610-9f9b-77f7d0af8dc7_0": initializing source docker://registry.k8s.io/pause:3.6: pinging container registry registry.k8s.io: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 192.168.100.1:53: server misbehaving
> USHIFT-497: update pause image to registry.k8s.io

- docs/howto_config.md
- pkg/release/release_amd64.go
- pkg/release/release_arm64.go
Kubernetes moved from k8s.gcr.io to registry.k8s.io in 1.15 via: https://github.com/kubernetes/kubernetes/pull/109938
With old k8s.grc.io, pods failed to start in offline mode since it cannot resolve registry.k8s.io or download the new pause image:
Warning  FailedCreatePodSandBox  10s (x7 over 92s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = error creating pod sandbox with name "k8s_ovnkube-master-84dtp_openshift-ovn-kubernetes_cb245daf-ef1d-4610-9f9b-77f7d0af8dc7_0": initializing source docker://registry.k8s.io/pause:3.6: pinging container registry registry.k8s.io: Get "https://registry.k8s.io/v2/": dial tcp: lookup registry.k8s.io on 192.168.100.1:53: server misbehaving
> Update pause image to registry.k8s.io

- scripts/devenv-builder/create-vm.sh
Update the kickstart filename to include the VM name to ensure it is
unique. This lets the script work better when multiple developers may
be sharing a server.
/assign @ggigaush
/assign @jcope
> update create-vm.sh to support shared systems

- docs/config/microshift-starter.ks
Closes [USHIFT-492](https://issues.redhat.com//browse/USHIFT-492)
> USHIFT-492: Use openshift-client-linux-4.12.0-ec.4 for getting started environment

- assets/components/ovn/master/daemonset.yaml
- pkg/assets/bindata.go
The change to local gateway mode in ovnk needs the activation of ip forwarding for NodePorts and hostPorts to work.
It was only enabled conditionally when br-ex1 additional bridge was configured on the system.
Fixes-Issue: https://issues.redhat.com/browse/USHIFT-502 (cherry picked from commit 3f5bf8e9fab150e1c82702386663919c7e07d80a)
> Fix connectivity issue to NodePorts and router hostPort

- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/controllers/kube-apiserver.go
- pkg/node/kubelet.go
- pkg/util/cryptomaterial/certpaths.go
This PR fixed cert generation for kubelet client cert to use the CSR signer instead of the root CA and uses this same signer to generate the serving cert for it.
/assign @oglok
> AUTH-296: generate kubelet certs properly

- packaging/systemd/configure-ovs.sh
In case VM is using tap/tun device for network connectivity, which is common for user mode networking then `configure-ovs` script fails because it doesn't have tun device support. This patch add supports for these type of device and able to create the bridge network.
Before running configure-ovs script
```
$ nmcli device status
DEVICE  TYPE      STATE      CONNECTION
tap0    tun       connected  tap0
lo      loopback  unmanaged  --
```
After running configure-ovs script
```
$ nmcli connection show
NAME            UUID                                  TYPE           DEVICE
ovs-if-br-ex    2a27fd37-e2b9-45c6-a552-3c5693a85ec0  ovs-interface  br-ex
br-ex           c454eb58-627a-49cb-9cad-d470f5c87b97  ovs-bridge     br-ex
ovs-if-phys0    9e3618f8-b7ac-45cc-bd90-717f03b64cfd  tun …
```
> packaging/systemd/configure-ovs.sh: Add tun device support

- hack/osbuild2copr.sh
- scripts/image-builder/configure.sh
More fixes for [USHIFT-205](https://issues.redhat.com//browse/USHIFT-205)
> USHIFT-205: Clean osbuild-composer cache when switching versions

- pkg/cmd/init.go
- pkg/controllers/etcd.go
- pkg/controllers/kube-apiserver.go
- pkg/util/cryptomaterial/certpaths.go
- pkg/util/cryptomaterial/signers.go
I was not yet able to learn what's important for etcd serving/peer certs so I'm going with minimal config where client certificates only follow the kube CN and O schemes, and serving certificates get their hostnames in DNS/IPs SANs.
The PR is rebased on top of https://github.com/openshift/microshift/pull/970 and can only merge once this one merges.
It's very likely that we may not see any failures in etcd because no peer communication is likely to happen with just one etcd instance. I'll need to test the cert setup with at least 2 etcds or ask someone with the necessary knowledge about how the peer certs should look like.
> AUTH-296: work out etcd certificates

- pkg/cmd/run.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/kube-apiserver.go
Audit logs from kube-apiserver are used in virtually every support engagement with the API team, so they're useful to enable out-of-the-box. I've also removed the audit log path config field, instead using the same path used by OpenShift (under /var/log).
> API-1449: Enable kube-apiserver audit logging.

- docs/howto_config.md
- packaging/microshift/config.yaml
- test/config.yaml
Mop-up for https://github.com/openshift/microshift/pull/1051.
> USHIFT-510: Clean up references to removed auditLogDir option.

- docs/getting_started.md
The link at the top of the Getting Started doc is currently broken. This fixes it.
> fixes link from Getting Started doc to r4e install doc

- docs/howto_config.md
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/cmd/showConfig.go
- pkg/components/components.go
- pkg/components/controllers.go
- pkg/components/networking.go
- pkg/components/storage.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/etcd.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-route-controller-manager.go
- pkg/kustomize/apply.go
- pkg/node/kubelet.go
- test/config.yaml
The three fields ConfigFile, DataDir and Manifests don't need to be user-configurable. Those values should be set to be default values at all time. As a result, those fields can be removed off microshift config to avoid supporting these user-facing configuration in the future.
> USHIFT-500: Remove ConfigFile, DataDir and Manifests fields off MicroShift config

- pkg/components/storage.go
The lvmd file is expected to live in the same path with config file. Previous PR mistakenly changed it to manifests data directory. It's now changed it back to the correct config file directory.
> USHIFT-529: fix(storage): correct lvmd file path

- ansible/roles/configure-firewall/defaults/main.yml
- ansible/roles/install-logging-exporters/templates/cadvisor.service.j2
- ansible/roles/install-logging/defaults/main.yml
- ansible/roles/install-logging/tasks/main.yml
- ansible/roles/install-logging/templates/prometheus.yml.j2
- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/microshift-start/defaults/main.yml
- ansible/roles/microshift-start/tasks/main.yml
- ansible/roles/setup-microshift-host/defaults/main.yml
- ansible/roles/setup-microshift-host/templates/cadvisor.service.j2
- `vnstat` gives us over the wire data metrics.
- `cadvisor` default port was already in use.
- As we split the roles into smaller pieces, some cruft needed to be removed.
> Add support for vnstat metrics to ansible playbooks & slight cleanup

- assets/components/openshift-router/service-internal.yaml
- assets/components/openshift-router/serving-certificate.yaml
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager.go
- pkg/util/cert.go
- pkg/util/cryptomaterial/certpaths.go
- pkg/util/cryptomaterial/trustupdates.go
- scripts/auto-rebase/rebase.sh
This PR does a couple of things in order to be able to finally remove the root CA:
1. generates serving certificates for the KAS
2. fixes the trust for ingress CA which caused the default router cert to be signed by the service-ca
3. removes the root CA and most of the original crypto code as that becomes unused
-----
depends on:
- https://github.com/openshift/microshift/pull/975
- https://github.com/openshift/microshift/pull/981
> AUTH-296: Finish the removal of the root CA

- pkg/controllers/openshift-route-controller-manager.go
external IPs on services should be assigned manually and not automatically in microshift
followup to https://github.com/openshift/microshift/pull/1011#discussion_r1004232794 conversation
> disable ingress-ip controller as we are not allowing configuration of IngressIPNetworkCIDR

- docs/design.md
- pkg/cmd/run.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/node/kubelet.go
- test/config.yaml
Following earlier discussion (https://github.com/openshift/microshift/pull/1011#discussion_r991640607), let's wait to define the configuration surface until split role support arrives.
> USHIFT-533: Remove role (controlplane/node) config.

- pkg/config/config.go
The ingress config doesn't need to be user-configurable. The ingress config will be generated by default.
> USHIFT-539: fix(config): remove user ability to configure ingress config

- packaging/microshift/config.yaml
- pkg/cmd/run.go
- pkg/cmd/showConfig.go
- pkg/config/config.go
- Removes references from sample config file.
- Remove defaulting behavior from ReadAndValidate.
- Don't try to load from file if no config file path is available.
> USHIFT-528: Mop up removal of manifests, configFile, and dataDir config fields.

- scripts/image-builder/config/kickstart.ks.template
This is a developer-friendliness change.
In this way we avoid the need to type the kubeconfig export
every time you switch to the root user.
> Make the kubeconfig file available to root

- assets/components/ovn/configmap.yaml
- docs/howto_config.md
- packaging/microshift/config.yaml
- packaging/systemd/configure-ovs.sh
- pkg/cmd/run.go
- pkg/components/components.go
- pkg/components/networking.go
- pkg/components/render.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/ovn/ovn.go
- pkg/config/ovn/ovn_test.go
- pkg/config/ovn/test/ovn.yaml
- test/config.yaml
Closes [USHIFT-536](https://issues.redhat.com//browse/USHIFT-536)
> USHIFT-536: add user-facing config for ovn-kubernetes CNI

- assets/components/openshift-dns/dns/configmap.yaml
- assets/components/openshift-dns/dns/daemonset.yaml
- assets/components/openshift-router/deployment.yaml
- scripts/auto-rebase/rebase.sh
Small updates to the rebase script and the produced assets to more closely match OCP's deployments.
Closes [USHIFT-421](https://issues.redhat.com//browse/USHIFT-421)
> USHIFT-421: Update manifests to more closely align with OCP

- docs/rhel4edge_iso.md
- scripts/image-builder/config/kickstart.ks.template
As of now generated iso fails to run on the EFI enabled system with following error.
```
Starting automated install.Saving storage configuration...
.Failed to save boot loader configuration
Failed to find a suitable stage1 device: EFI System Partition cannot be of type xfs.; EFI System Partition must be mounted on one of /boot/efi.; EFI System Partition cannot be of type lvmpv.
```
> USHIFT-569: Add efi partition to Image Builder kickstart template

- packaging/systemd/microshift.service
Control shutdown order by declaring the MicroShift service to start Before the kubepods.slice transient systemd unit; this makes system shutdown delay MicroShift shut down until all the pod containers are down. This is important because some services need to talk to the MicroShift API during shutdown (i.e. releasing leader election locks or cleaning up other resources) MicroShift restart or manual stop will not stop the kubepods.
Related-Issue: https://issues.redhat.com/browse/USHIFT-542
> Fix pod/MicroShift systemd services shutdown order

- ansible/roles/install-logging/defaults/main.yml
- ansible/roles/install-logging/files/microshift_perf.json
- ansible/roles/install-logging/files/prometheus_datasource.json
- ansible/roles/install-logging/tasks/main.yml
- ansible/roles/install-logging/templates/grafana_dashboard.json.j2
Adds support for visualizing  Prometheus metrics that we gather from MicroShift in Grafana.
> USHIFT-448: Add prometheus datasource & dashboard to grafana

- ansible/roles/setup-microshift-host/tasks/main.yml
- docs/devenv_rhel8.md
- docs/devenv_rhel8_auto.md
- docs/getting_started.md
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
- Start using beta rhocp-4.12 channel available at OCP mirror site.
- Remove Golang 1.18 workaround as the new version is now available via the RHEL 8.7 channels
- Upgrade documentation references to use RHEL 8.7
- Update puddle repo references to use 4.13 channel
Closes: [USHIFT-495](https://issues.redhat.com//browse/USHIFT-495) and [USHIFT-578](https://issues.redhat.com//browse/USHIFT-578)
> Switch MicroShift devenv to RHEL 8.7 OS and rhocp-4.12 BETA channel

- ansible/README.md
- ansible/roles/configure-firewall/defaults/main.yml
- ansible/roles/install-logging/defaults/main.yml
- ansible/roles/install-logging/tasks/main.yml
- ansible/roles/install-logging/templates/prometheus.yml.j2
- ansible/roles/install-logging/templates/prometheus_datasource.json.j2
Cadvisor also uses port 9090, made a var to set the Prometheus port.
New default Prometheus port updated across configs (including grafana), and set to `9091` which seems to be unused.
> USHIFT-577: Change prometheus port to fix cadvisor conflict

- .gitignore
- ansible/README.md
- ansible/inventory/inventory
- ansible/roles/microshift-start/tasks/main.yml
- ansible/vars/all.yml
The following enhancement were implemented as part of testing:
* Streamlined the documentation flow to let users get to running the benchmark with default params and command line arguments
* Flow tested on devenv and R4E hosts
* Fixed minor problems in the roles to work properly in the devenv / R4E cases
* Added variables for some configuration values to streamline benchmark invocation 
Closes [USHIFT-292](https://issues.redhat.com//browse/USHIFT-292)
> USHIFT-292: Streamline the Ansible documentation for devenv and edge benchmark flows

- docs/howto_config.md
- go.mod
- go.sum
- packaging/microshift/config.yaml
- pkg/cmd/run.go
- pkg/config/config.go
- pkg/config/config_test.go
- test/config.yaml
- vendor/github.com/apparentlymart/go-cidr/LICENSE
- vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
- vendor/modules.txt
Cluster DNS is set to the 10th IP of Service CIDR
> USHIFT-535: Remove dns configurable option from MicroShift config

- docs/rhel4edge_iso.md
- hack/osbuild2copr.sh
Stop using osbuild package from corp for embedded container builds because the right version of the tool is availabe at RHEL 8.7 distribution.
Closes a part of [USHIFT-498](https://issues.redhat.com//browse/USHIFT-498) (rpm-ostree package usage will be fixed when it becomes availabe at RHEL 8.7 distro)
> USHIFT-498: Stop using copr osbuild RPM

- docs/devenv_rhel8.md
- docs/devenv_rhel8_auto.md
- docs/rebase.md
- docs/rhel4edge_iso.md
- pkg/config/config.go
- pkg/node/kubelet.go
- pkg/release/release_arm64.go
- scripts/devenv-builder/config/kickstart.ks.template
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/config/kickstart.ks.template
- Fix docs to remove hard-coded x86_64 mentions and add aarch64 support on RHEL 8.7 OS
- Minor code fixes to error message formatting
- Add aarch64 container image references (all except TopoLVM should work)
- Fix partitioning to split /boot into 200/800MB for efi
Closes [USHIFT-568](https://issues.redhat.com//browse/USHIFT-568)
> USHIFT-568: Apply fixes to code and docs to run on aarch64 platform

- docs/rhel4edge_iso.md
- scripts/devenv-builder/create-vm.sh
- scripts/image-builder/build.sh
- scripts/image-builder/config/ostree-copr.toml
- scripts/image-builder/configure.sh
- scripts/image-builder/create-vm.sh
Minor fixes very necessary, mostly cosmetic:
- Fixed R4E memory allocation to be 3GB
- Make sure pull secret file is readable
- Verify user home directory permissions and umask for Image Builder to work
- Add scripts/image-builder/create-vm.sh script that streamlines R4E VM env setup and creation
- Make sure virt-install is installed
Closes [USHIFT-60](https://issues.redhat.com//browse/USHIFT-60)
> USHIFT-60: Streamline R4E ISO creation on aarch64 platform for AWS environment

- assets/components/openshift-router/deployment.yaml
- scripts/auto-rebase/rebase.sh
revisionHistoryLimit limits the number of old replicaset to 0,
so that there will be no more than one instance of router
replicaset after microshift restart.
> USHIFT-579: eliminate old replicaset of router deployment

- docs/default_cni_plugin.md
pprof is exposed over kubelet unauthenticated healthz endpoint on
port :10248 to localhost only [1], removing MicroShift specific pprof
port document.
[1]: https://github.com/kubernetes/kubernetes/issues/81023
> Remove pprof port reference in CNI doc

- docs/debugging_tips.md
- packaging/rpm/microshift.spec
Ensure the `sos` presence on MicroShift hosts.
Also created [USHIFT-628](https://issues.redhat.com//browse/USHIFT-628) task to follow-up on embedding MicroShift-specific information in the reports generated by the `sos` utility.
Closes [USHIFT-626](https://issues.redhat.com//browse/USHIFT-626)
> USHIFT-626: Install sos utility with MicroShift and document its usage

- Makefile
- packaging/rpm/make-rpm.sh
- packaging/rpm/microshift.spec
```
$ microshift version
MicroShift Version: 4.12.0-20221128123124-8fb675d4
Base OCP Version: 4.12.0-0.nightly-2022-11-22-215931
$ microshift version
MicroShift Version: 4.12.0-20221128123124-8fb675d4-dirty
Base OCP Version: 4.12.0-0.nightly-2022-11-22-215931
```
```
microshift-4.12.0_20221128123124_8fb675d4-1.el8.x86_64.rpm
microshift-networking-4.12.0_20221128123124_8fb675d4-1.el8.x86_64.rpm
microshift-4.12.0_20221128123124_8fb675d4_dirty-1.el8.x86_64.rpm
microshift-networking-4.12.0_20221128123124_8fb675d4_dirty-1.el8.x86_64.rpm
```
> USHIFT-605: Change MicroShift embedded & RPM version scheme

- Makefile
- packaging/rpm/microshift.spec
As a result, `%{version}` given to .spec will be printed out when running `microshift version` command and will match version part of RPM filename.
> USHIFT-645: Pass version from spec to Makefile

- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-controller-manager_test.go
needed for testing the KCM https://issues.redhat.com/browse/WRKLDS-604
It seems to me that log level is passed correctly to the other controllers
> pass log level to KCM

- hack/cleanup.sh
Without this, sometimes part of the container executables
stay running on the system under the kubepods.slice systemd
slice.
> Better cleanup of MicroShift resources for developers

- pkg/components/render_test.go
- pkg/components/storage.go
- pkg/config/config.go
- pkg/config/lvmd/lvmd.go
- pkg/config/lvmd/lvmd_test.go
Closes # [USHIFT-657](https://issues.redhat.com//browse/USHIFT-657)
This PR removes the assumption that the microshift config and the lvmd config are always co-located.  This created a situation where, if a user does not create a microshift config, the search for the lvmd config would short circuit.  This isn't a safe assumption because the microshift default values, used when a user hasn't created a config file, are generally safe for common use cases.  The lvmd config however must usually be defined to describe the host's storage environment, which is probably less uniform with arbitrary volume group names.
This became and issue when the name of the microshift default/example config was changed in the RPM spec, which provided an anchor for the lvmd …
> [BUG] USHIFT-657 MicroShift does not find lvmd config if no microshift config file exists.

- packaging/rpm/microshift.spec
`%{commit}` would get substituted for actual commit SHA in ART pipeline
> Change %{X} to 'X macro' in spec changelog

- validate-microshift/cluster-debug-info.sh
changed execution flow to:
* first register commands to run
* print a "table of contents" so it's obvious what command will be executed and easily searched for
* print a command with `>` prefix and execute the command
By replacing `set -x` with printing the cmd it is now visually clearer and suitable for inclusion in bug tickets (`./validate-microshift/cluster-debug-info.sh > /tmp/cluster.log`)
> USHIFT-660: yet another cluster debug info improvement

- docs/howto_config.md
- pkg/config/config.go
- test/config.yaml
Separate component-specific config and microshift-specific config into 2 sections within top-level config. The components config is modelled after OpenShift config v1 API while microshift config contains fields that are specific to microshift usage.
> USHIFT-607: Introduce a new config format for microshift config

- README.md
- packaging/rpm/microshift.spec
```
$ find _output/rpmbuild/ -name \*.rpm -exec rpm -qi {} \;
Name        : microshift
Version     : 4.12.0_20221207102632_98a2fe03
Release     : 1.el8
Architecture: x86_64
Install Date: (not installed)
Group       : Unspecified
Size        : 117975457
License     : ASL 2.0
Signature   : (none)
Source RPM  : microshift-4.12.0_20221207102632_98a2fe03-1.el8.src.rpm
Build Date  : Wed 07 Dec 2022 10:32:15 AM UTC
Build Host  : microshift-dev.local
Relocations : (not relocatable)
URL         : https://github.com/openshift/microshift
Summary     : MicroShift service
Description :
The MicroShift package provides an OpenShift Kubernetes distribution optimized for small form factor and edge computing.
Name        : microshift-networking
Version     : 4.12.0_20221207102632_98a2fe03
Release     : …
```
> USHIFT-632: Update MicroShift description in RPM

- assets/components/openshift-router/deployment.yaml
- docs/howto_config.md
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/components/render.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/kube-apiserver.go
- pkg/node/kubelet.go
- test/config.yaml
- Re-introduce PR#1030 baseDomain patch
- [USHIFT-664](https://issues.redhat.com//browse/USHIFT-664) Backend logic to baseDomain
> Re-introduce PR#1030 baseDomain patch and add backend logic

- scripts/auto-rebase/rebase.sh
Updates the rebase script to the recent config change separating cluster domain into cluster name and base domain.
> Fix missing change of router manifest

- pkg/controllers/kube-apiserver.go
Default router domain is used to generate router hostname
when neither of host or subdomain is provided. This change
updates the default router domain to be consistent with
the env var ROUTER_DOMAIN in router-default deployment.
> OCPBUGS-4577: Fix default router domain in GenericAPIServerConfig

- assets/components/openshift-router/deployment.yaml
- docs/howto_config.md
- packaging/microshift/config.yaml
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/cmd/showConfig.go
- pkg/components/render.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/kube-controller-manager_test.go
- scripts/auto-rebase/rebase.sh
- test/config.yaml
- test/config_bad_subjectaltnames.yaml
- Groups cluster-, node-, and apiserver-related params.
- Wires-through the cluster-name parameter.
- Updates /etc/microshift/config.yaml.default to reflect the format correctly.
- Removes 'url' field from being user-configurable.
- Fixes a couple of parameter descriptions.
Closes [USHIFT-673](https://issues.redhat.com//browse/USHIFT-673)
> USHIFT-673: Clean up config file format

- scripts/auto-rebase/rebase.sh
This change adds a step to the `rebase.sh to` command to record the
image references used in the rebase. They are saved in the form of
a script that can be used to run the same rebase command again,
which makes it easy to test changes to the rebase script.
/assign @pmtk @fzdarsky
> NOISSUE: save last image references so it is easy to reproduce the rebase

- pkg/cmd/init.go
- pkg/controllers/kube-apiserver.go
- pkg/util/cert.go
The issue happens when MicroShift is restarted, and the keypair used to verify service account tokens is regenerated. At first boot, KAS and KCM will read the content of the initial file and keep that information internally.  After restart, the user agents calling the API server with the private key will be unauthorized because it has changed. 
This PR prevents the regeneration of the key pair.
Closes [USHIFT-667](https://issues.redhat.com//browse/USHIFT-667)
> USHIFT-667: Avoid regenerating keypair for Service Account tokens

- scripts/auto-rebase/rebase.sh
CI jobs script run as nonroot, but repo is cloned as root.
Job can change files' contents freely or even delete files, but it's unable to change permissions of files it doesn't own:
```
chmod: changing permissions of '(...)/last_rebase.sh': Operation not permitted
```
> rebase.sh: remove previous last_rebase.sh

- docs/design.md
This PR is to fix the broken link of enabeld_apis(https://github.com/openshift/microshift/blob/main/docs/enabled_apis.md)
> fix broken link

- scripts/auto-rebase/rebase.sh
Addresses scenario when last_rebase.sh and git commit exits with 1 because there were no files to commit
```
Switched to a new branch 'rebase-4.12.0-0.nightly-2022-12-23-190941'
On branch rebase-4.12.0-0.nightly-2022-12-23-190941
nothing to commit, working tree clean
Script exited with error.
Script exited with error.
```
> rebase.sh: don't fail if last_rebase.sh didn't change

- pkg/controllers/cluster-policy-controller.go
- pkg/controllers/kube-scheduler.go
- pkg/controllers/openshift-crd-manager.go
- pkg/controllers/openshift-default-scc-manager.go
- pkg/controllers/version.go
- pkg/mdns/routes.go
- pkg/mdns/server/resolver.go
- pkg/mdns/server/server.go
- pkg/util/net.go
- pkg/util/sigchannel/sigchannel.go
I'm suspecting that changing CI image from `rhel-8-release-golang-1.18-openshift-4.12` to `rhel-8-release-golang-1.19-openshift-4.13` (note the golang change) change gofmt's behavior
> Fix formatting after changing CI's image to go1.19

- scripts/auto-rebase/create_pr.py
- scripts/auto-rebase/rebase_job_entrypoint.sh
Because steps in "steps registry" are shared between branches I'd like to move rebase's commands.sh contents into microshift repository so that changes to the job are contained to specific branch.
Otherwise, when introducing rebase.py (wrapper for rebase.sh with extra goodies, will obsolete create_pr.py) will need either introducing into 4.12 branch (and I'd like to run in on main first, as a testing area) or special login in step's commands.sh.
> OCPBUGS-5537: USHIFT-601 rebase: entrypoint and create_pr.py

- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
Start using officially released and supported TopoLVM 4.12.0-2 image from registry.redhat.io
Closes [USHIFT-609](https://issues.redhat.com//browse/USHIFT-609)
> USHIFT-609: Upgrade TopoLVM image to v4.12.0-2

- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
Merge #1259 
Closes OCPBUGS-5907
> OCPBUGS-5907: Cherrypick 4.12: Upgrade TopoLVM image to v4.12.0-2

- cmd/microshift/main.go
- pkg/cmd/get.go
Expose the embedded 'kubectl get' command for use in greenboot and
sos.
> USHIFT-781: add 'get' command line client

- docs/devenv_rhel8.md
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
The 4.13 channels are not yet available, while rhocp-4.12-beta channels no longer work.
Closes OCPBUGS-6080
> OCPBUGS-6080: Use rhocp-4.12 release channel for OCP dependencies

- assets/components/openshift-dns/dns/configmap.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/node/kubelet.go
- scripts/auto-rebase/rebase.sh
systemd-resolved conf is used by kubelet as alternative
dns resolver when exists. This commit aligns the DNS
Corefile conf with kubelet resolvConf when default
systemd-resolved config is detected.
> NP-660: use systemd-resolved in CoreDNS configmap

- docs/config/nginx-IP-header.yaml
- docs/howto_load_balancer.md
**Which issue(s) this PR addresses**: #1290 
Closes #1290
> Update MetalLB how to with instructions for k8s 1.25+

- scripts/auto-rebase/rebase.sh
DNS's configmap.yaml is owned by MicroShift (it's a file that would be generated by the operator)
> USHIFT-791: Rebase: don't change Corefile in DNS's ConfigMap

- scripts/auto-rebase/rebase.py
- Allow for using Personal Access Token (PAT) to test against a developer's fork (`TOKEN` env var)
- Add information about `rebase.sh` execution time
- Allow to override `base_branch` so the PR can be created against `main` when script is executed from other branch, not yet existing on the remote (`BASE_BRANCH` env var)
- Don't crash on "review request" failures
- Use more precise prefix to pick branches for deletion (`rebase-4`)
- Delete temporary remote at the end of script, so next time it's executed on dev machine git doesn't have old remote refs.
Usage:
```
TOKEN=ghp_... \
BASE_BRANCH=main \
ORG=pmtk \
REPO=microshift \
AMD64_RELEASE="registry.ci.openshift.org/ocp/release:4.13.0-0.nightly-2023-01-24-061922" \
ARM64_RELEASE="registry.ci.openshift.org/ocp-arm64/release-arm64:4.13.0-0.ni …
```
> USHIFT-816: rebase.py - personal tokens

- packaging/rpm/microshift.spec
- packaging/systemd/firewalld-no-iptables.conf
Disables firewalld access to iptables related nftables translator,
this avoids firewalld flush of iptables under any circumstance,
firewalld will work at nftables level, while MicroShift/OVN can
continue to work at iptables level (translated to nft) under the hood.
> NP-641: Avoid firewalld flush of iptables

- pkg/components/networking.go
GetConfigFile() may return empty path or user defined path, but ovn config file is only supported under /etc/microshift
> OCPBUGS-7056: fix ovn config file path

- pkg/util/net.go
In OCP, we always use the same IP as OVN-K gateway and kubelet node IP. We shall do the same thing for microshift.
> NP-646: Prefer OVN-K gateway IP as the nodeIP

- assets/components/ovn/clusterrole.yaml
- assets/components/ovn/clusterrolebinding.yaml
- assets/components/ovn/configmap.yaml
- assets/components/ovn/master/daemonset.yaml
- assets/components/ovn/node/daemonset.yaml
- assets/components/ovn/node/serviceaccount.yaml
- assets/components/ovn/role.yaml
- assets/components/ovn/rolebinding.yaml
- pkg/components/networking.go
Related-Issue: https://issues.redhat.com/browse/NP-648
> Revert single pod ovnk

- packaging/rpm/microshift.spec
Closes [OCPBUGS-6858](https://issues.redhat.com/browse/OCPBUGS-6858)
> OCPBUGS-6858: Add minimum CRIO version as rpm requirement

- scripts/image-builder/build.sh
Prevent conflicts with MicroShift RPMs from rhocp repo when building ISO images.
Closes OCPBUGS-7124
> OCPBUGS-7124: Delete microshift RPM files from rhocp repo when building ISO images

- docs/howto_firewall.md
- scripts/devenv-builder/configure-vm.sh
multicast dns query will be rejected by firewalld if not enabled
Related-Issue: https://issues.redhat.com/browse/OCPBUGS-6862
> Add mdns service in firewalld

- packaging/rpm/microshift.spec
Signed-off-by: Ricardo Noriega [rnoriega@redhat.com](mailto:rnoriega@redhat.com)
Which issue(s) this PR addresses:
Closes #[OCPBUGS-7139](https://issues.redhat.com/browse/OCPBUGS-7139)
We are using a minimum requirement for CRIO, assuming the release team will only provide the CRIO version according to the OCP requirements of that release.
> OCPBUGS-7139: Add minimum CRIO version as rpm requirement for MicroShift 4.12

- etcd/cmd/microshift-etcd/run.go
- hack/cleanup.sh
- pkg/controllers/etcd.go
This is the first step to get etcd running un-bundled from MicroShift; this change makes etcd run in a transient systemd unit whose lifetime is bound to the MicroShift execution. Also, as a temporary measure, I added a subcommand to MicroShift that just runs the bundled etcd; this is so we can test etcd's execution with the systemd unit and this will be removed and replaced by an invocation of the etcd binary that will be laid down by an rpm.
The end goal, as described in this [Microshift Enhancement](https://github.com/openshift/enhancements/pull/1242) is to remove the current embedded etcd service and replace it with a service that launches etcd in a transient systemd unit.
> ETCD-319: adding transient systemd unit for etcd

- docs/howto_firewall.md
- scripts/devenv-builder/configure-vm.sh
Related-Issue: https://issues.redhat.com/browse/OCPBUGS-6862
> optionally enable mdns service in firewalld

- scripts/auto-rebase/rebase.sh
'+' is used in GitHub as a character for joining filters in query and breaks prow.ci.openshift.org PR search
> NO-ISSUE: fix rebase branch name for GH query

- scripts/auto-rebase/rebase.sh
Instead of parsing the image name to find the version and date, use
the image data we have already extracted.
> USHIFT-790: always take image version from content when rebasing

- docs/howto_config.md
- pkg/cmd/init.go
- pkg/cmd/run.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/kube-apiserver.go
- pkg/node/netconfig.go
> USHIFT-716: add configurable KAS advertise address

- docs/network/default_cni_plugin.md
- docs/network/host_networking.md
`firewall --reload` won't flush iptable rules after the fix: https://github.com/openshift/microshift/pull/1300
> OCPBUGS-7444: remove firewall known issue in the doc

- scripts/auto-rebase/rebase.sh
Ensure the namespace is set for namespace-scoped manifests when
copying them.  Copy the cluster-scoped manifests without modifying
them.
Running this using last_rebase.sh produced minimal changes in indentation
in the LVMS manifests.
> USHIFT-870: do not require kubeconfig to run rebase script

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_role.yaml
- assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_rolebinding.yaml
- assets/components/lvms/topolvm-lvmd-config_configmap_v1.yaml
- assets/components/lvms/topolvm-node-securitycontextconstraint.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
- assets/components/lvms/topolvm-openshift-storage_namespace.yaml
- assets/components/openshift-dns/dns/daemonset.yaml
- assets/components/openshift-dns/dns/service.yaml
- assets/components/openshift-router/deployment.yaml
- assets/components/service-ca/deployment.yaml
- pkg/components/render.go
- pkg/components/render_test.go
- pkg/components/storage.go
- scripts/auto-rebase/assets.yaml
- scripts/auto-rebase/handle-assets.py
- scripts/auto-rebase/rebase.sh
- scripts/devenv-builder/configure-vm.sh
Adds asset.yaml that lists all the files in `assets/`. Focused only on sourcing the assets (either copying from `STAGING_DIR` or using `git restore`). It does not include any modifications (like yq) to the manifests (yet).
Its purpose is to have common place for both rebase procedure and rebase presubmit.
Introduces new way of copying manifests from staging dir based on contents of assets.yaml file.
Commands such as `cp`, `git restore`, `rm -rf` are removed from `rebase.sh`'s functions dealing with manifests (`assets/`).
Other changes include:
- wrapping `{{ .template  }}` inside quotes to get correct yaml file, so many `sed` commands are removed
- formatting lvms/topolvm manifests with `oc create --dry-run=client` (includes sorting) (a consequence of using `oc create --dry-run` on all …
> USHIFT-852: assets.yaml declaring manifests to copy from releases

- assets/components/openshift-dns/dns/configmap.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/node/kubelet.go
- scripts/auto-rebase/rebase.sh
systemd-resolved conf is used by kubelet as alternative dns resolver when exists. This commit aligns the DNS Corefile conf with kubelet resolvConf when default systemd-resolved config is detected.
Co-authored-by: Miciah Dashiel Butler Masters <mmasters@redhat.com>
(cherry picked from commit 24ae57ee616e7ccdb4298c6f159ae5442bc87abc)
> OCPBUGS-6785: Use systemd-resolved in CoreDNS configmap

- docs/network/default_cni_plugin.md
ovn-kubernetes doesn't restrict the host addresses where
k8s nodeport service can be accessed from outside microshift
node, this commit adds nftable instructions to drop packet
matching the nodeport and host interface IPs. These nftable
instructions can work regardless of firewalld service state.
> NP-621: add doc for nodeport host addresses

- packaging/rpm/microshift.spec
The /etc/microshift/manifests empty directory is created when installing RPMs
Closes OCPBUGS-6859
> OCPBUGS-6859: Create empty manifest directory when installing MicroShift

- assets/components/ovn/master/daemonset.yaml
- docs/network/default_cni_plugin.md
- docs/network/host_networking.md
- docs/network/ovn_kubernetes_traffic_flows.md
- pkg/config/ovn/ovn.go
OVNKubernetes builds overlay networking implementation based on geneve
tunnel which adds extra header for packets coming from overlay (Pod) to
underlay network. However, the geneve tunnel is only useful for
cross-nodes communication and not required for microshift single node
deployment. This PR leverages the single-node change[1] in OVNKubernetes
and updates the default overlay MTU to the same size as default uplink
MTU (1500).
[1]: https://github.com/ovn-org/ovn-kubernetes/pull/3290
> NP-603: default to system mtu in ovnk

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-node-metrics_v1_service.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
Closes #[USHIFT-851](https://issues.redhat.com//browse/USHIFT-851)
> USHIFT-851 remove references to lvms-operator/provisioner in manifests

- docs/devenv_setup.md
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
Switch to using OCP mirror site for 4.13 RPM dependencies.
The following testing was performed:
- Reconfiguring and testing the current RHEL 8 x86 devenv
- Creating x86 RHEL 8/9 devenv machines from scratch and making sure the devenv procedures work
- Creating x86 RHEL 8/9 ISO images and making sure they install and run properly
Closes [USHIFT-691](https://issues.redhat.com//browse/USHIFT-691)
> USHIFT-691: Configure RPM dependencies to use packages from OCP 4.13 beta mirror site

- scripts/image-builder/build.sh
Tested ISO image creation and boot using build.sh script on RHEL 8 x86.
Closes [USHIFT-910](https://issues.redhat.com//browse/USHIFT-910)
> USHIFT-910: Remove redundant coreos package deletion from build.sh

- pkg/config/ovn/ovn.go
- pkg/mdns/controller.go
> OCPBUGS-7205: don't advertise ovn-kubernetes local addresses in mdns

- scripts/devenv-builder/config/kickstart.ks.template
- scripts/image-builder/config/kickstart.ks.template
Closes [USHIFT-896](https://issues.redhat.com//browse/USHIFT-896)
> USHIFT-896: Enable activations of all ethernet interfaces in kickstart

- scripts/devenv-builder/config/kickstart.ks.template
- scripts/image-builder/config/kickstart.ks.template
Use UUID instead of names in the command to make it work for device names with spaces
Closes [USHIFT-896](https://issues.redhat.com//browse/USHIFT-896)
> USHIFT-896: Use UUID for enabling automatic network device connections in kickstart

- docs/devenv_setup.md
- docs/devenv_setup_auto.md
- scripts/devenv-builder/configure-vm.sh
Closes [USHIFT-912](https://issues.redhat.com//browse/USHIFT-912)
> USHIFT-912: Fix 4.13 devenv installation instructions to only use RHEL / CentOS 9.x

- assets/components/openshift-router/configmap.yaml
- pkg/components/controllers.go
- scripts/auto-rebase/rebase.sh
The data of openshift-ingress service-ca-bundle configmap is erased everytime when microshift starts since the configmap is applied without data. This results in delay in starting router-default deployment pod after reboot as it has to wait for service-ca controller to inject the ca-bundle again. This commit applies service-ca-bundle configmap directly with data generated in service-ca dir.
> OCPBUGS-7779: apply service ca-bundle directly to ingress configmap

- scripts/image-builder/config/kickstart.ks.template
Implement a solution for enabling secondary network interfaces in kickstart. 
Using `ncli connection modify` command does not update the configuration file when run in post install. As a workaround, edit the configuration files by removing `autoconnect=.*` option from them.
Closes [USHIFT-896](https://issues.redhat.com//browse/USHIFT-896)
> USHIFT-896: Fix kickstart to edit autoconnect option in the configuration files

- scripts/auto-rebase/rebase_job_entrypoint.sh
This reverts commit 3570ead6e36cfc5def9d6b01bdc6908ea69c6e29.
/assign @pmtk
> USHIFT-289: Revert "change names of rebase image configmaps"

- etcd/cmd/microshift-etcd/run.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- pkg/config/config.go
- pkg/config/config_test.go
This is the implementation for the 'defrag goroutine' approach from [this enhancement](https://github.com/openshift/enhancements/pull/1350)
> ETCD-352: Adding etcd defrag goroutine

- scripts/auto-rebase/rebase_patches/0003-disable-clusterQuotaMapping-controller.patch
- scripts/auto-rebase/rebase_patches/0004-remove-config-informer.patch
- scripts/auto-rebase/rebase_patches/0005-remove-user-informer.patch
- vendor/k8s.io/kubernetes/openshift-kube-apiserver/openshiftkubeapiserver/patch.go
Remove startup code that adds the resource quota controller and informers
for the Group and User APIs, because none of the relevant APIs are
present in MicroShift.
/hold
> OCPBUGS-2869: patch out unused components in openshift-kube-apiserver

- scripts/auto-rebase/get-ci-token.sh
The script uses the token from the console web app to login and get
the pull secret value for the CI registry, then prints it to the
screen to be copied and pasted into ~/.pull_secret.json
> NO-ISSUE: add developer tool for getting CI pull secret

- packaging/crio.conf.d/microshift_amd64.conf
- packaging/crio.conf.d/microshift_arm64.conf
openshift pod image places pause exec under /usr/bin/pod while the default path for pause exec is set to "/pause".
> OCPBUGS-7874: set the pause exec path for openshift pod image

- go.mod
- pkg/cmd/run.go
- pkg/loadbalancerservice/controller.go
With this new controller and OVN-K, microshift is able to support k8s services of loadblancer type. The controller is responsible for updating the status.loadBalancer with the node ip and hostname of the local host. OVN-K is responsible for adding the iptables rules accordingly.
> NP-604: Add loadbalancer service controller

- docs/howto_config.md
- packaging/microshift/config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
#1395 Added etcd configuration to the internal Microshift config structure, but not the user-facing configuration. This PR adds the etcd config to the user-facing configuration file.
> ETCD-401: Adding etcd config to user-facing config

- ansible/roles/install-logging/defaults/main.yml
- ansible/roles/install-logging/tasks/main.yml
- ansible/roles/manage-repos/defaults/main.yml
- ansible/roles/manage-repos/tasks/main.yml
- ansible/roles/manage-repos/templates/ocpbeta.repo.j2
- ansible/roles/setup-microshift-host/defaults/main.yml
- ansible/roles/setup-microshift-host/tasks/main.yml
- Hack to fix URI module for grafana manipulation
- Add OCP beta mirror repo for 4.13
- Add go 1.19 to build for 4.13
- Small spacing changes
- Reorder package installation and add package for RHEL9 prereqs
> USHIFT-938: Ansible RHEL9 & 4.13 changes

- pkg/config/config.go
While hostnames may have whatever case is desired by the user, resources in kubernetes must be lower case. Node name was directly copied from the hostname, resulting in upper case characters, if any. This prevents creation of the node and many other interactions between kubelet and apiserver.
> OCPBUGS-8411: Use lower case node names only

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
TopoLVM on MicroShift suffers flakey behavior that stems in part from a race window with the service-ca.  This PR pads TopoLVM's startup time to give the service-ca a chance to issue certs.  This PR sets the initial startupProbe values to a 5 minute timeout (30 retries at 10 second intervals).
The race window was exposed by flakey behavior with service-ca startup that is being addressed separately.  The work there will reduce the scale of the race window, however it will still be present.  The window appears during (re)boot because topolvm depends on the service-ca to issue cert. In this scenario, topolvm and service-ca are started concurrently; their boot order is not controlled by microshift. This means that both services' retry loops are initiated at the same time, so the diff between …
> OCPBUGS-6861: Allow TopoLVM initial grace period while service-ca attempts to start

- docs/getting_started.md
The link for a "no-cost Red Hat Developer subscription" was improperly formatted and did not render properly.
> NO-ISSUE: Correct markdown link error in Getting Started doc

- pkg/util/net.go
There is no need to log the gateway IP address every time we look it
up, so only log it when it changes. This is somewhat redundant to the
logic in the controller itself, but the IP returned from GetHostIP()
is not always the gateway IP and GetHostIP() may have other callers.
This change also rewords another log message related to how the host
IP is being selected to make it clear what effect the failure to find
a default route has on the outcome.
> OCPBUGS-8329: update sysconfwatch-controller logging

- docs/config/busybox_running_check.sh
- docs/greenboot_dev.md
Closes [USHIFT-737](https://issues.redhat.com//browse/USHIFT-737)
> USHIFT-737: Fix user workload greenboot verification to check for 1 pod

- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/util/net.go
- pkg/config/config.go
getAllHostnames is meant to run once on startup to help populate
configuration. In the test suite it may run many times, and it
occasionally blocks looking up the FQDN for hosts. This change caches
the first set of results to avoid blocking on future calls and to make
the tests run more quickly. This change is safe because MicroShift
should be restarted (automatically or by the user) if the network
settings of the host change in a significant way.
> USHIFT-949: cache getAllHostnames

- pkg/kustomize/apply.go
Closes OCPBUGS-8425
Example of a failed run, which backs off after 1m of retries, logs an error and proceeds.
```
kustomizer I0312 18:30:20.289488  180399 manager.go:114] Starting kustomizer
kustomizer I0312 18:30:20.289524  180399 apply.go:64] No kustomization found at /usr/lib/microshift/manifests/kustomization.yaml
kustomizer I0312 18:30:20.289532  180399 apply.go:57] Applying kustomization at /etc/microshift/manifests/kustomization.yaml 
kustomizer I0312 18:30:20.738705  180399 apply.go:71] Applying kustomization failed: accumulating resources: accumulating resources from 'busybox.yaml': MalformedYAMLError: yaml: line 20: could not find expected ':' in File: busybox.yaml. Retrying in 10s.
kustomizer I0312 18:30:30.790331  180399 apply.go:71] Applying kustomization failed: accumulating …
```
> OCPBUGS-8425: Fix the kustomization procedure not to exit with fatal error

- docs/howto_firewall.md
- docs/network/host_networking.md
- docs/network/ovn_kubernetes_traffic_flows.md
- pkg/config/config.go
> OCPBUGS-8277: Use a different internal IP for apiserver connectivity

- docs/openshift_ci.md
- pkg/cmd/init.go
> OCPBUGS-8301: Use correct CAs in kubeconfig files

- packaging/rpm/make-rpm.sh
Use 8 threads parallelization with the same compression algorithm.
Results in a dev machine with 3 cores:
Before optimization
$ time make rpm
real	1m57.313s
user	2m0.536s
sys	0m5.801s
After optimization
$ time make rpm
real	0m25.741s
user	0m30.174s
sys	0m5.869s
> USHIFT-956: optimize rpm build time

- README.md
- docs/devenv_cloud.md
- docs/devenv_setup.md
- docs/greenboot_dev.md
- docs/network/ovn_kubernetes_traffic_flows.md
All except Getting Started document, which will be handled in a separate PR
Closes [USHIFT-960](https://issues.redhat.com//browse/USHIFT-960)
> USHIFT-960: Replace RHEL 8 references by RHEL 9 references

- scripts/jira/cloner.py
Python tool to automate bug handling:
- Checks Fix versions and mismatches for original and cloned bugs.
- Checks Target version mismatches with Fix versions.
- Checks gaps in Target version against Fix versions and creates clones for those that are not present.
- Automatically creates blocks links between clones and originals.
- Automatically synchronize clones with originals for Fix versions.
- Alert about manual actions required, such as setting Target version/Fix versions.
> NOISSUE: Add jira auto clone tool to scripts

- packaging/greenboot/functions.sh
In case of an invalid input, the following messages will be logged.
```
Could not parse MICROSHIFT_WAIT_TIMEOUT_SEC value 'Abc': using '300' instead
GREENBOOT_MAX_BOOTS value '35' is not in the [1..9] range: using '3' instead
```
Closes [USHIFT-979](https://issues.redhat.com//browse/USHIFT-979)
> USHIFT-979: Sanitize the values of wait timeout and max boots from greenboot.conf

- scripts/release-notes/gen-ec-release-notes.py
Update the URL where we look for preview releases for RHEL 9 builds
and update some of the progress messages to be more informative.
> NO-ISSUE: update the release note generator script for RHEL 9

- docs/default_csi_plugin.md
- pkg/components/render.go
- pkg/components/storage.go
- pkg/config/lvmd/lvmd.go
- pkg/config/lvmd/lvmd_test.go
Instead of requiring the user to configure their system with a "rhel"
volume group, look at the volume groups that exist and pick one as the default. If there is only 1, use it. If there is a "microshift" VG, use it. Otherwise, disable the CSI driver.
/assign @copejon
> OCPBUGS-9996: make lvms configuration more robust

- assets/components/ovn/master/daemonset.yaml
- assets/components/ovn/node/daemonset.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- scripts/auto-rebase/rebase.sh
(cherry picked from commit f0585c67818cfe9fe2b68bfe9cb4581f520bb0a8)
> [release-4.13] OCPBUGS-10532: update ovn-kubernetes to rhel9 based image

- ansible/roles/microshift-start/tasks/main.yml
`network.txt` output will reflect accurate vnstat network transfer metric across RHEL8/9.
> PERFSCALE-2109: Bugfix wait for vnstat db to populate before recording output

- packaging/greenboot/functions.sh
- packaging/greenboot/microshift-pre-rollback.sh
- packaging/greenboot/microshift-running-check.sh
* Introduce print_boot_status function to properly print variables from all the scripts
* Fix error redirection in the get_wait_timeout function
Closes:
[USHIFT-985](https://issues.redhat.com//browse/USHIFT-985)
[USHIFT-990](https://issues.redhat.com//browse/USHIFT-990)
> Fix greenboot script errors when variables are specified in /etc/greenboot/greenboot.conf file

- ansible/README.md
- ansible/inventory/inventory
- ansible/roles/add-kubelet-logging/defaults/main.yml
- ansible/roles/add-kubelet-logging/files/metrics-sa.yaml
- ansible/roles/add-kubelet-logging/tasks/main.yml
- ansible/roles/configure-firewall/defaults/main.yml
- ansible/roles/create-service-account/defaults/main.yml
- ansible/roles/create-service-account/tasks/main.yml
- ansible/roles/create-service-account/tasks/metrics-sa.yaml
- ansible/roles/install-logging-exporters/defaults/main.yml
- ansible/roles/install-logging-exporters/tasks/main.yml
- ansible/roles/install-logging/templates/prometheus.yml.j2
- ansible/roles/microshift-start/tasks/main.yml
- ansible/setup-node.yml
- Make external cadvisor process conditional
- Create role to create metrics service account
- Add firewall port for kubelet endpoint
- Create role to modify prometheus config
- Fix file location in microshift-start
- Append kubelet endpoint to prometheus config in playbook
> PERFSCALE-2108: Enable logging for Microshift built-in kubelet metrics

- docs/config/microshift-starter.ks
- docs/devenv_setup.md
- scripts/devenv-builder/config/kickstart.ks.template
Works around OCPBUGS-10766 by not appending .local domain suffix when creating MicroShift VMs. 
Users can explicitly specify an FQDN, which has to be resolved properly.
> OCPBUGS-10766: Stop using .local domain suffix in the MicroShift VMs

- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-scheduler.go
- pkg/node/kubelet.go
- pkg/util/net.go
Includes http client configuration instead of changing global http package variables.
> USHIFT-1008: Justify why healthz endpoints are not TLS verified

- docs/devenv_setup.md
- docs/rhel4edge_iso.md
- packaging/images/openshift-ci/Dockerfile.test-runtime
- scripts/auto-rebase/get-ci-token.sh
- scripts/auto-rebase/rebase.sh
- scripts/devenv-builder/configure-vm.sh
- scripts/devenv-builder/create-vm.sh
- scripts/image-builder/configure.sh
After this fix the following /tmp references remain:
```
$ grep -rn /tmp scripts/ hack/ docs/ packaging/ validate-microshift/ | grep -v mktemp
scripts/image-builder/cleanup.sh:60:    sudo rm -rf /tmp/containers/* 2>/dev/null || true
docs/debugging_tips.md:45:The report archives can be found in the `/var/tmp/sosreport-*` files.
docs/debugging_tips.md:48:$ sudo ls -tr /var/tmp/sosreport-* | tail -2
docs/debugging_tips.md:49:/var/tmp/sosreport-host0-2022-11-24-pvbcaji-obfuscated.tar.xz
docs/debugging_tips.md:50:/var/tmp/sosreport-host0-2022-11-24-pvbcaji-obfuscated.tar.xz.sha256
docs/debugging_tips.md:58:sudo rm -f /var/tmp/sosreport-*
docs/rhel4edge_iso.md:27:- The user `~/.cache` and `/tmp/containers` directory contents are deleted to clean various cache files
```
Closes …
> USHIFT-1011: Fix the usage of predictable file names in /tmp

- pkg/cmd/init.go
- pkg/controllers/kube-apiserver.go
In order to avoid DNS configuration unless there is no other way, try using external and internal IPs to reach kubelet from apiserver. This allows having whatever hostname+domain name combinations without trying to resolve the name externally.
To allow this we need to include the node IP in the kubelet certificate as this is what the apiserver will target.
> OCPBUGS-10766: Change apiserver preferred addresses

- OWNERS
Since we are now running the team with core members, OCTO disengaged and there are only a few collaborations with other teams, we reduce the scope of the reviewers to the core members while keeping them in emeritus approvers for a second informed opinion if there is a need This way we avoid spamming folks who have no time to devote to MicroShift and we also dont slow down PR merge flow.
> NO-ISSUE: Modify OWNERS

- scripts/image-builder/config/kickstart.ks.template
Partially reverting #1568 to allow password-less sudo in R4E images. This is required for QE pipeline.
Closes [USHIFT-1007](https://issues.redhat.com//browse/USHIFT-1007)
> Allow password-less sudo in the R4E images

- pkg/cmd/run.go
When the certificates are about to expire MicroShift restarts to regenerate
them. This change introduces an extra goroutine to watch for that event
specifically and log a message explaining the restart. It then propagates
the shutdown by canceling the main context used by everything else to know
when to shutdown.
> USHIFT-591: log when exiting due to certificate rotation

- pkg/components/storage.go
Oneliner to make the warning log line render the error message.
> Fix LVM-not-detected log rendering

- docs/devenv_setup.md
- packaging/rpm/microshift.spec
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/configure.sh
* Switch the development environment to use RHEL 9.2 beta
* Enable osbuild configuration to use RHEL 9.2 beta channels
* Use golang that comes with the OS
* Fix the golang dependency in the MicroShift RPM spec file
Closes:
* [USHIFT-1023](https://issues.redhat.com//browse/USHIFT-1023)
* [OCPBUGS-10472](https://issues.redhat.com//browse/OCPBUGS-10472)
> Start using RHEL 9.2 in the devenv and edge

- Makefile
- etcd/vendor/github.com/openshift/microshift/pkg/util/cert.go
- hack/verify-vendor-etcd.sh
As we make changes to code in microshift that is vendored into etcd, we
need to ensure that we also update the vendored copy at the same time.
This change adds a Makefile target `vendor-etcd` that updates the
`etcd/vendor` directory and another target `verify-vendor-etcd` that fails
if there are any files added or modified after running `make vendor-etcd`.
> USHIFT-950: add verification step to ensure etcd/vendor is kept up to date

- docs/howto_config.md
- etcd/cmd/microshift-etcd/run.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- packaging/microshift/config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controllers/etcd.go
To simplify the configuration, this PR reverts the changes made by #1435. Also, this sets the maximum on-disk quota for etcd to be the maximum allowed (and aligned with Openshift) as the default to reduce the likelihood that a customer will hit the quota during runtime.
> ETCD-403: Revert user configuration for etcd and change default max quota

- scripts/verify_images.sh
* add registry.redhat.io/lvms4/ to allowed image locations
The LVMS images are published 'lvms4' instead of 'odf4' now that the
project has been renamed.
* exit with error if an image does not match accepted pattern
Restructure the script so the while loop does not end up in a sub-shell, so
the `approve` variable value is remembered after the loop. This allows the
script to exit with an error when an image is found from an unaccepted
source.
/assign @eggfoobar
> USHIFT-1044: fix image verification test

- packaging/rpm/microshift.spec
Aligns the build and install time selinux minimum versions.
> OCPBUGS-11374: RPM: Match build and install time min versions

- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/files.go
- pkg/components/networking.go
- pkg/components/storage.go
- pkg/config/files.go
Simplify the configuration approach by removing the search in multiple
places for a configuration file. Use only the file in
/etc/microshift/config.yaml.
> USHIFT-662: remove user directory configuration file

- scripts/image-builder/configure.sh
> OCPBUGS-11564: Explicitly install runc before building ISO images

- .hadolint.yaml
- Makefile
- packaging/images/openshift-ci/Dockerfile.test-runtime
- scripts/fetch_tools.sh
Closes https://issues.redhat.com/browse/USHIFT-1050
This PR adds [hadolint](https://github.com/hadolint/hadolint) as a linter for Dockerfiles and Containerfiles
> USHIFT-1050:  Add hadolint : Linter for Dockerfiles and Containerfiles

- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/etcd.go
- pkg/config/config_test.go
- pkg/config/etcd.go
The memory limit floor of 50mb was too low and was causing issues in testing, this PR raises this minimum valid value to 128mb to resolve this issue.
> OCPBUGS-11592: increase etcd memory limit floor

- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- pkg/config/config.go
This is a manual backport of #1647 since the configuration refactor was not backported.
> OCPBUGS-11497:increase etcd memory limit floor

- scripts/fetch_tools.sh
* Set `textrel_shlib_t` SELinux context to prevent `hadolint` crash.
* Optimize the script to explicitly declare `tmp` variable in the global scope and rename it to `WORK_DIR`
Closes [USHIFT-1050](https://issues.redhat.com//browse/USHIFT-1050)
**Context**
`hadolint` executable is statically linked and it causes the following errors on some systems when SELinux is enabled.
> Apr 11 06:30:57 microshift-dev-rhel92 setroubleshoot[32487]: SELinux is preventing /home/microshift/microshift/hadolint-Linux-x86_64 from execmod access on the file /home/microshift/microshift/_output/bin/hadolint.#012#012*****  Plugin allow_execmod (53.1 confidence) suggests   *********************#012#012If this issue occurred during normal system operation.#012Then this alert could be a serious issue and your system …
> USHIFT-1050: Set textrel_shlib_t SELinux context on hadolint static executable

- assets/components/ovn/master/daemonset.yaml
- assets/components/ovn/node/daemonset.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
ovn-kubernetes-microshift-rhel-9 has been renamed to ovn-kubernetes-microshift in 4.14 release payload via https://github.com/openshift/release/pull/37816
> OCPBUGS-11635: rename ovn-kubernetes-microshift image

- etcd/vendor/github.com/openshift/microshift/pkg/config/kubeconfig.go
- pkg/cmd/init.go
- pkg/cmd/init_test.go
- pkg/config/kubeconfig.go
Remove any kubeconfig that is not part of the hostname or SAN values in configuration.
> OCPBUGS-11395: Remove stale kubeconfigs

- packaging/rpm/microshift.spec
Minimal openvswitch version required by ovn-kubernetes in rhel9.2(4.14) is openvswitch3.1.
> OCPBUGS-11538: upgrade openvswitch package version for 4.14

- packaging/rpm/microshift.spec
openvswitch3.1 is required by rhel9.2 by both
4.13 & 4.14 releases
> OCPBUGS-11538: Fix rpm spec history for ovs version upgrade

- etcd/vendor/github.com/openshift/microshift/pkg/config/debugging.go
- pkg/config/debugging.go
- pkg/config/debugging_test.go
Don't require the user to capitalize the log level name correctly.
> USHIFT-1043: ignore case when looking at logging level

- cockpit-plugin/packaging/config-openapi-spec.json
- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/files.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
- packaging/microshift/config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/files.go
- pkg/config/manifests.go
- pkg/kustomize/apply.go
Add a configuration option to control the directories scanned for
kustomization.yaml files.
/assign @eggfoobar
> USHIFT-974: make the kustomize paths configurable

- scripts/image-builder/build.sh
Authorised keys generated by `yubikeys` used `;` character in the contents. 
Changing to the `^` separator in the `sed` command to make the command more robust.
> NO-ISSUE: Make authorized keys content replacement more robust in build.sh

- scripts/auto-rebase/assets.yaml
> USHIFT-1229: fix the location of kube-apiserver configuration assets

- .pylintrc
- scripts/release-notes/gen_ec_release_notes.py
- scripts/verify/verify-py.sh
Pylint incorporates new rules based on the version of pylint and
python. This PR adds a configuration file that should help us keep the
rule set we apply more consistent over time, avoiding confusing results
from different errors appearing in different settings.
> USHIFT-1222: make pylint configuration more static

- packaging/rpm/microshift.spec
- validate-microshift/cluster-debug-info.sh
We depend on cri-o and can rely on it to pull in any specific version
needed.  Currently neither cri-o nor podman specify a minimum version.
> OCPBUGS-11421: remove version specifier for container-selinux

- docs/config/microshift-starter.ks
This is just simple fix for typo in the kickstarter file.
https://github.com/openshift/microshift/blob/main/docs/config/microshift-starter.ks#L35
> NO-ISSUE: fixing typo with crio package in kickstart file - from criu -> crio

- scripts/devenv-builder/configure-vm.sh
Relates to [USHIFT-1201](https://issues.redhat.com//browse/USHIFT-1201)
Transitioning CI to AWS in openshift/release#38877 is broken on release-4.13 due to the fact that on the release-4.13 version of configure-vm.sh, build dependencies are installed by default.  This is producing an error on the RHEL 9.2 instance in AWS related to git package dependencies:
```
sudo dnf install -y git cockpit make golang jq selinux-policy-devel rpm-build jq bash-completion
Error: [Errno 2] No such file or directory: '/var/cache/dnf/rhel-9-appstream-beta-rhui-rpms-ad06c8f61df035e2/packages/git-core-2.39.1-1.el9.x86_64.rpm' 
```
Back porting the more recent version will bring in changes that will condition the above command based on a CLI flag (--no-build-deps), which will skip the unnecessary deps install …
> USHIFT-1201 Backport configure-vm.sh to 4.13

- .pylintrc
- scripts/auto-rebase/handle_assets.py
- scripts/auto-rebase/presubmit.py
- scripts/auto-rebase/rebase.py
- scripts/jira/cloner.py
- scripts/release-notes/gen_ec_release_notes.py
Disable logging-fstring-interpolation, logging-not-lazy, line-too-long
because we have valid code that violates those rules in a few places
where we disable the rules locally.
> USHIFT-1234: globally disable a few pylint rules that are commonly an issue

- cmd/generate-config/config/config-openapi-spec.json
- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
- packaging/microshift/config.yaml
- pkg/config/manifests.go
The docs incorrectly said /var/lib instead of /usr/lib.
> USHIFT-974: fix docs and default config file for manifest locations

- test/Makefile
- test/assets/hello-microshift.yaml
- test/requirements.txt
- test/resources/common.resource
- test/resources/kubeconfig.resource
- test/suites/load-balancer.robot
- test/suites/variables.yaml
> USHIFT-1119: Add load-balancer Robot Framework test

- packaging/crio.conf.d/microshift-ovn.conf
Due to limitations on AWS ARM, we are removing this CPU pinning to elivate confromance testing failing on ARM. This feature will be revisited, see https://issues.redhat.com/browse/USHIFT-1239
> OCPBUGS-13239: Remove CPU Pinning

- Makefile
- docs/rhel4edge_iso.md
- scripts/image-builder/build.sh
- scripts/image-builder/config/blueprint_v0.0.1.toml
- scripts/image-builder/config/kickstart.ks.template
* Add a special mode to the image-builder/build.sh script to generate edge commit archives
* Add an HTTP server to the ISO to allow local ostree updates
* Update documentation of Edge ISO with the new scenario
Closes [USHIFT-1218](https://issues.redhat.com//browse/USHIFT-1218)
> USHIFT-1218: Implement ostree updates from the local repository and edge commit

- docs/network/default_cni_plugin.md
- docs/network/host_networking.md
- packaging/microshift/ovn.yaml
- pkg/config/ovn/ovn.go
This flag is for building a secondary bridge br-ex1 for OVN-K. The br-ex1 bridge is used by the multiple external gateway feature that we don't support in microshift.
> OCPBUGS-13078: Remove config flag externalGatewayInterface from ovn.yaml

- pkg/components/storage.go
Minor fix in the message formatting.
Closes OCPBUGS-12977
> OCPBUGS-12977: Fix log message when CSI is disabled

- docs/config/Containerfile.tinyproxy
The usage of this container is documented [here](https://github.com/openshift/microshift/blob/main/docs/howto_http_proxy.md)
Closes [USHIFT-986](https://issues.redhat.com//browse/USHIFT-986)
> USHIFT-986: Use UBI image and EPEL repo for running tinyproxy container for CRIO proxy doc

- scripts/auto-rebase/rebase.py
Disable the pylint rule that complains about unused variables, since
it can't tell that the call to locals() is how those variables are
being used.
> USHIFT-1238: pass all locals to template when creating pr message

- ansible/roles/create-vm/defaults/main.yml
- docs/devenv_cloud.md
- docs/devenv_setup.md
- docs/devenv_setup_auto.md
- scripts/devenv-builder/manage-vm.sh
Follow-up on #1770 
Closes [USHIFT-1235](https://issues.redhat.com//browse/USHIFT-1235)
> USHIFT-1235: Fix RHEL 9.2 DVD name following the operating system GA

- docs/devenv_cloud.md
- docs/devenv_setup.md
- docs/devenv_setup_auto.md
- scripts/devenv-builder/manage-vm.sh
Backport of #1785
Closes [USHIFT-1241](https://issues.redhat.com//browse/USHIFT-1241)
> [release-4.13] USHIFT-1241: Fix RHEL 9.2 DVD name following the operating system GA

- assets/components/ovn/common/configmap.yaml
With this change, the gateway router of ovn-k can always forward egress traffic to host kernel.
It will fix the following scenarios:
1. no default gateway host
2. the connection to host default gateway is down
> OCPBUGS-11967: Use ovn-k masquerade nexthop address as gateway route's default gw

- scripts/auto-rebase/rebase.py
The previous attempt to fix this issue included the message saying the
changelog was being truncated but did not actually shorten the message
text.
/assign @pmtk
> USHIFT-1238: fix changelog truncation in changelog script

- scripts/devenv-builder/configure-vm.sh
When setting up a system with a subscription, lock it to the current
minor release. This prevents the system from being upgraded beyond
that minor release so we can be sure that we are testing on the
version we install. Add a flag to disable this behavior for systems
where we want to test upgrading past the installed version.
> USHIFT-1259: update configure-vm.sh to lock RHEL minor release

- scripts/jira/start_ticket.py
The OCPBUGS project has no sprints, so if the project for the ticket is
OCPBUGS use USHIFT to find sprints instead.
> USHIFT-1263: always use ushift to find active sprints

- test/resources/YAML.py
- test/resources/common.resource
- test/resources/kubeconfig.resource
- test/resources/microshift-host.resource
- test/resources/microshift-process.resource
- test/resources/oc.resource
- test/run.sh
- test/suites/version.robot
- update the way commands are run to return stdout
- log the remote host used for tests when connecting
- add shell runner for robot framework tests
- add tests for version config map and command line output
- move variable file up one level and make the default an example file
- update ssh connection so if no key is provided the active agent is used instead
> USHIFT-1198: add tests for version API

- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
Do not disable SELinux and switch to rhocp-4.13 released repos.
Closes [USHIFT-1271](https://issues.redhat.com//browse/USHIFT-1271)
> [release-4.13] USHIFT-1271: Switch to rhocp-4.13 repositories in devenv and ISO build environments

- scripts/image-builder/build.sh
- scripts/image-builder/cleanup.sh
- scripts/image-builder/create-vm.sh
Tested using the following sequence
```
BUILD_ARCH=$(uname -m)
OCP_REPO_NAME="rhocp-4.13-for-rhel-9-${BUILD_ARCH}-rpms"
reposync -n -a "${BUILD_ARCH}" -a noarch --download-path ~/openshift-local --repo="${OCP_REPO_NAME}"
find ~/openshift-local -type f -not -name microshift\* -exec rm -f {} \;
~/microshift/scripts/image-builder/build.sh -microshift_rpms ~/openshift-local -pull_secret_file ~/.pull-secret.json
```
Closes [USHIFT-1270](https://issues.redhat.com//browse/USHIFT-1270)
> USHIFT-1270: The ISO image version should be deduced from the microshift RPM

- Makefile
- docs/devenv_setup.md
- packaging/rpm/microshift.spec
- scripts/devenv-builder/configure-vm.sh
- scripts/image-builder/build.sh
- scripts/verify/verify-assets.sh
- Use configure-vm.sh script for configuring devenv
- Remove the duplication of information and dependency between the devenv configuration doc and configure-vm.sh
- Start using Go 1.20.3 in devenv
- Remove Go `BuildRequires` dependency from MicroShift spec file, using `go version` dynamic check
See an example of `make rpm` output generated on the go version incompatibility
```
The detected go version 1.20.2 is less than the required version 1.20.3
error: Bad exit status from /var/tmp/rpm-tmp.scxA6z (%prep)
Bad exit status from /var/tmp/rpm-tmp.scxA6z (%prep)
make: *** [Makefile:236: rpm] Error 1
```
Closes:
[USHIFT-1265](https://issues.redhat.com//browse/USHIFT-1265)
[USHIFT-1266](https://issues.redhat.com//browse/USHIFT-1266)
> Upgrade the devenv and image build scripts to use 4.14 release dependencies

- docs/rhel4edge_iso.md
- scripts/image-builder/build.sh
A more flexible approach for opening firewall ports when building R4E ISO images. 
By default, no ports are open.
A follow-up on the discussion in #1792 
Closes [USHIFT-1250](https://issues.redhat.com//browse/USHIFT-1250)
> USHIFT-1250: Add an option to build.sh to customize open firewall ports

- test/run.sh
Avoid having fixed locations for some of the practicalities of running RF both locally and on CI. Allow changing both the dir for venv for python dependencies and also the variables file. This also allows QE have multiple files locally and select when running the tests.
> USHIFT-1246: Enable custom variables file and venv dir in RF

- scripts/configure-multinode.sh
This was tested on top of https://github.com/openshift/microshift/pull/1717, which should merge soon.
To run it set WORKER_NODE_HOSTNAME to the hostname of a host which is setup to run microshift and run configure-multinode.sh on the microshift host. The worker node doesn't actually need to have microshift installed through, just CRI-O and OVN. Also make sure that `microshift-ovs-init.service` was run on the worker node so that OVN is setup the way that microshift expects. 
Running the conformance tests on a cluster setup this way, we still have 15 test failures:
[It] [sig-network] DNS should provide DNS for pods for Hostname [Conformance]
[It] [sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]
[It] [sig-network] DNS should resolve DNS of …
> USHIFT-485: Add script which adds worker node running via kubelet

- scripts/auto-rebase/rebase.py
- scripts/jira/start_ticket.py
Recently we updated `build_root` image to one based on RHEL9 which ships python3 instead of python2. Change is needed to fix rebase procedure
> NO-ISSUE Update python scripts to use python3

- docs/config/microshift-starter.ks
- docs/getting_started.md
The instructions were update for MicroShift supporting both `x86_64` and `aarch64` architectures now.
Closes [USHIFT-898](https://issues.redhat.com//browse/USHIFT-898)
> USHIFT-898: Port getting started instructions to work on RHEL 9.2 with MicroShift 4.13

- docs/config/microshift-starter.ks
- docs/getting_started.md
Backport of #1845 
Closes [USHIFT-957](https://issues.redhat.com//browse/USHIFT-957)
> USHIFT-957: [release-4.13] Port Getting Started instructions to use RHEL 9.2 and MicroShift 4.13

- packaging/greenboot/microshift-running-check.sh
All MicroShift failures return 1 except for the service not being able to start. This happens because it shortcuts error checking by sending a SIGTERM to itself so that it exits immediately. The default handler for this signal returns exit code 143, whereas all the other known failure conditions return 1.
When testing this behavior the greenboot script is not consistent when something fails. This change creates a specific handler for TERM so that the exit code is also 1.
> USHIFT-1286: Use exit code 1 in greenboot failures

- test/resources/microshift-host.resource
- test/variables.yaml.example
Use 'Get Varible Value' to see if an ssh key has been provided instead
of looking for the name in all of the variables ourselves.
> USHIFT-1284: make test login to microshift host more reliable

- scripts/devenv-builder/configure-vm.sh
Necessary for QE procedures to build the right source code in the release-4.13 branch.
> NOISSUE: [release-4.13] Fix configure-vm.sh script to use release-4.13 branch by default

- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- packaging/crio.conf.d/microshift_amd64.conf
- packaging/crio.conf.d/microshift_arm64.conf
* quay.io/openshift-release-dev/ocp-release:4.14.0-ec.1-x86_64
* quay.io/openshift-release-dev/ocp-release:4.14.0-ec.1-aarch64
* registry.access.redhat.com/lvms4/lvms-operator-bundle:v4.12
> USHIFT-1287: update image references to 4.14 EC 1 build

- scripts/devenv-builder/configure-vm.sh
Installing microshift via configure-vm.sh was working before, but today it was failing because gcc wasn't installed:
```
error: Failed build dependencies:
gcc is needed by microshift-4.14.0_0.nightly_2023_05_29_174116_20230531233827_e4dff3d6-1.el9.x86_64
```
> USHIFT-1292: Install GCC in dev VM

- e2e/tests/0040-reboot.sh
require several successful connection attempts before deciding that it's really working
tries to mitigate situation when one SSH command might be successful, but next one might get "connection refused"
> USHIFT-1299 make SSH re-connect after reboot more robust

- pkg/controllers/kube-apiserver.go
Apparently the indentation rules in go 1.20 are different, because
`make verify` fails on my host without this change.
> USHIFT-1291: fix gofmt for go 1.20

- go.mod
- pkg/config/lvmd/lvmd.go
- pkg/controllers/kube-controller-manager.go
The `github.com/ghodss/yaml` package is no longer being actively maintained. `sigs.k8s.io/yaml` is a permanent fork of `github.com/ghodss/yaml`, which is actively maintained by Kubernetes SIG and widely used in K8s projects.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, while `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. You can see the changes between the two versions here: [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), which mostly consists of bug fixes.
Please review and merge https://github.com/openshift/library-go/pull/1501 as well. Once that's done, I'll update `github.com/openshift/library-go` in this PR, allowing us to completely remove `github.com/ghodss/yaml`.
```
$ go mod why -m github.com/ghodss/yaml …
```
> chore: replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

- pkg/cmd/showConfig.go
- test/suites/show-config.robot
Change the default for the mode option to show-config so that the effective
configuration is displayed when no mode is specified and the user has to
ask explicitly for the default values.
> OCPBUGS-13221: show the effective config by default

- Makefile
- cmd/generate-config/config/config-openapi-spec.json
- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
- packaging/microshift/config.yaml
- packaging/rpm/microshift.spec
- pkg/config/config.go
- pkg/config/manifests.go
- pkg/config/manifests_test.go
- pkg/kustomize/apply.go
- test/resources/common.resource
- test/resources/kubeconfig.resource
- test/resources/microshift-config.resource
- test/suites/kustomize.robot
- support glob patterns in the manifest paths config entry
- add manifests.d glob patterns to the defaults to allow packages with separate applications to write their own customization.yaml files
/assign @eggfoobar
> USHIFT-1123: add manifests.d support

- scripts/auto-rebase/presubmit.py
Avoid issues like #1883 in the future
/assign @copejon @pmtk
> update asset verification script to look for redundant instructions

- Makefile
- e2e/main.sh
- e2e/tests/0050-pvc-resize.sh
- etcd/Makefile
We had original disabled cgo, because it increases the binary size. We will need to accept that footprint increase.
```
$ du -sh _output/bin/microshift*
110M	_output/bin/microshift
42M	_output/bin/microshift-etcd
$ du -sh _output/bin/microshift*
141M	_output/bin/microshift
55M	_output/bin/microshift-etcd
```
> USHIFT-1298: enable cgo to support loading local libraries

- e2e/main.sh
- e2e/tests/assets/greenboot-test.sh
- scripts/microshift-cleanup-data.sh
* Add the `--keep-images` option to `microshift-cleanup-data` script
* Use this option in the greenboot tests to speed it up
* Fixed bug when deleting pods
```
$ ./scripts/microshift-cleanup-data.sh 
Stop all MicroShift services, also cleaning their data
Usage: microshift-cleanup-data.sh <--all [--keep-images] | --ovn>
--all         Clean all MicroShift and OVN data
--keep-images Keep container images when cleaning all data
--ovn         Clean OVN data only
```
Closes [USHIFT-1267](https://issues.redhat.com//browse/USHIFT-1267)
> USHIFT-1267: Allow for keeping container images when cleaning MicroShift data

- test/suites/load-balancer.robot
`Log    ${result}` yields `<result object with rc 7>` which is not helpful
> NO-ISSUE: load-balancer.robot: change logging of `curl`'s `result`

- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- packaging/crio.conf.d/microshift_amd64.conf
- packaging/crio.conf.d/microshift_arm64.conf
- packaging/rpm/microshift.spec
- scripts/devenv-builder/configure-vm.sh
* restore build dependency on golang
* update image references to 4.14 EC 1 build
/assign @ggiguash @pacevedom
> USHIFT-1287, USHIFT-1315: prepare EC 1 build

- scripts/image-builder/create-vm.sh
Remove -b flag from sudo when creating the VM to allow active wait until the guest is completely installed and restarted.
> USHIFT-1297: Create image-builder VM as foreground process

- packaging/systemd/configure-ovs.sh
Ignore externalGatewayInterface flag in ovn.yaml.
> OCPBUGS-13078: Remove externalGatewayInterface from configure-ovs.sh

- test/README.md
Since we have a wrapper script for running the robot runner, it is not
necessarily obvious how to pass arguments through to the runner to
control which tests are run. Add a couple of examples to the
documentation.
> USHIFT-1328: document how to pass options to the test runner

- test/resources/DataFormats.py
- test/resources/microshift-config.resource
- test/resources/microshift-host.resource
- test/resources/microshift-process.resource
- test/resources/oc.resource
- test/resources/ostree.resource
- test/suites-ostree/upgrade-ostree.robot
- test/suites/show-config.robot
- test/suites/version.robot
Tests functionality of https://github.com/openshift/microshift/pull/1874
> USHIFT-1312 Test: Rebooting healthy system should result in backing up the data

- cmd/generate-config/config/config-openapi-spec.json
- docs/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/manifests.go
- packaging/microshift/config.yaml
- pkg/config/manifests.go
- pkg/config/manifests_test.go
- pkg/kustomize/apply.go
- test/suites/kustomize.robot
This change expands the search patterns for kustomization inputs to
include all of the forms supported by kubectl (kustomization.yaml,
kustomization.yml, and Kustomization).
> OCPBUGS-12744: support all kustomization base filenames

- docs/rhel4edge_iso.md
I did not create a related issue before. This PR is meant to address a problem that the path of file `.pull-secret.json` does not consist.
> NO-ISSUE: make the path to a file consist

- scripts/auto-rebase/rebase_job_entrypoint.sh
Periodic and presubmit jobs are set up differently. `oc registry login` fails to write registry config to default location in periodic jobs, no problem in presubmits.
> USHIFT-1359: Rebase: write cluster registry credentials to custom path

- docs/rhel4edge_iso.md
Necessary to prevent confusion when following the instructions from the document.
> NOISSUE: Add explicit environment requirements to the RHEL for Edge document

- pkg/admin/prerun/prerun.go
- pkg/admin/prerun/run_minimal.go
- pkg/cmd/run.go
Added function to launch minimal MicroShift services when needed. For now the idea is to keep it as a local function for prerun until we need to expose it. I tried to keep it simple at the call site by not sending the channels back to the caller to handle. 
This PR supports #1956 
/assign @pmtk
> USHIFT-1085: feat: support prerun with minimal services

- scripts/devenv-builder/configure-vm.sh
* Need to install openshift-clients RPM because MicroShift PRM depends on it explicitly
* Make sure to enable crun runtime in /etc/crio/crio.conf if not already enabled
Closes #1965
> NO-ISSUE: Fix configure-vm.sh script to work on CentOS 9 Stream

- packaging/greenboot/microshift_set_unhealthy.sh
Taking a backup is very important and we don't want to lose information that it should be done.
This change adds handling of situation where MicroShift is unhealthy because it couldn't make a backup and it should attempt to do it after reboot and after rollback: "don't overwrite 'backup' request if it wasn't created".
> USHIFT-1364: Don't overwrite health if backup wasn't created

- scripts/auto-rebase/rebase.sh
We use the _output directory for tools and test files, which should
not be deleted when running a rebase.
/assign @pmtk
> USHIFT-1401: rebase should only clean up files it creates

- scripts/devenv-builder/create-vm.sh
Do not background virt-install, since that breaks manage-vm.sh.
/assign @ggiguash @pmtk @pacevedom
> USHIFT-1412: run virt-install in the foreground

- Makefile
- scripts/verify/verify-licenses.sh
The OpenShift CI image may use a shim instead of the `go` compiler. Such shim producing debug output causes errors when run by `lichen`. 
Work around this problem by using the `go.real` driver for running `lichen` license verification.
> NO-ISSUE: Fix lichen error due to go shim usage in CI

- pkg/cmd/showConfig.go
Command `microshift show-config` must show the running configuration. This command loaded the configuration from /etc/microshift/config.yaml if it existed, possibly showing wrong information (editing the file without restarting microshift yields wrong data).
Having no configuration file fills the config with defaults. This might also be wrong in the event of a hostname change, when this is automatically fixed to use the previous name. This command would show the new name when MicroShift is using the previous one.
New approach stores the running configuration upon start and returns it when asked for it.
If MicroShift is not running this command returns the last active config.
> OCPBUGS-15740: Fix show-config command output

- packaging/rpm/microshift.spec
Exact pattern comparison does not work in osbuilder, generating the following error.
```
ERROR: BlueprintsError: microshift: DNF error occurred: DepsolveError: There was a problem depsolving microshift, microshift-greenboot, microshift-release-info, openshift-clients, iputils, bind-utils, net-tools, iotop, strace, redhat-release, caddy-2.4.6, kernel: 
Problem: package microshift-4.14.0_0.nightly_2023_07_05_191022_20230710193040_5aa2178c3_dirty-1.el9.x86_64 requires microshift-networking, but none of the providers can be installed
- conflicting requests
- nothing provides openvswitch3.1 = 3.1.0-14.el9fdp needed by microshift-networking-4.14.0_0.nightly_2023_07_05_191022_20230710193040_5aa2178c3_dirty-1.el9.x86_64
```
Closes [USHIFT-1411](https://issues.redhat.com//browse/USHIFT-1411)
> USHIFT-1411: Fix openvswitch3.1 version comparison not to use exact pattern

- docs/contributor/rhel4edge_iso.md
- scripts/image-builder/build.sh
- scripts/image-builder/config/kickstart.ks.template
Using HTTP server for local `ostree` upgrades is not necessary, hence the simplification of the default ISO configuration.
Closes [USHIFT-1395](https://issues.redhat.com//browse/USHIFT-1395)
> USHIFT-1395: Use file protocol for local ostree updates instead of Caddy HTTP server

- test/bin/download_images.sh
- test/resources/TestAgent.py
- test/resources/ostree-data.resource
- test/resources/ostree-health.resource
- test/resources/ostree.resource
- test/suites-ostree/backup-restore.robot
- test/suites-ostree/failed-upgrade.robot
- test/suites-ostree/fdo.robot
- TestAgent.py for managing test agent config
- Split `ostree.resource`
- General cleanup of keywords related to upgrades
- New test `failed-upgrade.robot`
> USHIFT-1372: Backing up the data is top priority

- test/bin/ci_phase_iso_boot.sh
- test/bin/scenario.sh
When no PUBLIC_IP is set, assume connections will come from the
hypervisor to the VM ("local" mode) and configure the VM properties
accordingly.
> USHIFT-1429: set port values for new VMs by default

- packaging/rpm/microshift.spec
Backport the fix to pin OVS in the 4.13 branch temporarily.
> USHIFT-1421 pin ovs 4.13

- scripts/image-builder/build.sh
- scripts/image-builder/cleanup.sh
- scripts/image-builder/config/blueprint_v0.0.1.toml
- scripts/image-builder/config/fast-datapath.toml.template
- scripts/image-builder/config/openshift-local.toml.template
- scripts/image-builder/config/rhocp-4.13.toml.template
Instead of downloading dependencies and manipulating the local repo,
use the regular repositories normally. This allows composer to find the
pinned version of openvswitch3.1 needed right now.
Includes some other cleanup changes.
/assign @ggiguash @jogeo
> USHIFT-1422: use the regular RPM repositories for dependencies in image-builder script

- test/bin/download_images.sh
When creating an alias reference, `ostree refs` requires a `--repo`
argument to know where to create the reference.
/assign @pmtk
> USHIFT-1433: pass repo to ostree refs command

- pkg/admin/prerun/health.go
- pkg/admin/prerun/prerun.go
- pkg/admin/prerun/upgrade_blocking.go
- pkg/admin/prerun/upgrade_blocking_test.go
- pkg/admin/prerun/version.go
- pkg/admin/prerun/version_test.go
- pkg/cmd/run.go
We won't aim toward running migration in prerun phase (instead it'll run in full cluster).
Therefore, removing all references to migration from prerun.
It can be now thought of as two, almost distinct, areas:
- data management (backup, restore, removal), and
- version metadata management
> USHIFT-1413: Update prerun after storage migration design changes

- .gitignore
It's a directory created when running robot framework tests, but we don't want to commit it to the repo.
> NO-ISSUE: add __pycache__ to .gitignore

- scripts/image-builder/build.sh
Custom RPMs are only used if specified explicitly from the command line.
Closes [USHIFT-1395](https://issues.redhat.com//browse/USHIFT-1395)
> USHIFT-1395: Fix custom-rpm failure in build.sh

- test/suites/snapshot.robot
Test seems to be flaky in the metal-tests workflow, temporarily disable until its passing.
> USHIFT-1438: Temporarily skip csi snapshot test

- pkg/admin/prerun/backups.go
- pkg/admin/prerun/prerun.go
- pkg/admin/prerun/system.go
> USHIFT-1225: Remove backups for no longer existing deploys

- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- packaging/crio.conf.d/microshift_amd64.conf
- packaging/crio.conf.d/microshift_arm64.conf
The second EC3 build from cdfc80e04b642b7e5b55ddd896aeb969e281e300 is
failing because the rebase script is reverting some code changes.
We need to update our image references by hand so that ART can build
without the rebase step.
> USHIFT-1439: manually update image references to EC3

- test/bin/build_images.sh
- test/bin/download_images.sh
Download the composer logs for all of the builds performed and stage them
with unique filenames so they can be collected by the CI system.
Remove the redundant log handling from the download script.
capture the depsolve logs for each blueprint separately
/assign @pacevedom @copejon
> USHIFT-1436: capture composer logs when building images

- test/kickstart-templates/kickstart.ks.template
The call to ostreesetup creates an edge remote with the correct URL,
so there is no need to delete it and re-create it.
> USHIFT-1448: remove redundant ostree setup in kickstart

- test/bin/manage_vm_storage_pool.sh
This commit ensures the storage pool manager script can be invoked
multiple times without error.
/assign @ggiguash @pacevedom @copejon
> USHIFT-1449: make storage pool manager script handle repeated calls

- packaging/rpm/make-rpm.sh
- test/Makefile
- test/bin/build_images.sh
- test/bin/ci_phase_iso_build.sh
- test/bin/common.sh
- test/bin/create_local_repo.sh
- test/bin/get_latest_rpm_version.sh
- test/bin/manage_vm_connections.sh
- test/bin/scenario.sh
- test/image-blueprints/rhel92-microshift-previous-minor.toml
- test/image-blueprints/rhel92-microshift413.toml
- test/image-blueprints/rhel92-source-fake-next-minor.toml
- test/package-sources/microshift-fake-next-minor.toml
- test/scenarios/upgrade-minor-version-healthy.sh
Depends on https://github.com/openshift/release/pull/40720
/assign @pmtk
> USHIFT-1098: add minor-version upgrade scenario

- scripts/image-builder/build.sh
When running the script with a remote RPM repository, it did not work correctly.
```
$ bash -x ./scripts/image-builder/build.sh -pull_secret_file ~/.pull-secret.json -microshift_rpms https://mirror.openshift.com/pub/openshift-v4/$(uname -m)/microshift/ocp-dev-preview/latest-4.14/el9/os/
...
...
+ createrepo microshift-local
+ open_repo_permissions microshift-local
+ find microshift-local -type f -exec chmod a+r '{}' ';'
+ find microshift-local -type d -exec chmod a+rx '{}' ';'
++ find https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview/latest-4.14/el9/os/ -name 'microshift-release-info*.rpm'
find: ‘https://mirror.openshift.com/pub/openshift-v4/x86_64/microshift/ocp-dev-preview/latest-4.14/el9/os/’: No such file or directory
```
> NO-ISSUE: MicroShift release info RPM should be queried from the local directory

- test/suites/version.robot
Add a test to ensure the version metadata file is updated when
MicroShift starts.
Also simplify some of the version parsing logic to make it easier to
understand what expected values are.
/assign @pmtk
> USHIFT-1089: microshift writes version metadata file

- scripts/image-builder/build.sh
Do not assume that the RPM source being copied is the result of a
local build, and copy everything we find. This ensures that if someone
points the script to a directory full of RPMs it can create a repo out
of them.
This partially reverts 75609ae5a251772e4d72e0c0ba9dd123d5ac02a1
/assign @ggiguash @jogeo
> USHIFT-1457: copy entire rpm source to local repo

- test/README.md
- test/bin/build_images.sh
- test/bin/build_rpms.sh
- test/bin/ci_phase_iso_build.sh
- test/bin/common.sh
- test/bin/create_local_repo.sh
- test/bin/download_images.sh
- test/bin/rebuild_source_images.sh
Consolidate several places where we build RPMs into a single script that
can be reused.
/assign @pmtk @jogeo @copejon
> USHIFT-1458: update build scripts to make rpm builds consistent

- Makefile
Deleting the top-level `_output` directory recursively rather then deleting sub-dirs one-by-one.
> NO-ISSUE: Simplify makefile clean target to remove the top-level directory

- assets/components/ovn/multi-node/node/daemonset.yaml
- scripts/multinode/configure-pri.sh
- scripts/multinode/configure-sec.sh
1. Enable no uplink mode for ovnkube.
2. Configure dummy IP for br-ex interface.
> OCPBUGS-16192: Use no uplink br-ex in mutlinode mode

- scripts/image-builder/build.sh
> OCPBUGS-16658: Fix build.sh due to the openvswitch version pinning

- scripts/release-notes/gen_ec_release_notes.py
We had 2 builds of 4.14.0~ec.3, which confused the release note tool. This
change adds the date and patch number values from the RPM version to the
tag and release name in case we have a similar issue in the future.
> USHIFT-1456: use more complete version numbers in release tagging

- packaging/rpm/microshift.spec
Two way version comparison is now in place:
* microshift depends on the exact version of microshift-networking / microshift-selinux
* all the sub-packages require the exact version of microshift
To test RPM dependencies, I used the following configurations
* rpm-413: vanilla RPM packages built by ART - no dependency fix
* rpm-nover: RPM packages from the main branch - no dependency fix
* rpm-ver: RPM packages with the current fix
*Scenario 1* - `4.13` allows mixing `nover` RPMs
```
$ sudo dnf localinstall microshift-4.13.5-202307141802.p0.g59bf35c.assembly.4.13.5.el9.x86_64.rpm ../rpm-nover/microshift-networking-4.14.0_0.nightly_2023_07_20_215234_20230726140113_fa2a51bc9-1.el9.x86_64.rpm ../rpm-nover/microshift-selinux-4.14.0_0.nightly_2023_07_20_215234_20230726140113_fa2a51bc9-1.el9.noarc …
```
> OCPBUGS-16339: Add explicit version dependencies among MicroShift RPM packages

- test/resources/libostree.py
- test/suites-ostree/backup-prune.robot
This is to avoid errors in timing between file creation and when the system comes up, since the prune logic skips touching the directory if backup exists, this tests could fail sometimes if ran out of order.
Moving to one test to avoid issue.
/assign @pmtk
> USHIFT-1445: fix: prune test

- docs/contributor/greenboot.md
- docs/user/greenboot.md
- packaging/rpm/microshift.spec
Added explicit dependency on `microshift-greenboot` from the `microshift` RPM and updated the docs.
```
$ rpm -qpR ./_output/rpmbuild/RPMS/x86_64/microshift-4.14.0_0.nightly_2023_07_26_001154_20230727003726_560fed8c1_dirty-1.el9.x86_64.rpm | grep ^microshift
microshift-greenboot = 4.14.0_0.nightly_2023_07_26_001154_20230727003726_560fed8c1_dirty
microshift-networking = 4.14.0_0.nightly_2023_07_26_001154_20230727003726_560fed8c1_dirty
microshift-selinux = 4.14.0_0.nightly_2023_07_26_001154_20230727003726_560fed8c1_dirty
```
Closes [USHIFT-1493](https://issues.redhat.com//browse/USHIFT-1493)
> USHIFT-1493: The microshift-greenboot package is no longer optional

- scripts/auto-rebase/rebase.sh
The ART pipeline does not report which inputs it passes to the rebase
script on its own, so we need to add details to aid in debugging build
failures.
/assign @copejon
> USHIFT-1520: show LVMS bundle source in rebase output for debugging

- scripts/auto-rebase/last_rebase.sh
- scripts/auto-rebase/rebase.sh
The production pipeline is passing an old value. We want that input
parameter to be controlled explicitly by the development, so ignore
the parameter and hard-code a value in the rebase script.
/assign @copejon @ggiguash @pmtk
> USHIFT-1519: hard-code source of LVMS manifests

- Makefile
- scripts/image-builder/build.sh
Also, fix Makefile to allow `build.sh` command line override when running `make iso` commands.
Closes [USHIFT-1516](https://issues.redhat.com//browse/USHIFT-1516)
> USHIFT-1516: Fix build.sh to properly pick up embedded container references

- scripts/multinode/configure-pri.sh
- scripts/multinode/configure-sec.sh
The secondary node is now tagged with "worker" label.
```
NAME             STATUS   ROLES                         AGE   VERSION
microshift-pri   Ready    control-plane,master,worker   79s   v1.27.1
microshift-sec   Ready    worker                        31s   v1.27.1
```
The following additional changes were also implemented:
- Keep images when cleaning MicroShift data to speed up pod reboot
- Wait until microshift-ovs-init.service is started to avoid race condition with IP setting
- Verify kubelet process is killed on the secondary node
- Unmount /var/lib/kubelet on the secondary node to allow directory deletion
- Wait until all MicroShift nodes are ready
- Wait until the pods are ready using the multinode pod counts
Closes [USHIFT-1510](https://issues.redhat.com//browse/USHIFT-1510)
> USHIFT-1510: Enhance multinode configuration scripts to be more resilient

- scripts/image-builder/cleanup.sh
- test/README.md
- test/bin/build_images.sh
- test/bin/rebuild_source_images.sh
- test/bin/start_webserver.sh
The testing environment was comprised of a development machine separate from the hypervisor host.
The following changes were implemented:
* Reorganize the README.md into 4 main sections and fix title cases
* Fix all the commands and script references in the docs to be relative to the root microshift repo
* Fix local source changes script to run missing repo creation and web server startup
* The image build procedure now fails after downloading logs if at least one job failed
* Scenarios can be run with parameters from an arbirary directory
* Fixed `scripts/image-builder/cleanup.sh` script to properly clean multiple osbuild workers
> NO-ISSUE: Review scenario part of the test harness

- scripts/image-builder/configure.sh
when /home/microshift  using default permissions (700)  `build.sh`  fails with an error: 
```bash
+ sudo composer-cli blueprints delete microshift
+ true
+ sudo composer-cli blueprints push /home/microshift/microshift/_output/image-builder/blueprint_v0.0.1.toml
+ sudo composer-cli blueprints depsolve microshift
ERROR: BlueprintsError: microshift: DNF error occurred: RepoError: There was a problem reading a repository: Failed to download metadata for repo 'de3d95914e632f2aee75dc0a200ac02106835607234a2ba2e4b3c2451b1efcad' [microshift-local: file:///home/microshift/microshift/_output/image-builder/microshift-local/]: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
+ /home/microshift/microshift/scripts/image-builder/cleanup.sh
```
> NO-ISSUE:  set the correct permission for osbuild-composer

- cmd/microshift/main.go
- pkg/cmd/admin.go
- test/suites-ostree/backup-restore.robot
* Adds `restore` subcommand that takes fullpath to a backup: `sudo microshift admin restore /var/lib/microshift-backups/some-manual-backup/`
* Flattens the subcommand structure from `admin data backup,restore` to `admin backup,restore`.
> USHIFT-1470: Add subcommand to restore a backup

- pkg/admin/prerun/system.go
System without rollback deployment is valid system.
By not throwing an error in this situation, MicroShift will continue start up (without restoring anything) to give cluster a chance to recover instead of just failing.
> USHIFT-1528: Don't throw an error when there is no rollback deploy

- scripts/auto-rebase/rebase.py
We've agreed that the dev team can add cherry-pick-approved to rebase PRs,
so have the bot do it when the PR is submitted.
We do not use jira issues to track rebase PRs, so instead of forcing 
reviewers to add the label manually put `NO-ISSUE` in the PR title to have
the bot label it for us.
/assign @ggiguash @pmtk @jogeo
> USHIFT-1504: add more labels to rebase PRs automatically

- packaging/greenboot/functions.sh
- packaging/greenboot/microshift-running-check.sh
Closes [USHIFT-1389](https://issues.redhat.com//browse/USHIFT-1389)
> USHIFT-1389: Enhance greenboot check script to print cluster debugging information on failures

- test/bin/ci_phase_iso_boot.sh
This aims to help when many scenarios are being booted in CI and one of them fails without clear message which one
> NO-ISSUE: Log "pid to scenario" mapping for easier debugging

- scripts/auto-rebase/rebase.py
Backport changes from https://github.com/openshift/microshift/pull/2125 to the 4.13 branch.
/assign @pmtk @ggiguash @pacevedom
> USHIFT-1504: rebase labels 4.13 take 2

- docs/contributor/howto_quay_mirror.md
we would l like to create a microshift-quay vm  with 2 attached networks  (default and isolated),
so it could communicate to both microshift-edge (isolated) and the upstream quay registry (default).
> NO-ISSUE: Document how to add second interface in libvirt quay VM

- pkg/admin/prerun/prerun.go
- pkg/cmd/run.go
Initial PR to rename `prerun` struct to `datamanger`.
Since `PreRun` does much more now, we decided to do a refactor and change the struct name to `DataManager` and it's receiver functions.
/assign @pmtk
> USHIFT-1487: refactor: rename prerun struct to datamanager

- docs/contributor/devenv_setup.md
- scripts/devenv-builder/manage-vm.sh
After building an ISO with embedded containers (see #2179) using test harness environment, it because apparent that the default 50GB of disk space is not enough on the dev machine.
> USHIFT-1512: Increase the default devenv disk size to 70GB

- test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
This depends on #2114
/assign @ggiguash @zshi-redhat
> USHIFT-1426: remove openvswitch pin in test image blueprint

- scripts/devenv-builder/configure-vm.sh
If any of these commands fail when chained by `&&`, the script does not exit with error on the spot.
For example,  intermittent `curl` failure did not result in the top-level script failure.
```
+ curl -L -o go1.20.4.linux-amd64.tar.gz https://go.dev/dl/go1.20.4.linux-amd64.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    75  100    75    0     0    735      0 --:--:-- --:--:-- --:--:--   735
33 95.5M   33 31.5M    0     0  38.7M      0  0:00:02 --:--:--  0:00:02 38.7M
67 95.5M   67 64.7M    0     0  53.2M      0  0:00:01  0:00:01 --:--:-- 82.7M
curl: (18) transfer closed with 32253670 bytes remaining to read
+ false
```
> NO-ISSUE: Separate golang archive installation commands

- packaging/greenboot/functions.sh
This change safeguards the  wait_for function  against long running commands.
if the  command is not finished within the arg_1 `timeout`  , command (arg_2)  will be killed   and `return 1`.
> USHIFT-1555: add timeout for long running command

- packaging/greenboot/functions.sh
This reverts commit 733477ccd92a670866d5fff52aae3110d6b75a78.
This change introduced an issue on greenboot  while VM is booting.
> Revert "USHIFT-1555: add timeout for long running command"

- test/bin/scenario.sh
- test/scenario_settings.sh.example
- Fix VM boot timeout by using --wait timeout option instead of timeout
- Implement virt-install retries due to https://github.com/virt-manager/virt-manager/issues/498
- Moved greenboot check from the launch to test phase
**Tests on c5n.metal at eu-west-1b**
|Phase|Greenboot in launch|Greenboot in test|
|---------|------------------------------|-------------------------|
|boot   |16m                             |9m                         |
|test     |20m                             |20m                       |
Closes [USHIFT-1578](https://issues.redhat.com//browse/USHIFT-1578)
> USHIFT-1578: Optimize virt-install and greenboot sequences in scenario.sh

- test/bin/build_images.sh
- test/bin/common.sh
- test/bin/manage_hypervisor_config.sh
- test/bin/scenario.sh
When running in CI, virtual machine creation hits the https://github.com/virt-manager/virt-manager/issues/498 libvirt bug.
```
sudo virt-install --noautoconsole --name rhel-9.2-microshift-source-rollback-host1 \
--vcpus 2 --memory 4092 --disk pool=vm-storage,size=20 --network network=default,model=virtio \
--events on_reboot=restart --location /home/microshift/microshift/_output/test-images/vm-storage/rhel-9.2.iso \
--extra-args inst.ks=http://192.168.122.1:8080/scenario-info/rhel-9.2-microshift-source-rollback/vms/host1/kickstart.ks \
--wait 15
ERROR    Error: --disk pool=vm-storage,size=20: internal error: pool 'vm-storage' has asynchronous jobs running.
```
Closes [USHIFT-1591](https://issues.redhat.com//browse/USHIFT-1591)
> USHIFT-1591: Optimize VM creation process by creating multiple libvirt storage pools

- test/bin/scenario.sh
junit is recorded during "create" phase and waiting for greenboot was moved to "run" phase.
That resulted in adding an extra <testcase> after the </testsuite> which violates XML spec which says that XML document can only have one root element.
Malformed XML is available in `artifacts/microshift-metal-tests/openshift-microshift-e2e-metal-tests/artifacts/scenario-info/$SCENARIO/vms/junit.xml`
> NO-ISSUE: Remove "greenboot-complete" from scenario.sh junit

- test/assets/isolated-lb-service.yaml
- test/bin/ci_phase_iso_build.sh
- test/image-blueprints/group2/rhel92-source-isolated.toml
- test/kickstart-templates/kickstart.ks.template
- test/resources/microshift-host.resource
- test/resources/microshift-process.resource
- test/scenarios/el92-src@isolated-net.sh
- test/suites/isolated-net/isolated-network.robot
Enable container image embedding and add the isolated network test.
**Note: this PR also fixes the race condition when rebooting the MicroShift host.**
This PR depends on the following to be merged:
- #2179 
- #2206 
- #2208
- #2209
Closes [USHIFT-1512](https://issues.redhat.com//browse/USHIFT-1512)
> USHIFT-1512: Add isolated network test

- assets/components/lvms/topolvm-controller_deployment.yaml
set topolvm-controller strategy = Recreate, else greenboot sees more pods than expected (terminating + starting) and fails
> USHIFT-1619: Set topolvm deployment strategy recreate

- test/scenarios-periodics/el92-src@upgrade-from-release-fails-and-rollsback.sh
This PR is part of the implementation of [USHIFT-1108](https://issues.redhat.com//browse/USHIFT-1108), the rest of the work being in the openshift/release repo.
Changes here tried to reuse existing logic as much as possible.  
- A ./test/Makefile target is added to build the 4.y-1 branch.
- The PREVIOUS_MINOR_VERSION is reused.  More var related to building prior release were added where they were needed to complete the pipeline.
-
> [USHIFT-1108] Add periodic scenario to test upgrade from latest release to head of next y-stream branch or main

- test/README.md
- test/bin/scenario.sh
It can be useful to access test VMs through the console. This patch
adds an option to the scenario test harness to add a VNC console that
can be used with cockpit to monitor or login to the VM.
/assign @ggiguash @pmtk @pacevedom
> USHIFT-1623: add support for vnc consoles to scenario vms

- pkg/controllers/cluster-policy-controller.go
Default configuration for event cache allows only 1 event every 5min. This triggers event aggregation which collapses several events into a single one, losing information about the event (aggregation happens when the reason is the same, regardless of the message). By allowing 1 event per second this problem is greatly reduced (if not completely).
> USHIFT-1590: Event cache configuration update

- pkg/util/net.go
The GetHostIP function is used repeatedly, which means we need to be
careful about how much it logs. This change adds a global state
variable to track whether the hard-coded node IP has been successfully
found, so that we only log that we are trying to find it if it has not
been sought before or if there is an error finding it.
/assign @pmtk @pliurh
> USHIFT-1624: quiet logging about node IP

- test/bin/build_images.sh
- test/bin/create_local_repo.sh
- test/bin/scenario.sh
- test/image-blueprints/group2/rhel92-microshift-previous-minor.image-installer
- test/kickstart-templates/kickstart-liveimg.ks.template
- test/resources/microshift-rpm.resource
- test/scenarios/el92-prel@upgrade-rpm-ok.sh
- test/suites/upgrade/upgrade-rpm-successful.robot
Implement a substitute test for `prow/microshift-rpm-upgrade` using test harness framework, adjusting it to support booting non-ostree images.
* Use `liveimg` directive to boot from the ISO instead of `ostreesetup` call
* Create an ISO image from `rhel92-microshift-previous-minor` blueprint
* Boot the mentioned ISO as a starting point of the test
* Verify greenboot and upgrade MicroShift RPMs to the current version
* Verify greenboot to ensure the upgrade was successful
P.S. This PR also fixes the `wait_for_ssh` and `wait_for_greenboot` issue I encountered. I noticed that long timeouts often seem to get stuck with `ssh`, so I replaced the `timeout` function by a loop.
Closes [USHIFT-1601](https://issues.redhat.com//browse/USHIFT-1601)
> USHIFT-1601: Implement MicroShift RPM upgrade tests on a non-ostree system

- pkg/admin/data/data_manager.go
- pkg/admin/data/data_manager_test.go
- pkg/cmd/admin.go
Adds a naive verification if provided path is
in fact a backup of MicroShift data.
It should prevent some accidental overwrites of
MicroShift data with contents of random directories.
> USHIFT-1538: Verify contents of a backup before restoring

- pkg/admin/prerun/backups.go
- pkg/admin/prerun/backups_test.go
- test/resources/libostree.py
Verifies if name of a backup is matching schema of automated backup.
Manual backups that start with `X.Y.Z_` or any other manual backup
with underscore in its name should not be subject to automated
backup pruning.
> USHIFT-1634: Pruning old backups: don't remove manual backups

- pkg/cmd/run.go
- pkg/controllers/etcd.go
microshift is running microshift-etcd binary as systemd [transient](https://github.com/openshift/microshift/blob/14adeba0d460b38c898d9b730806eb4f011b49cd/pkg/controllers/etcd.go#L73) unit ,
current behavior after microshift.service is stopped:
1. systemd sends its term signal  to the microshift.service,
2. microshift ServiceManager  stopping  the microshift-etcd.transient unit https://github.com/openshift/microshift/blob/14adeba0d460b38c898d9b730806eb4f011b49cd/pkg/controllers/etcd.go#L119-L126
3. microshift  exits prematurely: https://github.com/openshift/microshift/blob/14adeba0d460b38c898d9b730806eb4f011b49cd/pkg/controllers/etcd.go#L107-L116
this behaviour causes  unclean microshift services shutdown (see also [USHIFT-1533](https://issues.redhat.com//browse/USHIFT-1533)),
which is …
> OCPBUGS-14678: microshift-etcd shuts down independently

- pkg/cmd/showConfig.go
- test/suites/standard/show-config.robot
Closes [USHIFT-1665](https://issues.redhat.com//browse/USHIFT-1665)
> USHIFT-1665: Fix show-config command to require root priviledges

- assets/controllers/route-controller-manager/ns.yaml
- assets/controllers/route-controller-manager/route-controller-manager-clusterrole.yaml
- assets/controllers/route-controller-manager/route-controller-manager-clusterrolebinding.yaml
- assets/controllers/route-controller-manager/sa.yaml
- pkg/controllers/openshift-route-controller-manager.go
- scripts/auto-rebase/assets.yaml
There were a handful of resources (ns, sa, rbac) missing that are required by the openshift-route-controller-manager.
Added files:
- Adds the openshift-controller-manager namespace and SA, which were referred by the informer-clusterrolebinding.yaml.
`ns.yaml`
`sa.yaml`
- There are the missing permissions for the openshift-route-controller-manager SA that is already deployed in microshift
`route-controller-manager-clusterrole.yaml`
`route-controller-manager-clusterrolebinding.yaml`
> USHIFT-1654: Fix openshift-route-controller RBAC failures

- scripts/microshift-cleanup-data.sh
- test/resources/microshift-process.resource
The following enhancements were implemented:
- Enhanced usability by allowing positiion independent options and more flexible answer when prompted
- Added error messages when command line parsing fails
- Added `set -euo pipefail` option to the script
- Fixed crio container and image removal by using commands that actually work
- Added the missing `kube-system` namespace to the clean list
Closes [USHIFT-1509](https://issues.redhat.com//browse/USHIFT-1509)
> USHIFT-1509: Enhance microshift-cleanup-data script UX and functionality

- pkg/assets/crd.go
By changing `immediate` from `false` to `true`, `PollUntilContextTimeout` will no longer wait for specified interval (5 seconds in this case) before running given `func` for the first time.
This results in drastic speed up of MicroShift's start up: 40 seconds because currently we have 8 CRDs to apply.
> OCPBUGS-18706: Don't wait before applying a CRD

- pkg/controllers/infra-services-controller.go
- pkg/controllers/kube-apiserver.go
- pkg/controllers/openshift-default-scc-manager.go
- scripts/auto-rebase/rebase_patches/0030-kube-controller-manager-command-context.patch
- vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go
By using `cmd.Context()`, KCM will use a context MicroShift passes down through all the components.
When using `context.Background()` it won't ever stop, because it's never cancelled, and result in blocking `ServiceManager` which waits for all components to stop and make MicroShift use its whole internal `gracefulShutdownTimer`.
---
`shutdown-delay-duration` tells KAS how long to serve after receiving a stop signal.
Its value is provided to `time.Sleep()`, so it's used in full; there is not short-circuit mechanism that would let KAS exit earlier.
Default value of `70s` is set in `assets/controllers/kube-apiserver/defaultconfig.yaml`
> OCPBUGS-18548: Stop all MicroShift components when signaled to exit

- docs/config/microshift-starter.ks
- docs/contributor/rhel4edge_iso.md
- scripts/image-builder/config/kickstart.ks.template
ISO which is created using the image builder script is not able to run on the windows hyperv-gen2 which need gpt disk label instead msdos and UEFI support.
- https://learn.microsoft.com/en-us/windows-server/security/guarded-fabric-shielded-vm/guarded-fabric-create-a-linux-shielded-vm-template
> USHIFT-1682: Update kickstart template to have GPT disk label

- docs/contributor/rebase.md
- scripts/auto-rebase/rebase.sh
When the rebase script executes against the latest release-4.X branch and main, it does not generate a unique branch name. This creates a situation where, if 1 of the 2 is pushed, the rebase process running in parallel on the other may pull the remote rebase-branch.  This means that if a rebase onto branch A pushes rebase-branch A', the rebase process running in parallel on branch B can mistakenly pull branch A', rather than create a branch B', because the names of A' == B'. This effectively means branch A is being rebased onto branch B, and includes the commits of the parant branch.  Injecting the onto-branch's name (release-4.x | main) will detangle this situation.
> USHIFT-1681: Inject target branch name into rebase branch name

- scripts/microshift-cleanup-data.sh
- test/resources/microshift-process.resource
- test/resources/ostree-health.resource
- test/suites/greenboot/greenboot.robot
- test/suites/standard/cleanup-data.robot
Write an e2e test for testing the functionality of the `microshift-cleanup-data` script.
The following problems were found in the test and fixed:
* When deleting pods, no need to delete containers. Only delete images when `--keep-images` option is absent
* When cleaning OVN data, delete the `/var/run/ovn-kubernetes` directory instead of `/var/lib/ovnk` which does not exist
Closes [USHIFT-1509](https://issues.redhat.com//browse/USHIFT-1509)
> OCPBUGS-19296: Fix microshift-cleanup-data script and test its functionality

- pkg/cmd/run.go
Logging version on start will ease investigation of certain scenarios. Particularly useful when tracing back upgrades.
> OCPBUGS-19540: Log version when starting

- scripts/jira/manage_ticket.py
The tool for automatically managing jira tickets from the CLI should
not close a ticket if there is no PR. We can manage those by hand in
the GUI.
> USHIFT-1711: do not close jira tickets if there are no PRs

- Makefile
- test/resources/microshift-host.resource
- test/resources/oc.resource
- test/suites/standard/hostname.robot
When using .local hostnames and mDNS the native golang resolver does not work properly as it only reads the /etc/resolv.conf The cgo based resolver calls the C library routines instead. See https://pkg.go.dev/net#hdr-Name_Resolution
> OCPBUGS-19719: Use cgo net for name resolution

- test/suites/standard/kustomize.robot
added logic to make /usr/lib writable during test, rebooting will revert back to immutable filesystem
local testing didn't show an increase in test time for the kustomize test itself, looking at previous runs, this test was around 2 minutes, and even with the reboot, it seems to hover around there.
> USHIFT-1705: feat: re-add /usr/lib check for kustomize

- test/suites/standard/hostname.robot
Because `hostname.robot` was cleaning up MicroShift, but not re-enabling it, when kustomize.robot rebooted the ostree host MicroShift was not starting
> USHIFT-1705: hostname/kustomize tests: re-enable microshift.service after cleanup

- test/resources/microshift-process.resource
- test/suites/standard/kustomize.robot
Seems like we might have a timing problem between when the teardown of kustomize happens and when we validate microshift is up
> USHIFT-1737: fix: add wait for microshift serice to make sure health check succeeds

- test/resources/microshift-process.resource
- test/suites/greenboot/greenboot.robot
- test/suites/standard/hostname.robot
> USHIFT-1733: 1733 reenable after cleanup

- test/resources/microshift-process.resource
- test/suites/greenboot/greenboot.robot
- test/suites/standard/hostname.robot
- test/suites/standard/kustomize.robot
Cherrypicking #2403 #2412 #2425
/cc @ggiguash 
> [release-4.14] OCPBUGS-20044: Cherry pick 2403 2412 2425

- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/setup-microshift-host/defaults/main.yml
Closes #[USHIFT-1741](https://issues.redhat.com//browse/USHIFT-1741)
> USHIFT-1741: Ansible script bump golang version to 1.20.3 for MicroShift 4.14

- test/resources/journalctl.py
- test/suites/standard/log-scan.robot
This commit adds a new test to check for some common
permission-related errors that should never appear in the MicroShift
logs.
/assign @copejon @ggiguash @pmtk @pacevedom
> OCPBUGS-19422: add test to look for errors in logs

- pkg/cmd/run.go
- pkg/cmd/showConfig.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/debugging.go
- pkg/config/debugging_test.go
- test/suites/standard/configuration.robot
Be more explicit about warning the user about a logging configuration
mistake.
/assign @eggfoobar
> USHIFT-1725: warn the user when the logging level is unrecognized

- test/bin/build_images.sh
Update help text to clarify that the argument should be the path to a
file.
Add explicit error handling for missing template files.
Record junit output for rendering each blueprint template.
/assign @ggiguash @dhensell-rh
> USHIFT-1695: improve template argument handling in build images

- test/assets/selinux-test-exec.sh
- test/resources/selinux.py
- test/resources/selinux.resource
Updated our context check to include /var/log/kube-apiserver
Adds a domain transition test to our selinux tests to validate that executing a binary can't transition to more privileged files.
> USHIFT-1666: Selinux domain transition test 

- test/bin/build_images.sh
- test/bin/get_rel_version_repo.sh
- test/image-blueprints/group2/rhel92-microshift-previous-minor.toml
- test/package-sources/microshift-prel.toml
Reuse existing `get_crel_version_repo.sh` to obtain previous release most recent version and right mirror repository if RPMs are not published yet to RHEL repos.
> USHIFT-1766: Use mirror for unreleased RPMs for prev release

- test/resources/libvirt.resource
- test/resources/qemu-guest-agent.py
Right now, the custom resources/library files only support guest VM and OS lifecycle management over a network (ssh). For testing simulated air-gapped VMs (i.e. those with 0 NICs), we need an supplementary suite that enables guest management without a network.  The implementation is split between guest VM management and execution of arbitrary commands on the guest OS:
*test/resources/qemu-guest-agent.py*: uses the robot Process library to wrap virsh commands on the host.  The virsh guest-agent-command executes the passed in commands with args on the guest VM. The virsh process returns the output of the command to stdout as a json object, with stdout, stderr, exitcode, and exited (bool) values.  I tried to keep it as close to the Process API as I could in terms of function names and return …
> USHIFT-1628: Control test-framework guest OS and VM without network

- packaging/rpm/microshift.spec
Limit the golang version check to the major and minor version numbers.
/assign @ggiguash @pacevedom @pmtk
> [release-4.14] USHIFT-1779: fix golang check in spec file

- packaging/rpm/microshift.spec
Since the go directive in go.mod is advisory only until 1.21 the enforcement happens when building the rpm.
> USHIFT-1778: Fix rpm spec version comparison

- assets/components/openshift-router/cluster-role-system-router.yaml
- pkg/components/controllers.go
- scripts/auto-rebase/assets.yaml
Add cluster role system:router to allow creating additional routers besides the default. Default router uses a different cluster role with wider system permissions that are not applicable to application/namespace-bound routers.
> USHIFT-643: Add system:router cluster role

- test/resources/qemu-guest-agent.py
As it is, the virsh processes's return data is accessed before checking the virsh exit status.  If the exit code is non-0, `result.stdout['return']` is unassigned, causing a json decoding error.
This fix checks the `result.rc` before `result.stdout['return']` to protect against accessing a non-existent key.
> USHIFT-1628 [BUG] Custom qemu-guest-agent library mishandles non-0 virsh status

- Makefile
- test/bin/build_rpms.sh
this change will  use openshift's  go container toolchain in CI  ,make the resulting binary/rpm FIPs compliant and consistent with ART .
> USHIFT-1801: change build_rpms.sh to create rpm with podman in CI

- test/bin/build_rpms.sh
Because FIPS is not yet supported on ARM and there's no build image available for ARM, let's use `make rpm` to build RPMs for ARM.
> USHIFT-1812: `make rpm-podman` only for x86_64

- test/bin/ci_phase_iso_build.sh
This is a temporary workaround to allow #2378 to pass pre-submits.  The PR's jobs cannot pass because the scenario image doesn't exist.  After merging 2378, we should revert this PR (or maybe enhance the logic to permit presubmit builds when changes are made to group3 files).
> [USHIFT-2378] CI: Build group3 images unconditionally

- test/bin/scenario.sh
The script requires at least 2 arguments, but the login command
accepts an extra one.
> USHIFT-1818: fix argument processing for login command

- scripts/review-dashboard/dinghy.yaml
Create a separate section for backport reviews.
In the main branch reviews, ignore PRs that are not mergeable because
they have holds.
> USHIFT-1830: separate release branches in the review dashboard

- scripts/fetch_tools.sh
- test/bin/ci_phase_iso_boot.sh
- test/bin/ci_phase_iso_build.sh
- test/bin/ci_phase_test.sh
- test/bin/common.sh
- test/bin/manage_build_cache.sh
**Bottom line**: the current build times of `group1` and `group2` are ~40m. When testing cached builds on AWS metal host, the build times of `group1` and `group2` go down to ~25m.
> There are opportunities to also cache ostree commits in addition to ISO images, which will result in more savings
> of the overall build time.
The following changes were implemented in the test system:
- `scripts/fetch_tools.sh`
- Installation of awscli for manipulating the buckets
-  `test/bin/common.sh`
- Definition of the SCENARIO_BUILD_* denoting branch and current/previous tag
-  `test/bin/manage_build_cache.sh`
- Cache manipulation script working with AWS S3 bucket
The main cache update and usage logic was implemented in `test/bin/ci_phase_iso_build.sh`. 
If access to a AWS S3 bucket is not configured, …
> USHIFT-1547: Implement build ISO artifact caching in AWS S3 buckets

- scripts/microshift-cleanup-data.sh
Note the `MicroShift service...` messages before the exit.
When run with `--all` option, the output is:
```
Stopping MicroShift services
Disabling MicroShift services
Removing MicroShift pods
Removing crio image storage
Killing conmon, pause and OVN processes
Removing MicroShift configuration
Removing OVN configuration
MicroShift service was stopped
MicroShift service was disabled
Cleanup succeeded
```
When run with `--ovn` option, the output is:
```
Stopping MicroShift services
Removing MicroShift pods
Killing conmon, pause and OVN processes
Removing OVN configuration
MicroShift service was stopped
Cleanup succeeded
```
> USHIFT-1716: Report microshift service status in the microshift-cleanup-data script

- origin/NOTES
- origin/suite.txt
- origin/test/extended/router/unprivileged.go
- origin/test/extended/util/annotate/generated/zz_generated.annotations.go
- origin/test/extended/util/pods.go
Use agnhost image to bypass the `ShellImage` being hosted in the local registry from image operator.
> USHIFT-1781: Add unprivileged router tests

- test/bin/scenario.sh
The RPM-based scenarios may not have greenboot, and won't need to wait if
MicroShift wasn't installed in the original image.
> USHIFT-1826: let scenarios skip waiting for greenboot

- test/bin/scenario.sh
The debug log shows each command being executed in detail, and is very
useful when debugging a test locally.
> USHIFT-1829: add debug log for robotframework

- scripts/microshift-cleanup-data.sh
In some situations, especially in tests but not necessarily limited to
those cases, crio is not running when the microshift cleanup script is
run.  Detect the missing socket and skip the crio steps to avoid failures.
> OCPBUGS-22936: don't fail to clean up if crio is not running

- pkg/kustomize/apply.go
Enables server-side apply for kustomize at startup. related to https://github.com/openshift/microshift/issues/2535
Closes https://github.com/openshift/microshift/issues/2535
> USHIFT-1859: Kustomization: enable server-side apply to avoid big resources failing

- test/bin/scenario.sh
Local variables are function scoped, not block (loop) scoped, so on subsequent executions of loop-body they cannot be reassigned resulting in error.
> USHIFT-1868: Remove readonly flag from vars in loop

- pkg/admin/prerun/prerun.go
- test/resources/ostree-data.resource
- test/scenarios/el92-src@backups.sh
- test/suites/backup/backups.robot
Adds a check that prevents backup creation for current boot. Existence of such backup would prevent a proper backup (i.e. created on boot, with data compatible with previous boot) from being created (because microshift does not update backups - only creates new ones while deleting previous).
> OCPBUGS-22322: Don't create backups for current boot

- scripts/image-builder/configure.sh
As RHEL 9.3 is GA, we should stop using beta repositories
> USHIFT-1873: Remove osbuild's repo substitution for RHEL9.3 to beta

- test/bin/start_webserver.sh
Turn on autoindex so that on development hosts it is easier to
navigate to RF log files.
> USHIFT-1876: enable directory listing in test harness webserver

- test/resources/microshift-rpm.resource
- test/suites/standard/version.robot
Instead of reading the local source tree to determine what version
MicroShift should report, look at the dnf info for the package.
/assign @ggiguash @jogeo
> USHIFT-1816: use the package as source of truth for version of microshift in tests

- test/bin/scenario.sh
- test/kickstart-templates/kickstart-liveimg.ks.template
- test/scenarios-periodics/el92-src@fips.sh
- test/suites/fips/validate-fips.robot
This PR introduce FIPs support to the CI test framework:
- add fips_mode flag to the created  VMs 
- create new `fips` periodic scenario which run the standand suit test
- add RF FIPs compliance test on  RHEL and Microshift binary
- since osbuild  rpm based ISO images doesnt fully  support FIPs ,  `fips-mode-setup --enable` performed in kickstart.
> USHIFT-1798: introduce fips periodic scenario on rpm based system

- test/requirements.txt
This fixes a dependency problem on Fedora 39, while remaining functional on RHEL 9.x
> USHIFT-1942: Upgrade pyyaml version to 6.0.1 in RF

- test/resources/systemd.resource
- test/suites/osconfig/cleanup-data.robot
- test/suites/osconfig/systemd-resolved.robot
Besides adding `Wait Until Greenboot Health Check Exited` calls following the `Reboot MicroShift Host` function, the following fixes were implemented:
- Make the `systemctl` command retry less frequently (once in 15s instead of 10s) not to hit the 10s start limit
- Fixed the `Systemctl enable --now` call, which was wrong because `Systemctl` does not expect such usage
- Limited the journalctl output to 32K characters instead of 100 lines. The 32K characters is the max size of RF buffer anyway.
> USHIFT-1941: Fix osconfig tests failing due to unplanned reboots and service failures

- packaging/rpm/microshift.spec
The version number is not part of the openvswitch package name in Fedora. This PR proposes changing the networking rpmspec requirement to either openvswitch3.1 (RHEL or CS9) or openvswitch (Fedora).
> USHIFT-1949: Require openvswitch3.1 or openvswitch to allow installation on Fedora

- test/suites/osconfig/systemd-resolved.robot
Looks like the latest systemd-resolved package added quotes on the file name.
```
resolvConf: "/run/systemd/resolve/resolv.conf" 
```
> USHIFT-1954: Fix the check for resolvConf option in the kubelet configuration file

- Makefile
- packaging/blueprint/blueprint.toml.template
- packaging/images/Containerfile.rpm-builder
- packaging/rpm/microshift.spec
Also added code to the spec file to declare all the directories under `/usr/share/microshift` to make sure they are cleaned up on uninstall.
```
$ ls -Rl /usr/share/microshift/
/usr/share/microshift/:
total 0
drwxr-xr-x. 2 root root 65 Nov 21 14:04 blueprint
drwxr-xr-x. 2 root root 26 Nov 21 14:04 functions
drwxr-xr-x. 2 root root 61 Nov 21 14:04 release
drwxr-xr-x. 2 root root 38 Nov 21 14:04 spec
/usr/share/microshift/blueprint:
total 8
-rw-r--r--. 1 root root 3443 Nov 21 14:00 blueprint-aarch64.toml
-rw-r--r--. 1 root root 3441 Nov 21 14:00 blueprint-x86_64.toml
/usr/share/microshift/functions:
total 12
-rw-r--r--. 1 root root 8855 Nov 21 11:33 greenboot.sh
/usr/share/microshift/release:
total 8
-rw-r--r--. 1 root root 2469 Nov 21 11:19 release-aarch64.json
-rw-r--r--. 1 root root 2463 …
```
> OCPBUGS-22854: The microshift-release-info RPM is no longer required and it contains sample blueprints

- scripts/image-builder/config/blueprint_v0.0.1.toml
- test/bin/scenario.sh
- test/bin/stress_testing.sh
- test/image-blueprints/layer1-base/group1/rhel92.toml
- test/image-blueprints/layer1-base/group1/rhel93.toml
- test/run.sh
Stress Testing script to enable/disable conditions (limiting resources) on local or remote host:
- New `stress_testing.sh` script added.
- `run.sh` add a new `-s` option to set the Stress Condition
- `scenario.sh` add new `stress_testing` function to enable/disable Stress condition before/after `run_tests`
- Add a new package `iproute-tc` to blueprints
- This package is needed to run `tc qdisc` commands for networking Stress conditions.
> OCPQE-17114: Stress Testing

- test/run.sh
Fix a bug introduced on https://github.com/openshift/microshift/pull/2647 PR: `DEST_DIR` must be set right before installing tools to set the proper path.
`DEST_DIR` specifies where to install the tool. robotframework is installed in `microshift/_output/robotenv` instead of `microshift/microshift-rf-tests@tmp/venv`. This causes robot framework execution to fail: `/home/jenkins/ws/workspace/microshift/microshift-rf-tests/microshift/test/run.sh: line 104: /home/jenkins/ws/workspace/microshift/microshift-rf-tests@tmp/venv/bin/robot: No such file or directory`
I found this bug last night Jenkins run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/microshift/job/microshift-rf-tests/923/console
> set DEST_DIR before fetch_tools.sh script

- packaging/greenboot/functions.sh
- packaging/greenboot/microshift-running-check-olm.sh
- packaging/greenboot/microshift-running-check.sh
- packaging/rpm/microshift.spec
* Implement a new greenboot check script for the `microshift-olm` RPM, based on deployment readiness.
* Refactor the existing scripts to share some common functionality
> USHIFT-1955: Implement microshift-olm plugin altering greenboot functionality

- scripts/microshift-cleanup-data.sh
- test/resources/common.resource
- test/suites/osconfig/cleanup-data.robot
The new script usage is as follows.
```
Stop all MicroShift services, also cleaning their data
Usage: microshift-cleanup-data.sh <--all [--keep-images] | --ovn | --cert>
--all         Clean all MicroShift and OVN data
--keep-images Keep container images when cleaning all data
--ovn         Clean OVN data only
--cert        Clean certificates only
```
Note: the changes in `systemd.resource` file come to make the logs more verbose and explicit, which assists with troubleshooting. The previous implementation did not show the returned values.
> USHIFT-1926: Implement certificate cleanup option in microshift-cleanup-data script

- test/README.md
- test/bin/ci_phase_iso_boot.sh
- test/bin/mirror_registry.sh
- test/bin/scenario.sh
- test/kickstart-templates/kickstart.ks.template
- Adds the possibility of mirroring the registry so that it is hosted in the hypervisor.
- Activated automatically in CI, it needs ENABLE_REGISTRY_MIRROR=true env var when executed locally.
- Provides a registry where all the images from built RPMs are mirrored.
- VMs are configured to use the mirror for all possible image sources in a secure way.
- Image signature validation for images coming from registry.redhat.io and registry.access.redhat.com is disabled.
- Registry is started and filled with images in boot phase.
> USHIFT-1956: Add mirror registry options to test harness

- test/bin/ci_phase_iso_build.sh
This is necessary to see the errors occasionally appearing when running the cache update procedure in CI
> USHIFT-2063: Display manage_build_cache.sh output for getlast command during CI builds

- Makefile
since we are running concurrent  builds with different golang compilers and shared cache,  it may produce  FIPS incompateble RPMS,   which may lead  to FIPS test failures.
> USHIFT-1961: remove golang cache when building from ART container

- scripts/fetch_tools.sh
Previous parsing failed occasionally on `aarch64` platform with the following error. Since the `awscli` parameter is correct, it's likely that the parsing failed to "find" it in the function list, depending on the environment.
```
Script for downloading various tools
Usage: fetch_tools.sh <all | specific-tool...>
Destination can be changed using DEST_DIR environmental variable. Default: '/home/ec2-user/microshift/_output/bin'
Tools: 
- awscli
- controller-gen
- golangci-lint
- gomplate
- govulncheck
- hadolint
- kuttl
- lichen
- robotframework
- shellcheck
- yq
ERROR: Unknown tool: "awscli"
```
See [this error](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-microshift-main-microshift-metal-cache-nightly-arm/1736174459213058048) as an example.
> USHIFT-2063: Make fetch_tools.sh more robust when parsing function names

- test/suites/standard/validate-certificate-rotation.robot
this test will change the system date then expects Microshift service to be restarted and cert rotation to occur.
> USHIFT-1860: introduce certificate rotation tests

- test/bin/ci_phase_iso_boot.sh
- test/bin/mirror_registry.sh
- test/bin/scenario.sh
- test/kickstart-templates/kickstart.ks.template
- Enable registry mirror in x86 and aarch64.
- Use docker distribution instead of quay.
> USHIFT-2067: Use registry mirror in all architectures

- test/README.md
- test/bin/scenario.sh
- test/scenarios-periodics/el92-src@osconfig.sh
> USHIFT-2124: [release-4.15] Add test execution timeout to RF with 30m default

- scripts/devenv-builder/configure-vm.sh
- scripts/get-latest-rhocp-repo.sh
This is a manual backport of #2837
> [release-4.15] USHIFT-2152: look for dependency in rpm repo before trying to use it

- assets/components/openshift-dns/dns/configmap.yaml
increase the buffer-size to be in-sync with the upsteam fixed configuration [value](https://github.com/openshift/cluster-dns-operator/pull/266) .
> OCPBUGS-21901: increase core dns pod buffersize

- test/resources/microshift-rpm.resource
- test/suites/rpm/install-and-upgrade-successful.robot
Instead of relying on the host to only have repos configured for the
version we want, specify the version to use when installing the
RPM. This ensures that after a GA release the source package, with a
x.y.0 nightly version, can override the version from the standard
repos, with a newer version.
> USHIFT-2191: force versions in rpm install test

- test/suites/standard1/validate-certificate-rotation.robot
This test changes the time immediately after starting. If the test is executed when the system is running greenboot (from a reboot, for example), the time warp makes it fail with fake timeouts, as time jumped to the future. Depending on the test execution order this might happen randomly.
Force waiting for greenboot before starting to avoid glitches.
> USHIFT-2105: cert rotation test wait for greenboot

- scripts/release-notes/tag_stable_releases.py
Add a script to tag stable releases by looking at the dnf database to
find the packages and comparing them to the existing tags.
Running this script on my system today produced
```
GIT_COMMITTER_DATE=2023-05-16 09:44 git tag -s v4.13.0 17cae44
GIT_COMMITTER_DATE=2023-06-15 07:47 git tag -s v4.13.4 9ceaa92
GIT_COMMITTER_DATE=2023-07-14 14:09 git tag -s v4.13.5 59bf35c
GIT_COMMITTER_DATE=2023-07-20 04:31 git tag -s v4.13.6 694973d
GIT_COMMITTER_DATE=2023-08-03 10:56 git tag -s v4.13.8 717bea4
GIT_COMMITTER_DATE=2023-08-10 08:44 git tag -s v4.13.9 7dc6a00
GIT_COMMITTER_DATE=2023-08-24 07:42 git tag -s v4.13.10 2dd1281
GIT_COMMITTER_DATE=2023-08-31 12:52 git tag -s v4.13.11 30d1fee
GIT_COMMITTER_DATE=2023-09-07 09:07 git tag -s v4.13.12 b1c836a
GIT_COMMITTER_DATE=2023-09-14 05:25 git tag -s …
```
> USHIFT-2204: add script to tag stable releases

- scripts/image-builder/configure.sh
The [RHEL-16243](https://issues.redhat.com//browse/RHEL-16243) issue has been closed Done.
> USHIFT-2157: Stop using copr repos as a source of osbuild RPM packages

- scripts/image-builder/configure.sh
> [release-4.14] USHIFT-2159: Stop using copr repos as a source of osbuild RPM packages

- packaging/rpm/microshift.spec
Before the fix:
```
$ rpm2cpio ./_output/rpmbuild/RPMS/noarch/microshift-release-info-4.16.0_0.*.el9.noarch.rpm | cpio -it
./usr/share/microshift
./usr/share/microshift/blueprint
./usr/share/microshift/blueprint/blueprint-aarch64.toml
./usr/share/microshift/blueprint/blueprint-x86_64.toml
./usr/share/microshift/release
./usr/share/microshift/release/release-aarch64.json
./usr/share/microshift/release/release-olm-aarch64.json
./usr/share/microshift/release/release-olm-x86_64.json
./usr/share/microshift/release/release-x86_64.json
29 blocks
```
After the fix:
```
$ rpm2cpio ./_output/rpmbuild/RPMS/noarch/microshift-release-info-4.16.0_0.*.el9.noarch.rpm | cpio -it
./usr/share/microshift
./usr/share/microshift/blueprint
./usr/share/microshift/blueprint/blueprint-aarch64.toml …
```
> USHIFT-2230: OLM release info files are no longer included in the base release-info RPM package

- test/bin/build_images.sh
Reusing the same temporary repo name for different repository locations
can introduce issues if the dnf cache is not updated. Use the base name
of the repository URL as a unique name.
> USHIFT-2241: use unique repo name when extracting container images

- packaging/crio.conf.d/microshift_amd64.conf
- packaging/crio.conf.d/microshift_arm64.conf
containernetworking-plugins RPM which is a dependency of CRI-O installs
CNIs to /usr/libexec/cni but we don't want to use them because as part
of Multus integration we will get CNIs from container image shipped
with OpenShift.
> USHIFT-2247: Remove /usr/libexec/cni from CRI-O conf

- pkg/controllers/kube-apiserver.go
- pkg/util/net.go
Improves cold and warm boot by making readiness checks more often. With 5s interval and `immediate=false`, some components always take 5s.
Below data between microshift starts in standard-suite-1 for this PR and PR without these optimizations. Sample size = 1 for both tables.
```
| svc                                | pre-opt         | post-opt       |
|------------------------------------+-----------------+----------------|
| kube-scheduler                     | 5.041438552 s   | 882.369692 ms  |
| kube-controller-manager            | 5.021197046 s   | 900.299865 ms  |
| route-controller-manager           | 11.005827344 s  | 6.182889485 s  |
| kubelet                            | 5.019218917 s   | 124.979189 ms  |
| storage-version-migration-migrator | 5.002376112 s   | 112.298763 ms  | …
```
> USHIFT-2253: Improve microshift start time by reducing readiness checks intervals

- packaging/crio.conf.d/10-microshift_amd64.conf
- packaging/crio.conf.d/10-microshift_arm64.conf
Reverts openshift/microshift#2955
Reason is CRI-O will constantly log following and impact of this was not fully assessed.
When Multus will be added to MicroShift, it will overwrite the `plugin_dirs` to make sure that CNIs from containernetwork-plugins have priority.
```
Feb 06 13:07:21 i-0bd8f58175b615d74.us-west-2.compute.internal crio[46248]: time="2024-02-06 13:07:21.268158558Z" level=warning msg="Error validating CNI config file /etc/cni/net.d/100-crio-bridge.conflist: [failed to find plugin \"bridge\" in path [/opt/cni/bin]]"
Feb 06 13:07:21 i-0bd8f58175b615d74.us-west-2.compute.internal crio[46248]: time="2024-02-06 13:07:21.268289685Z" level=warning msg="Error validating CNI config file /etc/cni/net.d/200-loopback.conflist: [failed to find plugin \"loopback\" in path …
```
> Revert "USHIFT-2247: Remove /usr/libexec/cni from CRI-O conf"

- test/bin/get_rel_version_repo.sh
Failing to look at the system arch leads to choosing the wrong version
of 4.14 on ARM, which blocks the new Y-2 upgrade job being created in #2952.
/assign @pmtk
> USHIFT-2257: detect the released RPMs using the current system architecture

- packaging/rpm/microshift.spec
Creates new dedicated RPM for OLM's release info that depends on `microshift-release-info`
> OCPBUGS-27849: Create microshift-olm-release-info RPM

- scripts/docs-preview/Containerfile
- scripts/docs-preview/README.md
- scripts/docs-preview/build-in-container.sh
- scripts/docs-preview/build.sh
- scripts/docs-preview/clean.sh
- scripts/docs-preview/common.sh
- scripts/docs-preview/serve.sh
- Rename `BRANCH` to `DOCS_BRANCH` and allow environment override
- Remove `build-in-container.sh` script and embed the command in `Containerfile`
- Use named images and containers when building docs and running server
- Add a message with the URL of the docs when running `serve.sh`
- Add `clean.sh` script to clean-up images, containers, docs (e.g. to allow other doc branch builds)
- Updated `README.md` with all the changes
> USHIFT-2367: Minor enhancements of docs-preview scripts

- assets/components/lvms/topolvm-configmap_lvms-version.yaml
- assets/components/lvms/topolvm-controller_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
- assets/components/lvms/topolvm-node_rbac.authorization.k8s.io_v1_clusterrole.yaml
- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- scripts/auto-rebase/last_lvms_rebase.sh
- scripts/auto-rebase/lvms_assets.yaml
- scripts/auto-rebase/rebase-lvms.sh
Update to LVMS 4.15, also solves https://issues.redhat.com/browse/USHIFT-1874 by moving to an embedded lvmd implementation which has feature parity but uses less containers and slightly fewer resources. The lvmd socket is not necessary.
> OCPBUGS-29271: Rebase lvms registry.access.redhat.com lvms4 lvms operator bundle v4.15.0

- test/scenarios-periodics/el92-src@cncf-conformance.sh
the e2e.log file  is required when submitting for the  CNCF certification [ref](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr).
> USHIFT-2366:  include e2e.log in  CNCF  conformance artifacts

- test/scenarios-periodics/el92-src@cncf-conformance.sh
change the  sonobuoy invocation command to match the  [readme](https://github.com/cncf/k8s-conformance/blob/master/v1.27/rh-device-edge/README.md#run-conformance-tests)
> USHIFT-2378: change sonobuoy command to match  the CNCF readme

- test/scenarios-periodics/el92-src@osconfig.sh
The osconfig suite takes a long time because of the restarts tests. Reducing the amount of restarts has been discouraged, so instead we increase the timeout for the whole test, as it was too close to 1h and it flaked sometimes.
A different suite partition for execution should be studied as a long term alternative.
> USHIFT-2382: Increase timeout for osconfig periodic scenario

- scripts/jira/manage_ticket.py
- scripts/jira/manage_ticket.sh
Update the jira ticket tools to set the target version of a ticket based
on the branch the PR is created from and support setting the story points
for a ticket.
> USHIFT-2392: require story points and set target version on jira tickets

- scripts/jira/manage_ticket.py
Swapping the order of the 2 checks means that someone using --dry-run
still sees that the reason a ticket is not being closed is that it has
no story points.
> USHIFT-2430: when closing check story points before dry-run flag

- test/bin/build_images.sh
Corrects the GROUP variable value when build_images.sh is called with the -t option.
> USHIFT-2372: Correct the GROUP path assignment when calling build_images.sh with -t.

- test/bin/scenario.sh
The fix comes to work around stuck VM installations when the ostree payload cannot be pulled. 
The `--wait <time>` option of `virt-install` does not terminate the `tclsh` process used by the `unbuffer` command.
When `timeout` is used, all the process chain of `unbuffer->sudo->virt-install` is terminated.
Note: this problem is reproducing itself on ARM platform (not on x86) as noted in the JIRA issue comments.
> USHIFT-2286: Use timeout command for interrupting failed VM installations

- test/scenarios-periodics/el92-src@cncf-conformance.sh
change the  sonobuoy invocation command to match the  [readme](https://github.com/cncf/k8s-conformance/blob/master/v1.27/rh-device-edge/README.md#run-conformance-tests)
manual cherry-pick from https://github.com/openshift/microshift/pull/3026
> [release-4.15] USHIFT-2476: change sonobuoy command to match the CNCF readme

- test/run.sh
Add `Cluster ID` tests to default set of tests triggered from `test/run.sh` script. This list of tests is triggered on QE Regression and Upgrade tests.
Closes Jira ticket: [USHIFT-2116](https://issues.redhat.com/browse/USHIFT-2116)
> USHIFT-2116: CI implementation - Introduce cluster id

- scripts/jira/manage_ticket.py
> USHIFT-2478: fix jira script logic to handle closed PRs

- packaging/rpm/microshift.spec
Creates new dedicated RPM for OLM's release info that depends on `microshift-release-info`
> [release-4.15] OCPBUGS-29246: Create microshift-olm-release-info RPM

- assets/components/openshift-router/deployment.yaml
- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/config/ingress.go
- scripts/auto-rebase/rebase.sh
- test/resources/microshift-network.resource
- test/suites/network/multi-nic.robot
- test/suites/standard1/networking-smoke.robot
- test/suites/standard1/router.robot
> USHIFT-2261 USHIFT-2459: Add namespace ownership support for router

- test/bin/get_rel_version_repo.sh
dnf supports limiting results so we don't have to sort and filter them
ourselves.
/assign @pmtk
> USHIFT-2549: simplify repoquery command used to look up microshift RPM version

- test/bin/scenario.sh
virt-install reports errors, but with the retry loop it can take a
while before the script exits when the VM already exists. Add a check
for that case and return early. Treat it as not an error, since the
instruction is to ensure the VM exists and it does.
> USHIFT-2555: detect existing VM in scenario.sh create

- assets/components/openshift-router/deployment.yaml
- assets/components/openshift-router/service-cloud.yaml
- origin/patches/router-exposed.patch
- pkg/components/controllers.go
- scripts/auto-rebase/assets.yaml
- scripts/auto-rebase/rebase.sh
> USHIFT-2086: Expose router as LoadBalancer service

- pkg/controllers/etcd.go
`--collect` causes transient unit to be unloaded even if it failed. If the microshift-etcd.scope failed, it would leave an existing transient unit that could prevent restart of the microshift-etcd.
> OCPBUGS-30807: Add --collect to systemd-run microshift-etcd

- scripts/release-notes/gen_ec_release_notes.py
- Add example RPM repository settings to the release notes header.
- Show release notes header as part of dry-run output.
/assign @ggiguash @pacevedom
> USHIFT-2606: add rpm repo details to release notes

- cmd/generate-config/config/config-openapi-spec.json
- packaging/microshift/config.yaml
- pkg/config/ingress.go
> USHIFT-2459: Add docs to namespaceOwnership

- scripts/release-notes/gen_ec_release_notes.py
We build a default list of versions to scan using the current version
and the previous version. This assumes the script is run out of the
main branch where we can find the most current version under
development. During the period where 4.n is being developed, 4.n-1 may
still be producing only release candidates, so that scanning those 2
versions give us the 2 most recent candidates for having no
releases. During the period where the main branch has not landed a
rebase to update the version and both main and the pre-release branch
have the same version, we will end up scanning for EC or RC releases
of 4.n-2, but that's
/assign @pmtk @pacevedom
> USHIFT-1349: automatically track pre-release versions in release note script

- .golangci.yaml
- assets/components/openshift-router/deployment.yaml
- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/assets/admission-registration.go
- pkg/assets/apps.go
- pkg/assets/core.go
- pkg/assets/handler.go
- pkg/assets/rbac.go
- pkg/assets/scc.go
- pkg/assets/scheduling.go
- pkg/assets/storage.go
- pkg/components/controllers.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/ingress.go
- scripts/auto-rebase/rebase.sh
- test/suites/standard1/router.robot
> USHIFT-2444: Router enable/disable

- pkg/loadbalancerservice/controller.go
Fixes #3136
**Which issue(s) this PR addresses**: #3136 
Closes #3136
This is my idea for an option to implement the checking of loadBalancerClass in the internal load balancing service. It would avoid conflicts with metallb or other load balancers being used. 
I specified "microshift-internal" as the name of the internal balancer service, but that could be anything really, was just the first thing that I thought of. 
Let me know what you think 😄
> OCPBUGS-30833: Added a check for loadBalancerClass for built-in load balancing service.

- assets/components/ovn/multi-node/node/daemonset.yaml
- assets/components/ovn/single-node/master/daemonset.yaml
- assets/optional/multus/05-configmap.yaml
- assets/optional/multus/06-daemonset.yaml
- packaging/crio.conf.d/10-microshift_amd64.conf
- packaging/crio.conf.d/10-microshift_arm64.conf
- packaging/crio.conf.d/12-microshift-multus.conf
- scripts/microshift-cleanup-data.sh
- test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
- test/suites/osconfig/cleanup-data.robot
The /opt/cni/bin host directory will become immutable in some configurations. We need a writable directory for CNI binaries.
> OCPBUGS-31739: Use host directory /run/cni/bin for CNI binaries

- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- packaging/microshift/config.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/ingress.go
- pkg/loadbalancerservice/controller.go
- pkg/loadbalancerservice/router.go
- test/resources/microshift-network.resource
- test/suites/standard1/router.robot
> USHIFT-2443: Introduce router IP address listening configuration

- test/suites/standard1/router.robot
Sometimes the operations are not deterministic or take too long. Remove whatever is not mandatory for the test, as listening in the new ports also means not listening in the old ones, so the test may be simplified and the flakes should disappear.
> USHIFT-2968: Simplify router tests

- scripts/release-notes/gen_ec_release_notes.py
When ci-operator clones the repository it does not include any credentials to talk back to the repository.
To be able to execute `git push` we need to add a special remote that will use token that is either supplied (personal) or generated (Installation Access Token, IAT).
> USHFT-2969: Release notes job: use token for `git` commands

- scripts/devenv-builder/configure-vm.sh
If RHSM cannot manage repositories, then `dnf` is not aware of `rhocp` repositories and `scripts/get-latest-rhocp-repo.sh` fails.
> USHIFT-2992: Always allow RHSM to manage repos

- scripts/release-notes/gen_ec_release_notes.py
* Properly query for changes since the previous tag on the same
branch, instead of using the default of looking for the previous full
release on the branch.
* Apply the reported maximum length to release notes, while trying to
maintain some basic formatting.
> USHIFT-2997: bound release notes generation

- docs/config/microshift-starter.ks
- scripts/image-builder/config/kickstart.ks.template
> USHIFT-2975: Fix all kickstart files not to use nmcli

- scripts/image-builder/cleanup.sh
Disabling socket can cause composer to fail the shutdown and result in multiple restarts that fail and block later start (at the end of the script).
Instead, stop workers first to keep composer from reactivating via socket, then stop the composer.
> USHIFT-2992: Image builder cleanup: don't stop osbuild-composer.socket

- test/resources/oc.resource
Tests may fail with timeouts when waiting for resources. See [this example](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_microshift/3257/pull-ci-openshift-microshift-main-metal-bootc-test-arm/1781984173133664256/artifacts/metal-bootc-test-arm/openshift-microshift-e2e-metal-tests/artifacts/scenario-info/cos9-src@storage/log.html).
Raising the timeout to 60s should improve test stability in CI running 15-20 VMs at the same time. In addition, it should not hurt the overall functionalily of the tests.
> USHIFT-3018: Increase CI resource wait default timeout to 60s

- test/bin/pyutils/build_bootc_images.py
- test/bin/pyutils/common.py
These changes should attain a usability feature parity with the build_images.sh script:
* Atexit terminates running subprocesses and bib containers
* The `--build-type` argument allows for filtering build by a specified type
* Force rebuild option 
* The `--no-extract-images` skips container image extraction procedure
* Junit handling for better integration in CI
> USHIFT-3113: Enhancements for build_bootc_image.py script

- test/resources/microshift-rpm.resource
- test/suites/optional/multus.robot
- test/suites/optional/olm.robot
- test/suites/standard1/version.robot
Follow-up on the https://github.com/openshift/microshift/pull/3296 fix.
Added the `rpm -V` tests on all installed MicroShift RPM packages:
* In the standard1 suite, which is run on both rpm and ostree configurations
* In the optional suite for olm / multus tests to cover the extra package checks
> OCPBUGS-31661: Add MicroShift RPM verification tests

- assets/components/ovn/multi-node/master/daemonset.yaml
- assets/components/ovn/single-node/master/daemonset.yaml
OVN assets are edited manually due to [this comment](https://github.com/openshift/microshift/blob/main/scripts/auto-rebase/rebase.sh#L747) in the rebase.sh file.
> USHIFT-3005: Remove ovsdb-server/memory-trim-on-compaction setting from OVN configuration

- docs/contributor/devenv_setup.md
- scripts/devenv-builder/configure-vm.sh
- scripts/devenv-builder/manage-vm.sh
- scripts/get-latest-rhocp-repo.sh
The following minor fixes were implemented:
* In devenv docs, change the OS version to 9.4 and increase the disk size requirements to 100GB
* In manage-vm.sh script, change the default OS version and increase the default VM disk size to 100GB
* In configure-vm.sh script, fix a crash during the initial bootstrap by adding a more flexible search for Makefile version file.
> USHIFT-3127: Update docs and scripts for support RHEL 9.4 devenv

- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
Also fixes [USHIFT-3131](https://issues.redhat.com//browse/USHIFT-3131)
> USHIFT-3125: Switch to using non-beta RHEL 9.4 container images for bootc

- test/bin/pyutils/build_bootc_images.py
- test/image-blueprints/layer5-bootc/group0/rhel94-bootc-base.containerfile
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc.image-bootc
- test/scenarios-bootc/el94-src@backup-and-restore-on-reboot.sh
- test/scenarios-bootc/el94-src@backups.sh
- test/scenarios-bootc/el94-src@greenboot.sh
- test/scenarios-bootc/el94-src@log-scan.sh
- test/scenarios-bootc/el94-src@multi-nic.sh
- test/scenarios-bootc/el94-src@optional.sh
- test/scenarios-bootc/el94-src@osconfig.sh
- test/scenarios-bootc/el94-src@standard-suite2.sh
- test/scenarios-bootc/el94-src@storage.sh
Also fixes [USHIFT-2926](https://issues.redhat.com//browse/USHIFT-2926)
> USHIFT-2963: Start using RHEL-9.4 ISO for booting RHEL-based tests

- test/bin/scenario.sh
- test/image-blueprints/layer3-periodic/group1/rhel92-source-isolated.image-installer
- test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.image-installer
- test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
- test/kickstart-templates/includes/post-fips.cfg
- test/kickstart-templates/kickstart-liveimg.ks.template
- test/kickstart-templates/kickstart.ks.template
- test/scenarios-periodics/el94-src@fips-rpm.sh
- test/scenarios-periodics/el94-src@fips.sh
- test/scenarios-periodics/el94-src@isolated-net.sh
- test/scenarios-periodics/el94-src@offline.sh
- test/scenarios-periodics/el94-src@rpm-standard1.sh
- test/scenarios-periodics/el94-src@rpm-standard2.sh
The [FIPS blueprint customization](https://osbuild.org/docs/user-guide/blueprint-reference/#fips) is not supported for edge-commits, so it cannot be used in `image-installer` due to the current MicroShift bluepring organization. Instead, we explicitly pass `fips=1` when booting the VM and call `fips-mode-setup` in kickstart.
The following message is produced by `fips-mode-setup` command when run in kickstart.
```
Setting system policy to FIPS
Note: System-wide crypto policies are applied on application start-up.
It is recommended to restart the system for the change of policies to fully take place.
FIPS mode will be enabled.
Now you need to configure the bootloader to add kernel options "fips=1 boot=UUID=<your-boot-device-uuid>" and reboot the system for the setting to take effect.
``` …
> USHIFT-2210: Run FIPS tests on RPM and ostree-based RHEL 9.4 systems

- assets/release/release-aarch64.json
- assets/release/release-x86_64.json
- packaging/images/openshift-ci/Dockerfile.test-runtime
- scripts/image-builder/config/registries.conf.template
- scripts/verify/verify-images.sh
- test/kickstart-templates/includes/post-containers.cfg
- test/suites/network/isolated-network.robot
Also switched to the latest ubi9 image. 
> Note that neither ubi9-minimal nor ubi9-micro contain the `openssl` executable we need.
> OCPBUGS-30039: Switch to registry.redhat.io images for OpenSSL dependency in TopoLVM

- test/resources/SkipTests.py
- test/run.sh
Closes Jira [USHIFT-2463](https://issues.redhat.com/browse/USHIFT-2463)
Add `--prerunmodifier` [flag](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#programmatic-modification-of-test-data) to RF execution in `run.sh` to skip tests by name.
Example:
`./test/run.sh -o /Users/agullon/workspace/microshift/_output/_output -i /Users/agullon/workspace/microshift/_output/rf_variables.yaml -k 'CLI Output,ConfigMap Matches CLI' -v /Users/agullon/workspace/microshift/_output/venv suites/standard1/version.robot`
```
+ /Users/agullon/workspace/microshift/_output/venv/bin/robot --randomize all --prerunmodifier 'resources/SkipTests.py:CLI Output,ConfigMap Matches CLI' --loglevel TRACE -V /Users/agullon/workspace/microshift/_output/rf_variables.yaml -x junit.xml --outputdir …
```
> USHIFT-2463: Add PreRunModifier flag to skip RF

- packaging/rpm/microshift.spec
- test/bootc-sources/microshift_repo_config.sh.template
- test/kickstart-templates/includes/post-cos9rpm.cfg
- test/resources/microshift-rpm.resource
4.16 ovn-kubernetes and RHCOS are both moved to OVS 3.3:
- https://github.com/openshift/ovn-kubernetes/pull/2142
- https://github.com/openshift/os/pull/1495
MicroShift should be kept in sync.
> OCPBUGS-33588: Upgrade openvswitch package for 4.16

- test/kickstart-templates/includes/post-system.cfg
Follow-up fix on #3352 
The /etc/greenboot/greenboot.conf file does not have the trailing EOL.
> USHIFT-3155: Fix greenboot configuration update

- test/bin/scenario.sh
Add `recreate` command to scenario for single command to destroy and create scenario's VMs
> NO-ISSUE: `scenario.sh recreate` command

- pkg/loadbalancerservice/router.go
There was a mismatch between what the config package IP addresses from the host and the router controller. The config package only gets ipv4 addresses while the router controller takes ipv6 too. This caused a mismatch between allowed/configured IP addresses that triggered fake warning logs about ipv6 entries not allowed in the service (even if they were not configured).
> USHIFT-3177: Use only ipv4 addresses for default router

- scripts/auto-rebase/assets.yaml
- scripts/auto-rebase/rebase.sh
The route API CRD was previously source from the route-controller-manager. This has proven to be problematic since the source file path has change in the last release.  MicroShift should source the CRD from the router repository instead, which should be safer in the future.
The source path used here is `amd64`.  It doesn't matter which arch is manifest is pulled from since the CRD is not arch-dependent.
> NO-ISSUE: Update asset.yaml source for the route crd

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
Changes the readinessProbe of topolvm-controller to use /readyz instead of /metrics.
Removes the initial delay of 10s because we also have a 2s startup probe that ensures that the probes should exist
> OCPBUGS-34491: fix: adjust topolvm controller probes

- packaging/crio.conf.d/00-crio-crun.conf
- packaging/rpm/microshift.spec
> USHIFT-3477: Add explicit crun default runtime configuration for crio

- test/bin/scenario.sh
* The virt-install command is now retried once if any error occurs.
* VM boot timeout is lowered to 20m to save some wait time in case of stuck VMs
* VM greenboot timeout is left on 30m not to miss slow container image downloads
This change should provide a workaround for VM installation problems like ostree pull timeouts ([USHIFT-3136](https://issues.redhat.com//browse/USHIFT-3136)), stuck ARM VM on reboot ([USHIFT-3152](https://issues.redhat.com//browse/USHIFT-3152)), etc.
See [this log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_microshift/3448/pull-ci-openshift-microshift-main-metal-bootc-test-arm/1799480463887175680/artifacts/metal-bootc-test-arm/openshift-microshift-infra-iso-boot/artifacts/scenario-info/cos9-src@backups/boot. …
> USHIFT-3136: Retry virt-install command in case of installation error

- test/bin/scenario.sh
> [release-4.15] USHIFT-3276: Retry virt-install command in case of installation error

- test/resources/SkipTests.py
- test/run.sh
Manual cherry-pick from https://github.com/openshift/microshift/pull/3343
> [release-4.15] USHIFT-2463: Add PreRunModifier flag to skip RF

- test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
microshift 4.15 RPM still specifies `crio >= 1.25` and doesn't ship its own `crun` runtime definition for crio. When it gets newest crio (>= 1.29), the test fails because crio exits shortly after startup.
This PR introduces a workaround: explicitly adds missing file to the blueprint.
When 4.15 RPM has its crio version fixed, we can remove the workaround.
> NO-ISSUE: Add runtime crun to crio for y-2 blueprint

- scripts/devenv-builder/configure-vm.sh
When $current_minor beta mirror is enabled we may also need the $previous_minor rhocp repo enabled. This is necessary for example for some scenarios.
> NO-ISSUE: Enable rhocp repos if mirror is used

- test/agent/microshift-test-agent.service
- test/agent/microshift-test-agent.sh
- Remove `/bin/bash` from the `ExecStart` so `microshift-test-agent.sh` is used in journal leading to easier debbuging.
- Add 5s stop timeout, to (hopefully) not receive two SIGTERMs in a row which can lead to _cleanup function to running completely and breaking the test.
- Don't fail if no file matches `/etc/ssh/ssh_host*key` wildcard
> NO-ISSUE: microshift-test-agent improvements

- Makefile
- packaging/images/Containerfile.rpm-builder
ART changed build images to use `dnf` wrapper script. 
Fix the MicroShift build image configuration to use the `dnf.real` executable directly.
Other minor enhancements include adding comments and build command optimization.
> USHIFT-3734: Avoid using build image dnf wrapper script

- assets/components/lvms/topolvm-controller_deployment.yaml
- assets/components/lvms/topolvm-node_daemonset.yaml
topolvm pods are the only who  missing the target.workload.openshift.io/management annotation:
```
oc get pods -o jsonpath='{range .items[*]}{.metadata.name}{" -- "}{.metadata.annotations.target\.workload\.openshift\.io/management}{"\n"}{end}' -A
csi-snapshot-controller-75d4fbc9df-c7cpz -- {"effect":"PreferredDuringScheduling"}
csi-snapshot-webhook-8547f88946-ktj89 -- {"effect":"PreferredDuringScheduling"}
dns-default-grvvs -- {"effect": "Preferredoc get pods -o jsonpath='{range .items[*]}{.metadata.name}{" -- "}{.metadata.annotations.target\.workload\.openshift\.io/management}{"\n"}{end}' -A
csi-snapshot-controller-75d4fbc9df-c7cpz -- {"effect":"PreferredDuringScheduling"}
csi-snapshot-webhook-8547f88946-ktjoc get pods -o jsonpath='{range .items[*]}{.metadata.name}{" -- …
```
> USHIFT-3733: add management annotation to topolvm pods

- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/network.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/network.go
> USHIFT-3473: Add validations for network ipv4/ipv6 stacks

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/loadbalancerservice/controller.go
- pkg/loadbalancerservice/router.go
> OCPBUGS-36587: Filter ip family in router service controller

- test/image-blueprints/layer1-base/group2/rhel92-microshift-yminus2.toml
- test/image-blueprints/layer1-base/group2/rhel93-microshift-yminus2.toml
- test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-crel.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-base.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-fake-next-minor.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source-with-optionals.toml
- test/image-blueprints/layer2-presubmit/group1/rhel94-source.toml
- test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
- test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
- test/image-blueprints/layer3-periodic/group1/rhel94-source-with-optionals.toml
- test/image-blueprints/layer5-bootc/group1/cos9-bootc-source.containerfile
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source.containerfile
- test/kickstart-templates/includes/post-greenboot.cfg
- test/kickstart-templates/includes/post-system.cfg
- test/kickstart-templates/kickstart-centos.ks.template
- test/resources/libostree.py
The greenboot RPM released in RHEL 9.x OS overwrites the `/etc/greenboot/greenboot.conf` customizations (see https://github.com/fedora-iot/greenboot/issues/142).
Work around this issue by:
* ostree: include the customization in blueprints
* bootc: include the customization in containerfiles
* rpm: apply the customization after installing MicroShift (and greenboot) RPMs
> USHIFT-3503: Properly apply greenboot timeout increase in blueprints and container files

- test/resources/oc.resource
- test/suites/standard2/workload-partitioning.robot
> USHIFT-3742: test if all the running pods are annotated for workload partitioning

- assets/components/ovn/common/configmap.yaml
- assets/components/ovn/single-node/master/daemonset.yaml
> USHIFT-3740: ovnk configuration changes for ipv6

- test/image-blueprints/layer1-base/group2/rhel94-microshift-previous-minor.toml
Need to include dnf and subscription-manager packages in the base ostree image to enable RPM package installation when building containers.
If those packages are not included in the ostree commit, the container image produced by `rpm-ostree` does not have these utilities, so any `dnf install` command present in the derived container builds fails.
A follow-up on https://github.com/openshift/microshift/pull/3625.
> USHIFT-3749: Add subscription-manager to the base ostree image to enable DNF install in containers

- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- pkg/config/config.go
Allows configuring only one of them, keeping old behavior for both ipv4 and ipv6.
> USHIFT-3761: Set default networks separately

- test/bin/scenario.sh
- test/kickstart-templates/includes/post-system.cfg
- test/scenarios/el92-yminus2@el94-src@upgrade-ok.sh
For some reason, when using only `Storage=persistent`, the journal on first boot is not persistent. This causes some upgrade tests fail when they depend on counting amount of boots.
> NO-ISSUE: Missing persistent journal on 1st boot when installing using rhel94 iso

- test/bin/common_versions.sh
Example of error messages when run on a Fedora OS
```
$ cat /etc/redhat-release 
Fedora release 39 (Thirty Nine)
$ source ./test/bin/common_versions.sh 
Error: Unknown repo: 'rhocp-4.16-for-rhel-9-x86_64-rpms'
Error: Unknown repo: 'rhocp-4.15-for-rhel-9-x86_64-rpms'
```
> NO-ISSUE: Fix common versions script not to produce errors for non-existent repos

- test/assets/ipv6-network.xml
- test/bin/scenario.sh
- test/kickstart-templates/includes/post-containers.cfg
- test/resources/kubeconfig.resource
- test/resources/microshift-network.resource
- test/scenarios/el94-src@ipv6.sh
- test/suites/ipv6/singlestack.robot
> USHIFT-3001: Add initial RF ipv6 tests

- assets/components/openshift-router/service-cloud.yaml
- assets/components/openshift-router/service-internal.yaml
- assets/components/ovn/single-node/master/daemonset.yaml
- pkg/components/render.go
- scripts/auto-rebase/rebase.sh
> USHIFT-3479: ipFamilyPolicy adjustments and ovnk restart on dual stack migration

- scripts/devenv-builder/manage-vm.sh
- test/assets/dual-stack-network.xml
- test/assets/hello-microshift-service-ipv6.yaml
- test/bin/common.sh
- test/bin/manage_hypervisor_config.sh
- test/resources/libipv6.py
- test/scenarios/el94-src@dual-stack.sh
- test/suites/ipv6/dualstack.robot
> USHIFT-3772: Dual stack RF e2e tests

- cmd/generate-config/config/config-openapi-spec.json
- docs/user/howto_config.md
- etcd/vendor/github.com/openshift/microshift/pkg/config/config.go
- etcd/vendor/github.com/openshift/microshift/pkg/config/storage.go
- packaging/greenboot/functions.sh
- packaging/greenboot/microshift-running-check.sh
- packaging/microshift/config.yaml
- packaging/rpm/microshift.spec
- pkg/components/csi-snapshot-controller.go
- pkg/components/storage.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/storage.go
- pkg/config/storage_test.go
- test/resources/oc.resource
- test/suites/standard1/configuration.robot
- test/suites/tuned/microshift-tuned.robot
> USHIFT-706: Add CSI Deployment Flag and Config

- test/bin/scenario.sh
I verified that any failure to the installation now invokes the kickstart [%onerror handler](https://github.com/openshift/microshift/blob/main/test/kickstart-templates/includes/onerror-logs.cfg).
The terminal output looks like this:
```
[   33.517655] anaconda[2628]: Installing.
[   34.520412] anaconda[2628]: The installation was stopped due to an error which occurred while running in non-interactive cmdline mode. Since there cannot be any questions in cmdline mode, edit your kickstart file and retry installation.
[   34.520498] anaconda[2628]: The exact error message is:
[   34.520680] anaconda[2628]: Non interactive installation failed: The command 'ostree container image deploy --sysroot=/mnt/sysimage --image=192.168.100.1:5000/rhel94-bootc-source --transport=registry' exited with the …
```
> USHIFT-3494: Add explicit command line mode to virtual machine creation

- test/bin/manage_hypervisor_config.sh
The bug introduced by https://github.com/openshift/microshift/pull/3716
> USHIFT-3780: Fix cleanup-all option in manage_hypervisor_config.sh

- packaging/rpm/microshift.spec
- test/image-blueprints/layer5-bootc/group1/rhel94-bootc-source-ostree-parent.containerfile
- test/kickstart-templates/includes/post-cos9rpm.cfg
Following ovn-k and RHCOS updates:
https://github.com/openshift/ovn-kubernetes/pull/2273
https://github.com/openshift/os/pull/1596
Depends on: https://issues.redhat.com/browse/ART-10428
previous bump: https://github.com/openshift/microshift/pull/3350
> OCPBUGS-38974: Update openvswitch to 3.4

- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/install-microshift/files/01-crio-metrics.conf
- ansible/roles/install-microshift/tasks/main.yml
- Add cri-o config to re-enable metrics as it was in MicroShift 4.15
- Disable prestart of cri-o service
> USHIFT-4059: Add crio metrics config to ansible scripts

- packaging/imagemode/Containerfile.repobase
Konflux pipelines do not allow for checking our repositories and copying external files when building container images.
> NO-ISSUE: Make Containerfile.repobase self contained to be used in build pipelines

- test/bin/manage_hypervisor_config.sh
Minor fix in the cleanup procedure to avoid errors like the following, which aborts the script in the middle:
```
$ bash -x ./test/bin/manage_hypervisor_config.sh cleanup
...
...
+ sudo virsh net-info isolated
+ sudo virsh net-info ipv6
++ sudo virsh net-dumpxml ipv6
++ yq -p xml .network.bridge.+@name
+ bridge_name=virbr3
+ sudo ip link del name virbr3p0
Cannot find device "virbr3p0"
```
> NO-ISSUE: Fix manage_hypervisor_config.sh script to finish cleanup procedure

- packaging/rpm/microshift.spec
Manual cherry-pick of https://github.com/openshift/microshift/pull/3913
> [release-4.17] USHIFT-4338: Declare openvswitch3.3 package as obsolete to allow seemless upgrade to openvswitch3.4

- Makefile
- docs/contributor/devenv_setup.md
- scripts/fetch_tools.sh
This change also contains an optimization for how hadolint is used. This is necessary to avoid SELinux context setting on an NFS-mounted partition. 
Note that `container_file_t` SELinux context is still required for running container images off the mounted directory. But, unlike the context for hadolint that was always set on verify, the `container_file_t` is only set in case of NFS mount.
> USHIFT-4385: Add devenv instructions on mounting shared directory

- test/bin/pyutils/build_bootc_images.py
- test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-isolated.containerfile
- test/image-blueprints/layer5-bootc/group2/microshift-imagestore-config.sh.template
- test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-isolated.containerfile
- test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
- test/scenarios-bootc/periodics/el94-src@isolated-net.sh
When rehearsing the current change, detected a few unrelated problems and opened follow-up issues:
* [The onerror handler in CI kickstart reboots the VM without returning failure](https://issues.redhat.com//browse/USHIFT-4520)
* [The ostree2bootc upgrade test may fail when switching the layer](https://issues.redhat.com/browse/USHIFT-4518)
* [The osconfig-lifecycle test may fail in CI](https://issues.redhat.com/browse/USHIFT-4519)
> USHIFT-4336: Implement embedded container build support in bootc tests

- scripts/image-builder/configure.sh
- test/bin/build_images.sh
Also fixed wrong job count in the parallel command options. Each job parameters are added in quotes, which means 1 parameter per job for count, not 2. Before the fix, the `--jobs 0` argument was used due to `1 / 2 = 0`.
```
download_opts+=("${expected_iso_file} ${download_url}")
```
Comparing wget and aria2 download speeds on a local workstation.
```
$ time wget -O centos9-wget.iso "https://mi
rrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-late
st-x86_64-dvd1.iso&redirect=1&protocol=https"
centos9-wget.iso     100% [==============================>]   10.79G   31.09MB/s
[Files: 1  Bytes: 10.79G [31.51M]
real    5m50.796s
user    0m5.486s
sys     0m16.325s
$ time aria2c -x 4 -s 4 -o centos9-aria2.is
o "https://mirrors.centos.org/mirrorlist?path=/9-stream/BaseOS/ …
```
> USHIFT-4547: Add timeout and retries to ISO downloads when building images

- test/README.md
Without this package the router smoke test fails with following error:
```
Start / End / Elapsed: 	20241007 13:54:13.779 / 20241007 13:54:13.781 / 00:00:00.002
13:54:13.779 	TRACE 	Arguments: [ '${result.stdout}' | '${result.stderr}' ]
13:54:13.780 	INFO
13:54:13.781 	INFO 	/bin/sh: line 1: avahi-resolve-host-name: command not found
13:54:13.781 	TRACE 	Return: None
```
> NO-ISSUE: Add avahi-tools requirement for router smoke test

- test/agent/microshift-test-agent.service
- test/agent/microshift-test-agent.sh
* Started to use systemd notify mechanism to signal service readiness
* Run cleanup actions on exit, rather than watching selected signals
* Minor bash syntax optimizations
* Optimized the wait loop in the script to avoid unwanted interruptions of the sleep command
> USHIFT-4684: Optimize microshift-test-agent code to avoid race conditions

- scripts/image-builder/mirror-images.sh
- test/README.md
- test/bin/ci_phase_boot_and_test.sh
- test/bin/common.sh
- test/bin/mirror_registry.sh
- test/bin/pyutils/build_bootc_images.py
- test/bin/scenario.sh
- test/kickstart-templates/includes/post-containers.cfg
- test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
- test/scenarios-bootc/periodics/el94-prel@el94-src@upgrade-ostree2bootc-ok.sh
- test/scenarios-bootc/periodics/el94-src@isolated-net.sh
- test/scenarios-bootc/presubmits/el94-src@downgrade-block.sh
- test/scenarios/presubmits/el94-src@ipv6.sh
The functional changes include:
* Consolidation of Web and Registry URL definition using VM bridge interface, or host name if libvirt is not configured
* Mirror registry script uses an external storage and configuration file
* Bootc containerfile and container encapsulate builds save artifacts to the mirror registry directly bypassing file system export.
* Mirror registry startup is implicit when running bootc builds
* Mirror registry is no longer optional
These changes should result in reduced resource consumption and reduced runtime of the builds.
**Test prerequisites**
* Delete `_output`
* `sudo podman rmi -af && podman rmi -af && podman volume rm -af`
* Run `./test/bin/build_rpms.sh` and download cache.
* Compare bootc build times and disk space
**Test results on AWS `c5n.metal` …
> USHIFT-4704: Port bootc build procedure to directly use mirror registry instead of local storage

- test/suites/standard1/kustomize.robot
Manual cherry-pick from https://github.com/openshift/microshift/pull/4060
> [release-4.16] USHIFT-4707: Add greenboot healthcheck after reboot on ostree system

- test/suites/standard1/kustomize.robot
Manual cherry-pick from https://github.com/openshift/microshift/pull/4060
> [release-4.17] USHIFT-4706: Add greenboot healthcheck after reboot on ostree system

- pkg/admin/autorecovery/backup.go
- pkg/admin/autorecovery/restore.go
- pkg/admin/autorecovery/state.go
- pkg/admin/autorecovery/state_test.go
- pkg/admin/autorecovery/storage.go
- pkg/admin/autorecovery/storage_test.go
- pkg/admin/data/atomic_dir_copy.go
- pkg/admin/data/data_manager.go
- pkg/admin/data/types.go
- pkg/admin/prerun/system.go
- pkg/cmd/admin.go
- pkg/util/util.go
- test/suites/backup/auto-recovery.robot
Adds two new options to `microshift restore` command:
- `--auto-recovery` to run the procedure of restoring the most recent backup from provided directory
- `--save-failed` to opt-out from making a copy of current MicroShift data to "failed" subdirectory
> USHIFT-4117: Auto Recovery: Restore

- assets/optional/flannel/05-daemonset.yaml
Recently one of user experienced that putting the cni plugin binary to `/usr/libexec/cni` location causing failure because of read only file system like below. Hopefully this will fix it.
```
$ oc logs kube-flannel-ds-rlksq -n kube-flannel -c install-cni-plugin
cp: can't create '/usr/libexec/cni/flannel': Read-only file system
9:08
```
> NO-ISSUE: Use /run/cni/bin location for flannel cni

- test/kickstart-templates/includes/post-bootc-wa.cfg
- test/kickstart-templates/kickstart-bootc.ks.template
https://github.com/containers/bootc/pull/417 has landed to support a workaround directly on the bootc side.
> USHIFT-2927: Remove fstab workaround in kickstart

- test/image-blueprints/layer3-periodic/group1/rhel94-crel-with-optionals.toml
The problem was introduced in [this commit](https://github.com/pacevedom/microshift/commit/8f6c92dc75259e0c6d65e342b486139d67d18794).
Otherwise, the following error is encountered during the rpm-ostree builds.
```
ERROR: BlueprintsError: rhel-9.4-microshift-crel-optionals: DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: microshift-gateway-api-4.18.0~ec.2-202410101849.p0.ge6b2865.assembly.ec.2.el9
blueprint: rhel-9.4-microshift-crel-optionals v0.0.1
```
> NO-ISSUE: Remove microshift-gateway-api from rhel94-crel-with-optionals.toml until the package is published on mirror

- test/image-blueprints/layer3-periodic/group1/rhel94-source-isolated.toml
- test/image-blueprints/layer5-bootc/group2/cos9-bootc-source-isolated.containerfile
- test/image-blueprints/layer5-bootc/group2/rhel94-bootc-source-isolated.containerfile
- test/kickstart-templates/kickstart-bootc-isolated.ks.template
- test/kickstart-templates/kickstart-isolated.ks.template
- test/scenarios-bootc/periodics/cos9-src@isolated-net.sh
- test/scenarios-bootc/periodics/el94-src@isolated-net.sh
- test/scenarios/periodics/el94-src@isolated-net.sh
- test/suites/network/isolated-network.robot
A problem was discovered with how container images were preloaded for isolated tests in bootc configurations. This led to a question on why the [isolated-network.robot](https://github.com/openshift/microshift/blob/main/test/suites/network/isolated-network.robot) tests were passing. Apparently, it was due to the [post-containers.cfg](https://github.com/openshift/microshift/blob/main/test/kickstart-templates/includes/post-containers.cfg) configuration in kickstart that opened up access to the mirror registry from the isolated VMs. The network routing to the mirror registry on the hypervisor works via the libvirt bridge IP.
This PR addresses fixes the container image embedding in the bootc configurations, adds a test for verifying no container image access from VMs and introduces a dedicated …
> USHIFT-4724: Isolated tests must not have access to mirror registry

- packaging/imagemode/Containerfile.repobase
- packaging/imagemode/Containerfile.repourl
- packaging/imagemode/Containerfile.rhocp
The upgrades occasionally cause problems, like the following one:
```
Running transaction
[build]   Preparing        :                                                        1/1 
[build]   Upgrading        : microcode_ctl-4:20230808-2.20240910.1.el9_4.noarch     1/2 
[build]   Running scriptlet: microcode_ctl-4:20230808-2.20240910.1.el9_4.noarch     1/2 
[build] /var/tmp/rpm-tmp.rIQFD8: line 18: /dev/kmsg: Read-only file system
[build] 
[build]   Running scriptlet: microcode_ctl-4:20230808-2.20240531.1.el9_4.noarch     2/2 
[build] /var/tmp/rpm-tmp.LaGb5F: line 11: /var/lib/rpm-state/microcode_ctl_un_intel-ucode: No such file or directory
[build] /var/tmp/rpm-tmp.LaGb5F: line 13: /var/lib/rpm-state/microcode_ctl_un_ucode_caveats: No such file or directory
[build] /var/tmp/rpm-tmp.LaGb5F: …
```
> ART-10563: Remove dnf upgrade from image mode container builds

- scripts/devenv-builder/configure-vm.sh
Gateway API is a dev preview future, meaning there are no guarantees on testing/docs.
When running conformance there is one issue with terminationMessagePolicy values in istio pods that can not be overridden by the operator with current options/configuration.
The RPM is installed using the common script configure-vm.sh which takes all optional packages and installs them. Since this feature is not ready yet for conformance, and the proper fix depends on another team we are disabling the install temporarily.
Other e2e tests will keep testing the feature, as it is included in some of the scenarios.
> USHIFT-4757: Skip installing gateway-api as optional rpm

- scripts/mirror-images.sh
> USHIFT-4737: Add tag and digest capabilities to mirror script

- scripts/devenv-builder/create-vm.sh
- scripts/devenv-builder/manage-vm.sh
This is usefull for cases where the default storage pool doesn't have sufficient capacity e.g.
```
WARNING  The requested volume capacity will exceed the available pool space when the volume is fully allocated. (102400 M requested capacity > 87253 M available)
```
Usage:
```
export MICROSHIFT_VOL_POOL=<your custom volume pool>
./scripts/devenv-builder/manage-vm.sh create -n ${VMNAME}
Creating VM microshift-dev from /var/lib/libvirt/images//rhel-9.4-x86_64-dvd.iso ...
...
Allocating 'microshift-dev.qcow2 | 100 GB  00:00:00     
...
VM online
.
.
.
virsh vol-list --pool my_pool | grep microshift
microshift-dev.qcow2        /root/dell/disks/dev-scripts/pool/microshift-dev.qcow2
```
Note this doesn't affect the iso location, you can still use `/var/lib/libvirt/images/` for the iso
> NO-ISSUE: Allow using custom pool for the dev vm disk

- packaging/rpm/microshift.spec
Created a follow-up [USHIFT-5108](https://issues.redhat.com/browse/USHIFT-5108) issue to fix the version requirements in 4.19 branch.
> NO-ISSUE: Relax cri-o versioning requirement before full transition to 1.32

- test/scenarios-bootc/periodics/el95-crel@published-images-standard1.sh
- test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
- test/scenarios-bootc/presubmits/el95-src@standard-suite1.sh
RHEL tests can only be enabled after switching to RHEL 9.6.
> USHIFT-2911: Enable SELinux tests on bootc CentOS 9 Stream

- test/suites/greenboot/greenboot.robot
Backport of db26897ecadadd5cf88290dc89bb814cd8d4d709
> [release-4.18] USHIFT-5223: Fix greenboot test to properly handle stdout

- packaging/greenboot/functions.sh
- scripts/multinode/configure-pri.sh
- scripts/multinode/configure-sec.sh
- test/bin/ci_phase_boot_and_test.sh
To test a CNCF fix in pre-submits, the c3710444498c9d3142ddfbebd2f0c01557c4807b was implemented to temporarily disable CNCF test exclusion. It must be reverted before merging the PR.
> USHIFT-5228: Use microshift healthcheck for verifying cncf multinode health

- test/bin/scenario.sh
- test/kickstart-templates/includes/main-network.cfg
- test/scenarios-bootc/presubmits/el95-src@ipv6.sh
- test/scenarios/presubmits/el94-src@ipv6.sh
Besides the importance of "clean" testing environment, this is necessary to avoid ~2m delays when booting IPv6 VMs. See the [THEEDGE-4109](https://issues.redhat.com//browse/THEEDGE-4109) for details.
> THEEDGE-4109: Explictly disable IPv4 in anaconda for IPv6 single stack scenarios

- ansible/roles/add-kubelet-logging/tasks/main.yml
- ansible/roles/create-service-account/tasks/main.yml
- ansible/roles/create-vm/defaults/main.yml
- ansible/roles/install-logging-exporters/defaults/main.yml
- ansible/roles/install-microshift/defaults/main.yml
- ansible/roles/install-microshift/files/01-crio-metrics.conf
- ansible/roles/manage-repos/defaults/main.yml
- ansible/roles/manage-repos/tasks/create-mirrors.yaml
- ansible/roles/manage-repos/tasks/main.yml
- ansible/roles/manage-repos/templates/ocpbeta.repo.j2
- ansible/roles/microshift-start/files/ready.sh
- ansible/roles/microshift-start/tasks/main.yml
- Update RHEL iso to 9.4
- Create longer lived metrics token
- Modify beta repo templates
- Improve start timing for CSI pods
- Remove comments & rename step
- Update cadvisor
- Add metrics_host to crio metrics config
> USHIFT-4277: Small fixes including update for beta mirror changes

- okd/src/README.md
- okd/src/microshift-okd-multi-build.Containerfile
This will helpful for offline run of the container image. It is also helpful for podman desktop scenario where only have to pull image once and run it fast even on slow network connnectivity.
By accident I deleted this branch from my fork and #4376 got closed and I am not able to reopen it :(
> NO-ISSUE: okd: Add step to embed all component images to final image

- okd/src/microshift-okd-multi-build.Containerfile
The verify job does not run container file check because it's using a hadolint container, so this error was missed in https://github.com/openshift/microshift/pull/4388.
```
./okd/src/microshift-okd-multi-build.Containerfile:70 DL4006 [1m[93mwarning[0m: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
./okd/src/microshift-okd-multi-build.Containerfile:70 SC2046 [1m[93mwarning[0m: Quote this to prevent word splitting.
make: *** [Makefile:180: verify-containers] Error 1
```
> NO-ISSUE: Fix hadolint errors in OKD container file

- pkg/config/debugging.go
- pkg/config/debugging_test.go
To Address https://github.com/openshift/microshift/issues/4399
- and the kube-scheduler-operator has already set the TraceAll to 10, as seen in https://github.com/openshift/cluster-kube-scheduler-operator/blame/b1cc4471e2f6c5dc81b2b9471f4634f1ecdb88b4/pkg/operator/targetconfigcontroller/targetconfigcontroller.go#L267
> NO-ISSUE: update TraceAll loglevel to 10

- docs/contributor/image_mode.md
> USHIFT-5286: Update image mode document with bootc image builder (BIB)

- assets/components/openshift-router/cluster-role-aggregate-admin-route.yaml
- assets/components/openshift-router/cluster-role-aggregate-edit-route.yaml
- assets/components/openshift-router/cluster-role-system-router.yaml
- pkg/components/controllers.go
- scripts/auto-rebase/assets.yaml
> OCPBUGS-48110: Update router cluster roles

- pkg/components/networking.go
- pkg/config/ovn/ovn.go
- pkg/config/ovn/ovn_test.go
- pkg/util/net.go
determine if the host has a default gateway  based on IPv4 or IPv6 routes, then use its MTU,
the original solution was based on net.GetHostIP which didn't cover cases when we  dont have any network connection (hardcoded nodeIP with loopback) .
> OCPBUGS-38468: use default route mtu

- test/bin/scenario.sh
I had to add a trailing slash to the `wget` command, because it would get redirected and wouldn't download the `.cfg` files otherwise, I'm not sure how it has worked so far.
> USHIFT-4726: Attempt console login in offline tests

- okd/src/microshift-okd-multi-build.Containerfile
During the github runner on arm64, found out that running configure-vm script fails with following error. After debugging it in the runner looks like in the container after creating the `microshift` user the `/etc/shadow` file permission is not updated. This is only happening with github ubuntu-arm runner. This PR fixes it.
```
STEP 15/16: RUN echo '{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}' > /tmp/.pull-secret &&    /src/scripts/devenv-builder/configure-vm.sh --no-build --no-set-release-version --skip-dnf-update /tmp/.pull-secret &&    /src/okd/sr
c/use_okd_assets.sh --replace ${OKD_REPO} ${OKD_VERSION_TAG}
sudo: PAM account management error: Authentication service cannot retrieve authentication info
```
- https://github.com/praveenkumar/minp/actions/runs/13047611605/job/36400806209
> NO-ISSUE: okd: Add read permission to /etc/shadow

- packaging/images/Containerfile.ci-brew
- packaging/images/Makefile
- packaging/images/README.md
See https://docs.ci.openshift.org/docs/how-tos/external-images/ for more information.
The CI changes are in https://github.com/openshift/release/pull/61099
> USHIFT-5281: Implement MicroShift CI image build rules and docs

- test/bin/mirror_registry.sh
Should help mitigating the following errors in CI.
```
2025-02-09T16:04:16.683889000Z gunicorn-registry stdout | 2025-02-09 16:04:16,679 [330] [ERROR] [gunicorn.error] Error handling request /v2/auth?account=microshift&scope=repository%3Amicroshift%2Frhel94-bootc-yminus2%3Apull%2Cpush&scope=repository%3Amicroshift%2Frhel94-bootc-prel%3Apull&service=i-020da06ecb9dac2ef.us-west-2.compute.internal%3A5000
2025-02-09T16:04:16.683942000Z gunicorn-registry stdout | Traceback (most recent call last):
2025-02-09T16:04:16.683970000Z gunicorn-registry stdout |   File "/app/lib/python3.9/site-packages/peewee.py", line 2993, in connect
2025-02-09T16:04:16.684005000Z gunicorn-registry stdout |     self._state.set_connection(self._connect())
2025-02-09T16:04:16.684032000Z gunicorn-registry stdout | …
```
> USHIFT-5367: Increase the max_connections setting of Postgres to improve mirror registry stability

- docs/config/Containerfile.bootc-rhel9
- docs/contributor/image_mode.md
- packaging/imagemode/Containerfile.repobase
- packaging/imagemode/Containerfile.repourl
- packaging/imagemode/Containerfile.rhocp
- packaging/imagemode/Makefile
- packaging/imagemode/README.md
- test/image-blueprints-bootc/layer1-base/group1/rhel94-bootc-base.containerfile
- test/image-blueprints-bootc/layer1-base/group1/rhel94-test-agent.containerfile
- test/scenarios-bootc-containers/presubmits/el94-src@standard-suite1.sh
- test/scenarios-bootc/periodics/el94-crel@optional-sigstore.sh
- test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
- test/scenarios-bootc/presubmits/cos9-src@standard-suite1.sh
- test/scenarios-bootc/presubmits/el94-src@standard-suite1.sh
- test/scenarios/periodics/el94-crel@optional-sigstore.sh
- test/scenarios/periodics/el94-src@rpm-standard1.sh
- test/scenarios/presubmits/el94-src@standard-suite1.sh
- test/suites/standard1/version.robot
This is a manual cherry-pick of https://github.com/openshift/microshift/pull/4531
> [release-4.18] USHIFT-5352: Use EUS bootc base images and prevent unintended OS version upgrade

- test/run.sh
This is a manual cherry-pick from: https://github.com/openshift/microshift/pull/3769
> [release-4.14] USHIFT-4867: error in microshift RF tests randomize parameter

- test/bin/build_rpms.sh
- test/bin/ci_phase_iso_build.sh
This should not interfere with ART pipelines because those are not using MicroShift build_rpms.sh script.
> NO-ISSUE: Enable flannel RPM build by default in build_rpms.sh

- test/kickstart-templates/includes/post-network.cfg
> USHIFT-5402: Handle DUID in ipv6 test harness

- scripts/devenv-builder/manage-vm.sh
- test/bin/scenario.sh
- test/kickstart-templates/includes/post-network.cfg
- test/scenarios-bootc/presubmits/el94-src@dual-stack.sh
> [release-4.18] USHIFT-5435: Handle DUID for ipv6 CI tests

- scripts/devenv-builder/configure-vm.sh
when all the RPMs  installed together  it introduces instability in conformance-optional-components tests
> OCPBUGS-51186: skip installing ai-model and low-latency  optional RPMs 

- scripts/mirror-images.sh
- test/bin/pyutils/build_bootc_images.py
- test/bin/pyutils/common.py
See the JIRA [comment](https://issues.redhat.com/browse/USHIFT-5288?focusedId=26660602&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26660602) for performance and disk size differences when mirroring multi-platform vs single-platform images.
> USHIFT-5288: Mirroring of images in CI should be performed for the current platform only

- pkg/healthcheck/healthcheck.go
- test/suites/optional/healthchecks-disabled-service.robot
If microshift optional RPMs were installed, but microshift is not enabled, primary healthcheck will exit early without an error.
This doesn't hold for other healthchecks - there's no check if microshift.service is enabled, it just proceeds to querying the API server.
Result is that optional healthchecks fail greenboot even if MicroShift is disabled.
> USHIFT-5381: Check microshift.service for all healthchecks

- scripts/mirror-images.sh
- test/bin/mirror_registry.sh
The `mirror_registry.sh` script is run automatically on every `build_bootc_images.sh` invocation and the process takes ~1m after all the images were mirrored. This is annoying in development environment.
With the optimizations in the PR commits, the repetitive run time was brought down to 10-15s. Interestingly, the majority of time was taken by suboptimal `find+chmod` operations.
> USHIFT-5406: Optimize mirror images operation for repetitive runs

- test/scenarios-bootc/periodics/el94-crel@published-images-standard1.sh
- test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh
- test/scenarios-bootc/periodics/el96-crel@published-images-standard1.sh
- test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
- test/scenarios-bootc/presubmits/el96-src@standard-suite1.sh
- test/scenarios/periodics/el94-src@rpm-standard1.sh
After switching to RHEL 9.6 bootc base images, the SELinux functionality should be fully functional.
> USHIFT-2911: Enable SELinux tests in standard suite for bootc images

- assets/optional/observability/00-namespace.yaml
- assets/optional/observability/01-service-account.yaml
- assets/optional/observability/02-cluster-role.yaml
- assets/optional/observability/03-cluster-role-binding.yaml
- assets/optional/observability/kustomization.yaml
- etcd/vendor/github.com/openshift/microshift/pkg/config/kubeconfig.go
- packaging/observability/90-enable-microshift-observability.preset
- packaging/observability/microshift-observability.service
- packaging/observability/opentelemetry-collector.yaml
- packaging/rpm/microshift.spec
- pkg/cmd/init.go
- pkg/config/kubeconfig.go
- scripts/auto-rebase/assets.yaml
- test/image-blueprints-bootc/layer2-source/group2/rhel96-bootc-source-optionals.containerfile
- test/image-blueprints-bootc/layer2-source/group3/cos9-bootc-source-optionals.containerfile
- test/resources/journalctl.py
- test/suites/optional/observability.robot
> TRACING-4752: Add OpenTelemetry-Collector as optional sub-package

- docs/config/Containerfile.bootc-embedded-rhel9
Embedding bash commands in `ExecStartPre=` is cumbersome. 
Simplify the docs by creating a separate script.
> OCPBUGS-52420: Fix container file documentation with correct image embedding commands

- scripts/advisory_publication/advisory_publication_report.py
[USHIFT-5569](https://issues.redhat.com//browse/USHIFT-5569): Fix advisory publication report
- Set ticket resolution always as string to fix issues when not defined
> USHIFT-5569: Fix advisory publication report

- test/bin/ci_phase_iso_build.sh
- test/bin/manage_build_cache.sh
- test/bin/mirror_registry.sh
- test/bin/pyutils/build_bootc_images.py
Attempt copying container images from the local mirror registry to container storage and skip the builds if the copy succeeds. The `--force-rebuild` flag overrides this behavior by always rebuilding the images.
The time saving seems to be around 5m for the image build step as that's the time it takes to build `layer1` when ISO images are skipped.
Notes: 
* The times are approximate and they may vary slightly. 
* To focus on the effect of the current change, only the `infra-iso-build` times are presented
* The PR test history can be viewed [here](https://prow.ci.openshift.org/pr-history/?org=openshift&repo=microshift&pr=4718).
* Build step is the "same" for pre-submit and periodic tests
|Job Type|Duration Before the Change|Duration After the Change| …
> USHIFT-5461: Implement S3 caching for container images in layer1

- packaging/rpm/microshift.spec
Open vSwitch 3.1 is EoL upstream and so the support of this version in FDP is limited.  To ensure timely bug fix delivery for 4.14+ we need to upgrade to the current LTS stream, which is Open vSwitch 3.3. It will be fully supported for much longer.
This change follows a corresponding move of RHCOS at https://github.com/openshift/os/pull/1774 and OVN-Kubernetes at https://github.com/openshift/ovn-kubernetes/pull/2492 to the same OVS 3.3.  MicroShift should stay in sync.
The plan is to get this change to 4.15 once corresponding os and ovn-kubernetes PRs are in, and then backport to 4.14 when corresponding os and ovn-kubernetes PRs are backported.
> [release-4.15] OCPBUGS-54714: Upgrade openvswitch package version to 3.3

- test/bin/pyutils/build_bootc_images.py
- test/bin/pyutils/common.py
- test/image-blueprints-bootc/layer1-base/group1/rhel96-test-agent.containerfile
- test/image-blueprints-bootc/layer1-base/group2/rhel96-bootc.image-bootc
- test/scenarios-bootc/periodics/el96-crel@brew-standard1.sh
- test/scenarios-bootc/presubmits/el96-src@standard-suite1.sh
Note that [USHIFT-5584](https://issues.redhat.com/browse/USHIFT-5584) issue was opened to revert the current workaround when RHEL 9.6 is in GA.
> USHIFT-5580: Use CentOS base image for RHEL 9.6 ISO creation until GA

- assets/optional/ai-model-serving/kserve/kustomization.yaml
- assets/optional/ai-model-serving/kustomization.yaml
- assets/optional/ai-model-serving/runtimes/kustomization.yaml
- docs/user/ai_model_serving.md
- packaging/rpm/microshift.spec
- scripts/auto-rebase/assets_ai_model_serving.yaml
- scripts/ci-ai-model-serving/tests/06-test-vllm.sh
- test/image-blueprints-bootc/layer3-periodic/group1/ai-model-serving-test-data.sh.template
- test/suites/ai-model-serving/ai-model-serving-offline.robot
- test/suites/ai-model-serving/ai-model-serving-online.robot
Split AIMS manifest into two parts to enable user to add a manifest in between that overrides the kserve settings.
> USHIFT-5568: Split AI Model Serving manifest

- test/bin/scenario.sh
- test/resources/qemu-guest-agent.py
> USHIFT-5621: qemu-ga tweaks: add timeouts, increase read file buffer, use subprocess lib

- scripts/auto-rebase/rebase.sh
> USHIFT-5531: Auto-rebase procedure with flannel and kube-proxy image update

- test/bin/scenario.sh
- test/scenario_settings.sh.example
This PR address to add a new option to scenario.sh to target any given VM.
For example: ./test/bin/scenario.sh run ./test/scenarios/periodics/el94-src@rpm-standard1.sh <vm_ip>
Closes https://issues.redhat.com/browse/USHIFT-5528
> USHIFT-5528: Add new option to scenario.sh to target any given VM

- pkg/cmd/init.go
- pkg/controllers/kube-controller-manager.go
- pkg/controllers/kube-controller-manager_test.go
- pkg/controllers/kube-scheduler.go
- pkg/util/net.go
Manual cherry-picking from https://github.com/openshift/microshift/pull/4868
Addressing snyk errors:
```bash
✗ [Medium] Path Traversal
ID: 7154f7f8-a0c9-42ec-b8b7-dc8727837ddf Path: pkg/cmd/init.go, line 614   
Info: Unsanitized input from file name flows into os.RemoveAll, where it is used as a path. This may result in a Path Traversal vulnerability and allow an attacker to delete arbitrary files
✗ [Medium] Improper Certificate Validation   
ID: cd1300f4-2c30-4395-b9cd-31e44905379f   
Path: pkg/util/net.go, line 91   
Info: TrustManager might be too permissive: The client will accept any certificate and any host name in that certificate, making it susceptible to man-in-the-middle attacks.
```
> USHIFT-5712: Snyk fixes

- scripts/devenv-builder/configure-composer.sh
- scripts/devenv-builder/configure-vm.sh
**Which issue(s) this PR addresses**: [USHIFT-5575](https://issues.redhat.com//browse/USHIFT-5575)
This PR checks to see if an internal rpm repo is configured for the host and if so configures osbuild repos as well.
> Configure internal RHEL 9.6 repos for osbuild.

- scripts/auto-rebase/assets.yaml
fixing in rebase `periodic-ci-openshift-microshift-main-rebase-on-nightlies` jobs
```log
2025-05-16 23:59:41,998     DEBUG      Copying assets/crd/0000_03_config-operator_01_securitycontextconstraints.crd.yaml <- _output/staging/release-manifests/0000_03_config-operator_01_securitycontextconstraints-Default.crd.yaml
Traceback (most recent call last):
File "/go/src/github.com/openshift/microshift/scripts/auto-rebase/handle_assets.py", line 162, in <module>
main()
File "/go/src/github.com/openshift/microshift/scripts/auto-rebase/handle_assets.py", line 155, in main
handle_dir(asset)
File "/go/src/github.com/openshift/microshift/scripts/auto-rebase/handle_assets.py", line 129, in handle_dir
handle_file(file, dst, new_src_prefix)
File …
```
> USHIFT-5763: file naming issue in config-operator scc 

- test/bin/scenario.sh
virt-insall is using .treeinfo  to [find](https://github.com/virt-manager/virt-manager/blob/f901c3277768a30c92daccc066b01784dccc1a05/virtinst/install/urldetect.py#L55) the correct kernel location , and if its missing incorrect default assumed.
microshift is running `virt-install` for starting  VMs  using `--location` (its appending kernel cmdline),
similiar issue also described in  https://github.com/osbuild/bootc-image-builder/issues/265#issuecomment-2446241061
kernel location is set by osbuild [here](https://github.com/osbuild/images/blob/a1bfcfe91c97e6ec9d17176d66b908de31661711/internal/manifest/iso_tree.go#L101-L112)
> USHIFT-5772:  explicitly specify kernel path when running virt-install

- test/bin/scenario.sh
manual cherry-pick of https://github.com/openshift/microshift/pull/4936
> [release-4.19] USHIFT-5773: explicitly specify kernel path when running virt-install

- test/suites/standard2/configuration.robot
Manual backport from https://github.com/openshift/microshift/pull/4939 PR
Added a condition to skip checking a cipher when it's not available, for example, when FIPS mode is enabled.
> [release-4.19] USHIFT-5775: TLS config RF test: skip cipher if not available

- test/suites/standard1/router.robot
Manual cherry-pick from https://github.com/openshift/microshift/pull/4958
> [release-4.19] USHIFT-5778: Stop excluding router security tests

- test/suites/tuned/workload-partitioning.robot
Added a condition to skip non-core MicroShift pods from `Pod Must Be Annotated` check
> USHIFT-5774: skip checking non-core pods from being annotated

- test/suites/router/router.robot
PR aims to fix recent issues where `Router Verify Security Configuration` test would fail because the namespace does not exist.
> NO-ISSUE: Add teardown for "Router Disabled" test

- scripts/devenv-builder/configure-vm.sh
In response to recent submgr problems:
```
+ 13:01:45.476308967 ./scripts/devenv-builder/configure-vm.sh:127 	sudo subscription-manager status
+ 13:01:55.896149642 ./scripts/devenv-builder/configure-vm.sh:128 	sudo subscription-manager register --auto-attach
This system is already registered. Use --force to override
+ 13:01:56.178021077 /bin/bash:1 	finalize
```
> USHIFT-5816: SubMgr: register force & get 'status' output

- packaging/rpm/microshift.spec
ovn-kubernetes container image moved to OVS 3.5 in: https://github.com/openshift/ovn-kubernetes/pull/2593 as part of 4.19 to 4.18 sync: https://issues.redhat.com//browse/OCPBUGS-48710
We should keep OVS versions between microshift and ovn-k in sync.
> [release-4.18] OCPBUGS-58139: Upgrade openvswitch package to 3.5.

- pkg/controllers/telemetry.go
> OCPBUGS-57777: Change poll interval for first metrics send

- test/scenarios-bootc/periodics/el94-crel@published-images-standard2.sh
- test/suites/standard2/configuration.robot
Revert of the 8ddd520d470301d31c6f6e6f6f408a3591e27e44 commit
> [release-4.18] USHIFT-5527: Revert Skip 'default config' test on crel

- test/scenarios-bootc/periodics/el96-crel@published-images-standard2.sh
- test/suites/standard2/configuration.robot
Manual revert of https://github.com/openshift/microshift/pull/4487/commits/aa1552d98563e99ed415619434014c51e8abfbe0
> USHIFT-5526: Renable default config test on for the current release

- test/assets/observability/otel_config.yaml
- test/suites/optional/observability.robot
centos9 observability test started failing with what appears to be changed logging schema. Because we already have verification of the exporters' capabilities in form of querying Loki and Prometheus, we can remove the journal log matching.
> USHIFT-5897: Observability test: remove debug exporter and journal log matching

- packaging/crio.conf.d/13-microshift-kindnet.conf
With https://github.com/openshift/microshift/pull/5186 "/usr/libexec/cni" is removed from plugin dir which makes kindnet to failed since it checks the plugins from that directory. This pr should add it back only for kindnet usecase.
> NO-ISSUE: kindnet: Add plugin dir for crio config

- packaging/rpm/microshift.spec
- packaging/systemd/firewalld-no-iptables.conf
since  RHEL9.3  with  `Firewalld 1.2.5-1` that includes that fix https://github.com/firewalld/firewalld/pull/1082,
```
[root@i-0f3d2b2a517dceaa9 ~]#  rpm -q --changelog firewalld
* Thu Oct 26 2023 Eric Garver <egarver@redhat.com> - 1.3.4-1
- package rebase to v1.3.4
* Mon Apr 24 2023 Eric Garver <egarver@redhat.com> - 1.2.5-1
- package rebase to v1.2.5
- feat(direct): avoid iptables flush if using nftables backend
```
- can be verified with reloading firewall and verifying   that the nodeport still exists in the iptables.
```
NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP                         PORT(S)                      AGE
router-default            LoadBalancer   10.43.22.136    10.192.10.240,10.42.0.2,10.44.0.0   80:31742/TCP,443:30090/TCP   41h …
```
> USHIFT-1669: remove firewalld  iptables flushing workaround

- test/assets/generic-device-plugin/fake-serial-communication.py
With multiple tests reusing the serial devices, it can happen that a stray empty message is received.
Other unsuccessful way of remediating the problem:
- Removing & reenabling serialsim kmod
- Closing serial devices after done using
> USHIFT-5976: Make GDP test script more robust

- scripts/advisory_publication/advisory_publication_report.py
**Which issue(s) this PR addresses**:  This PR addresses being able to check and retrieve ocp release data from konflux.
```
knarra@knarra-thinkpadx1carbon7th:~/automation/Openshift/microshift/scripts/advisory_publication$ sh advisory_publication_report.sh 4.19.9
{
"RHSA-2025:20444": {
"type": "extras",
"url": "https://gitlab.cee.redhat.com/rhtap-release/advisories/-/raw/main/data/advisories/ocp-art-tenant/2025/20444/advisory.yaml",
"cves": {
"CVE-2024-45339": {}
}
},
"RHSA-2025:20447": {
"type": "image",
"url": "https://gitlab.cee.redhat.com/rhtap-release/advisories/-/raw/main/data/advisories/ocp-art-tenant/2025/20447/advisory.yaml",
"cves": {
"CVE-2024-45339": {},
"CVE-2025-22869": {
"jira_ticket": {
"id": "OCPBUGS-52524",
"summary": "CVE-2025-22869 microshift: Denial of Service in the …
```
> USHIFT-5992: Update script to use release data from konflux

- ansible/roles/common/tasks/disk.yml
- ansible/roles/configure-firewall/tasks/main.yml
- ansible/roles/fetch-kubeconfig/defaults/main.yml
- ansible/roles/fetch-kubeconfig/tasks/main.yml
- ansible/roles/microshift-start/tasks/main.yml
- ansible/roles/setup-microshift-host/tasks/main.yml
- ansible/roles/setup-microshift-host/tasks/storage.yml
- ansible/roles/setup-microshift-host/templates/lvmd.yaml.j2
- Fix disk.yaml variable names for clarity
- Rework local kubeconfig management in fetch-kubeconfig role
- Handle if firewalld is masked
- local_action is being depricated
- More robust lvm handling and support for configuring lvmd.conf
> USHIFT-6028: ansible: few more fixes across roles

- scripts/fetch_tools.sh
- test/bin/ci_phase_boot_and_test.sh
- test/bin/common.sh
- test/bin/scenario.sh
- test/scenarios-bootc/releases/el96-lrel@ginkgo-tests.sh
- test/scenarios/releases/el96-lrel@ginkgo-tests.sh
**Which issue(s) this PR addresses**: Currently scenario.sh does not have support to run gingko test cases(openshift-qe-test-private cases), this PR enables user to run the same on the created microshift vm.
Define function in any of the scenario file using the below way
```
scenario_run_tests() {
run_gingko_tests host1
}
```
And use the command below to run the same. when gingko is not specified it will run robot framework cases
`./test/bin/scenario.sh run ./test/scenarios/presubmits/el96-src@gingko-tests.sh <host>`
Closes #[USHIFT-5983](https://issues.redhat.com//browse/USHIFT-5983)
> USHIFT-5983: Update scenario.sh script to run gingko tests

- Makefile
- packaging/rpm/make-rpm.sh
- packaging/rpm/microshift.spec
- test/bin/build_rpms.sh
Make building the microshift-observabilty package optional.
> USHIFT-5548: Exclude telemetry from community builds

- packaging/crio.conf.d/13-microshift-kindnet.conf
- packaging/rpm/microshift.spec
- test/image-blueprints-bootc/layer4-upstream/group1/centos10-bootc.image-bootc
- test/image-blueprints-bootc/layer4-upstream/group1/cos10-bootc-source.containerfile
- test/package-sources-bootc/microshift-centos10-nfv.repo
- test/scenarios-bootc/upstream/cos10-src@standard-suite1.sh
- test/scenarios-bootc/upstream/cos10-src@standard-suite2.sh
- test/scenarios-bootc/upstream/cos9-src@kindnet.sh
Also addresses [USHIFT-6186](https://issues.redhat.com//browse/USHIFT-6186)
Note that kindnet-related scenarios require more work. See [USHIFT-6190](https://issues.redhat.com/browse/USHIFT-6190)
> USHIFT-6101: Add standard scenario bootc tests on CentOS 10

- test/bin/common_versions.sh
Add check to return from get_vrel_from_rpm() when rpm directory does not exist.
The goal is to remove from the stdout error messages from find command when the directory does not exist.
> USHIFT-6189: Add check to not show errors when file not found
